### ISSUE TITLE
Stuck with irc bridge no longer accessible

### ISSUE THREAD

**Issue by christianlupus** [matrix-org/matrix-appservice-irc#1006]
I wanted to use the IRC bridge to freenode on matrix.org. I went along different guides like [this one](https://github.com/matrix-org/matrix-appservice-irc/wiki/Guide:-How-to-use-Matrix-to-participate-in-IRC-rooms). Especially I found [this](https://github.com/matrix-org/matrix-appservice-irc/wiki/End-user-FAQ#i-am-getting-kicked-out-of-a-bridged-room-with-the--err_needreggednick-error) after I was kicked from a room. Instead of trying it manually I did directly the [automatic version](https://github.com/matrix-org/matrix-appservice-irc/wiki/End-user-FAQ#and-do-it-automatically). I got a message about I had to re-login.
I then joined the desired room (which seems to work now) but another guy soon tells me via mail that I was not found in the room. OK, I thought it could be the re-login thing and issued a logout command to NickServ and closed both the connection to NickServ and the IRC room. Opening the chat with NickServ now causes the problem, that no answer is received from the NickServ anymore. Nothing. I can say whatever I like, I do not get any answer from the server.

I then tried to force a reconnect completely issed `!quit` to the appservice user and left all IRC related rooms. Reopening the connections is possible but the connection seems closed. I can enter `!nick` and I get 
```
Format: '!nick DesiredNick' or '!nick irc.server.name DesiredNick'
Currently connected to IRC networks:
chat.freenode.net as christianlupus[m
```
Changing the nick with `!nick clupus` tells me
```
You are not connected to the network.
```

The incident happend maybe in the last 2 hours totally. To be honest I fear I completely broke my installation and I do not know how to recover.

**Comment by ocdtrekkie** [comment]
Have this exact same issue, no idea what to do.

**Comment by Half-Shot** [comment]
This has been fixed in the latest RC release, and will be shipped out in the morning to the freenode bridge.

**Comment by maxdeviant** [comment]
Running into this issue as well.

If I check `!bridgeversion` with `@appservice-irc:matrix.org` I get `BridgeVersion: 0.16.0`.

@Half-Shot Was the RC release with the fixed pushed out?

**Comment by Half-Shot** [comment]
Not yet. It's going out on Tuesday

**Comment by Half-Shot** [comment]
This went out.
