### ISSUE TITLE
Handle banned IRC clients sensibly

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/matrix-appservice-irc#101]
The Freenode bridge was restarted today and began connecting users as per normal. Eventually, it got to ~250 connections and then started getting the following message on all subsequent connections:
 - `Closing Link: (*** Banned (cache))`

Metrics showed no more connections were being established. Cue panic.

### Summary

tl;dr
- Greatly throttle (as an immediate fix) banned connections where "banned" = receive the following error message:
  - `Closing Link: (*** Banned (cache))`
  - `Closing Link: servername.com (*** Banned )`

  Longer term, we should not attempt to reconnect at all, and expose a `!connect` option so the user            has to explicitly act to reconnect.
- Implement https://github.com/matrix-org/matrix-appservice-irc/issues/56 (Pastebin messages)

---

After asking Freenode staff about this, it turns out that "Banned (cache)" happens when lots of connections from a single IP get rejected because of klines in a short period of time. I protested my innocence naturally - the bridge does ident so why aren't the bans scoped to the username portion? Well it turns out they *are*, at least at first. But:

 > because klines only take effect after the full user details are known, that can eat quite a lot of server resources if someone who's klined is hammering it

So instead, if a single IP address has a number of rejected connections (due to klines) within a certain time frame, that **IP address** will be added to a ban cache so they don't need to waste resources. Looking at the logs, it turns out that there was a single user who got klined who then managed to trigger this heuristic and get the bridge added to the ban cache. Freenode kindly unbanned the bridge and everything slowly recovered.

The person who got k-lined most likely did so by accident. They seemed to have inserted a markdown code block into a channel, which triggered an automatic anti-spam bot who k-lined that ident username. Whilst the bridge *does* do flood delay timers, a continuous flood of messages would still trigger the ban if it was long enough. That wouldn't have been a problem if it weren't for the bridge's reconnection behaviour - it doesn't know that client was banned, so it attempted to reconnect after ~10 seconds, which then naturally failed, ad infitum. This then triggered the ban cache heuristic as the reconnect attempts were frequent enough.

Freenode have agreed to adjust the heuristic somewhat, but there's a lot more the bridge can do under these circumstances. It shouldn't try to reconnect on bans, or if it does it should be extremely infrequent (bans on freenode last a long time, as in 30min ~ days). If a user posts a block of code, the bridge shouldn't try to send them all through at once but should [upload it and send a link](https://github.com/matrix-org/matrix-appservice-irc/issues/56) into the room instead.

**Comment by Kegsay** [comment]
Updated title on this. The main focus of this issue now is to prevent banned clients from blindly trying to reconnect, and expose an explicit mechanism for users to manually attempt to connect again (via a `!connect` option or similar). Note that this is only for bans on a **connection**, rather than a *channel*, which is already handled correctly in 0.4.0

**Comment by Kegsay** [comment]
Really just setting a 10m retry timer on this would prevent us being k-lined and that's good enough until we move to IPv6.

**Comment by Kegsay** [comment]
Set to 1h.

**Comment by monacv** [comment]
any idea why I suddenly got this error?
Is it related to Comcast Xfinity? Do you know how I can resolve it?

`ERROR :Closing Link: c-66-31-107-137.hsd1.ma.comcast.net (*** Banned ) `

I am using pidgin client in Ubuntu 20.04
