### ISSUE TITLE
IRC doesn't do multi-line

### ISSUE THREAD

**Issue by jtagcat** [matrix-org/matrix-appservice-irc#1013]
dowdle: jtagcat: That's a deal breaker. Your last send, which was four lines... didn't print in IRC... but sent a link... that IRC users have to click on and open up in a browser window.

Send 4 messages rapidly, seperately!

(I didn't see a duplicate, but it's hard to believe there isn't a duplcate issue for this)

**Comment by TheDiscordian** [comment]
Looks like a duplicate of #701.

**Comment by jtagcat** [comment]
I guess, it does fit under it.
