### ISSUE TITLE
Changing topic on tombstoned channel leaks to the new room

### ISSUE THREAD

**Issue by vranki** [matrix-org/matrix-appservice-irc#1028]
Situation:

* Channel #A which is bridged to room A. #A has no ops and no +t set.
* Channel #B which is plumbed to room B. Permissions are good.

How to reproduce:

* Create a tombstone event from A to B. 
* Change topic on #A 
* Topic in room B is changed by bridge bot. Topic in #B is not changed.

This creates a vulnerability as attacker can spam via the topic and there is nothing anyone can do.

Better check for any other channel parameters that follow tombstone. Perhaps a tombstoned 
room could even be unbridged automatically. Tested on version 0.13.1 so this may already be fixed but there is no confirmation on that yet.

**Comment by Half-Shot** [comment]
By creating a tombstone in room A to room B without first disconnecting the bridge, you are telling the bridge to connect channel #A to room B. What's happened here is expected, as changing the topic in #A will make B's topic change.

I don't think there is a bug here, tombstones are used for upgrading rooms to fresh new rooms. In the small number of cases where it's used as a redirect to an existing room, users need to first disconnect the thing it's bridged to.
