### ISSUE TITLE
@swedneck:hielle.com started echoing back across the bridge in HQ

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-appservice-irc#1032]
Which is strange, the bridge has the correct nick for him as given by the inspector:

```
    "@swedneck:hielle.com": [
      {
        "channels": [
...
          "#matrix"
        ],
        "dead": false,
        "server": "chat.freenode.net",
        "nick": "swedneck"
      }
```

Only conclusion I can draw from this is that his nick must be incorrectly mapped in the virtualClient object on ClientPool?

**Comment by z3ntu** [comment]
Is this issue about what can be seen in the screenshot?
![image](https://user-images.githubusercontent.com/3768500/79267026-bed54c80-7e98-11ea-9328-362d7b25e4b1.png)

**Comment by Half-Shot** [comment]
yes

**Comment by ra-kete** [comment]
I have that same issue (someone named "<nick>[m]" echoing every message I write). It's rather annoying. Is there anything I can try to make it stop?

**Comment by Half-Shot** [comment]
I've not seen this recently, has anyone else encountered this?

**Comment by z3ntu** [comment]
I've unbanned the `[m]` version of the user in the screenshot at https://github.com/matrix-org/matrix-appservice-irc/issues/1032#issuecomment-613643676 and it's not echoing back for this user anymore so I think it's good now.

**Comment by Half-Shot** [comment]
Okay, not sure what happened. Will close for now.

**Comment by Half-Shot** [comment]
@ara4n was affected by this last night in `#matrix`. He was connected throughout the day absolutely fine, and there are not hints of a re-connection in the logs. However, he also connected with an alt account which tried to claim `Matthew[m]`, which may have caused an issue with the nick -> mxid mappings and caused the bridge to erroneously believe the user wasn't owned by the bridge

**Comment by Half-Shot** [comment]
Still seeing this on some channels. Hard to be sure what is causing it.

**Comment by z3ntu** [comment]
Also happened today again in a channel with the log looking like this:
![image](https://user-images.githubusercontent.com/3768500/95576834-6a6aee00-0a31-11eb-9954-c7465f9765f3.png)

**Comment by Half-Shot** [comment]
I'm hoping this is fixed by https://github.com/matrix-org/matrix-appservice-irc/pull/1146
