### ISSUE TITLE
Folks consistently get surprised at status PMs from the IRC bridge

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-appservice-irc#105]
Perhaps it's because backfill might sometimes go awol over federation, confusing users?  Except in general they seem to be panicked before even trying to accept the invite...

**Comment by ara4n** [comment]
...or perhaps it was that previews don't work over federation, which panicked people

**Comment by ara4n** [comment]
...or perhaps it's because the bot is named ambiguously - if it was "Freenode Bridge Status" rather than the more generic "@appservice-irc:matrix.org" people would be less surprised.

**Comment by Kegsay** [comment]
I'd like to hear some more from people who are being surprised. A lot of this I suspect is going to some down to UX, particularly Vector's UX, which is of no concern to me when developing the IRC bridge. Of course, there may be nice things that I can do to aid UX (like adding metadata to the room or messages within), but those are clearly separate bugs to this.

If this is a federation issue, then there is nothing for me to do here. I am of the opinion that this project will have actionable issues, rather than vague issues which never end up being resolved, so if we can identify exactly what is causing the surprise, I can spin off additional bugs to fix those issues.

**Comment by ara4n** [comment]
well, the point of my comments above was to try to gather explicit feedback about problems folks are facing.  To spell it out again:

 * [ ] The room is cryptically named.  "Freenode IRC Bridge Status" or something would be clearer.
 * [ ] The bridge does not populate the room with scrollback or MOTD or even topic that explains what it is, or what it's for or how to use it.
 * [ ] The user can't preview the room to see what they're getting into. (Yes, this isn't an IRC bridge problem, but it's a contributing factor to the confusion here).

I suggest ignoring the potential federation problem unless someone reports it as a concrete problem.

I will keep asking people whenever they report the confusion (so far just today it's been phaverkamp and fladd) and add the pain points to this.

**Comment by ara4n** [comment]
Please can we at least put an initial message into the room that explains what the room is for and how to use it?  "Hi, i'm your friendly neighbourhood bridge through to the Freenode IRC network. type !help to find out what i can do for you today!"

**Comment by ara4n** [comment]
Right, yet more people getting confused by this.  I got a screenshot last time of what's confusing them - it looks like this:

![image](https://cloud.githubusercontent.com/assets/1294269/18033899/fe2ece9c-6d26-11e6-84df-8aff8025c1df.png)

N.B. that this screenshot is from a federated user and shows that the federation concern was invalid.

All that is needed is the initial message in the room to clarify use and we should be fine.

**Comment by ara4n** [comment]
make... it... stop...

<img width="505" alt="screen shot 2016-08-28 at 20 27 24" src="https://cloud.githubusercontent.com/assets/1294269/18036271/f23c5230-6d5d-11e6-86e7-4890cae9a49d.png">
<img width="552" alt="screen shot 2016-08-28 at 20 27 17" src="https://cloud.githubusercontent.com/assets/1294269/18036272/f2526d54-6d5d-11e6-8b63-16d53f2c8e6a.png">

**Comment by fuloating** [comment]
For a layperson they might not understand or expect receiving anything like that, and then it's even presented to them in a way that seem like they need to make some important action, to reject or preview an invitation. Then it happens again and again (at least if you reject them).

I would prefer it to be something like in irc, that the status window is kind of mandatory and you are not asked to make any decision ever for its presence.  Maybe these messages need not be among the rooms on room list at all in popular clients, just some separate "view status messages" through some sub menu. 

I understand that it might be the easiest to treat them like any other messages between nodes(?) or users like they are now(?) creating a room for it, but right now they appear too intrusive for what they are imo :p

**Comment by Kegsay** [comment]
> make... it... stop...

But the picture is of people whining about the invite, rather than the content of the room post-accept. Either way, totally agreed with the welcome message on new rooms, thanks for updating the labels for me!

**Comment by ara4n** [comment]
yup, the thing i'd like to stop is people whining about the invite.  the reason they whine about it is that they don't understand why they get the invite due to the lack of message:

<img width="845" alt="screen shot 2016-08-30 at 22 32 19" src="https://cloud.githubusercontent.com/assets/1294269/18107923/eeb5ecfc-6f01-11e6-9e8b-6d77df8887c2.png">

**Comment by lukebarnard1** [comment]
How do we feel about the following changes:

Upon joining a network, the bot will invite the user to a room called 'IRC Admin Room', if the admin room does not already exist. The message sent upon connecting to a network now looks like:

> You've been connected to the IRC network 'localhost' as Lukeb[m]. This room can be used to send commands directly through your personal connection to connected IRC networks. Type !help for more information.

Sending '!help' will now give:
```
This is an IRC admin room for sending commands directly to IRC. 
Commands can be sent all as one message, but these will not reply with any information:
	irc.server
	(JOIN [arg0 [arg1 [...]]])
	irc.server2
	(KICK [arg0 [arg1 [...]]])
	(COMMAND [arg0 [arg1 [...]]])
Or if feedback is desired, the following commands can be used:
	!join irc.example.com #channel [key]
	!nick irc.example.com DesiredNick
	!whois nick
```

**Comment by ara4n** [comment]
Can we please switch the text to:

> You've joined a Matrix room which is bridged to the IRC network 'localhost', where you are now connected as Lukeb[m].
> This room shows any errors or status messages from IRC, as well as letting you control the connection - type !help for more information

...and then we're done :)

**Comment by Kegsay** [comment]
This was done.
