### ISSUE TITLE
Can't start docker container

### ISSUE THREAD

**Issue by meatballs** [matrix-org/matrix-appservice-irc#1058]
I'm trying to get my bridge up and running for the first time using the docker container but I get:

```
2020-05-26 16:07:10 INFO:IrcBridge Using PgDataStore for Datastore
2020-05-26 16:07:10 ERROR:CryptoStore Could not load private key ENOENT: no such file or directory, open 'passkey.pem'.
(node:1) DeprecationWarning: prom-client - Passing a non-object to metrics constructor is deprecated
2020-05-26 16:07:10 ERROR:CLI Failed to run bridge.
2020-05-26 16:07:10 ERROR:CLI undefined
```

I followed the instructions in the docker readme, and I've created the .pem file in the dockerdata directory.

I did have to alter the volume parameter from what the readme says - I mapped my dockerdata directory to /data (rather than /app/data) because it seemed to be looking in that directory for my config.yaml

**Comment by meatballs** [comment]
This turned out to be the passwordEncryptionPath setting in config.yaml which needs to include the /data directory.

**Comment by erciccione** [comment]
I'm having the same error while trying to run the bridge. I'm not using Docker, i'm using the instructions in the readme and the how-to guide. None of this guides mention a `passkey.pem` file. What am i missing?
