### ISSUE TITLE
#stripe is seeing two messages for each user

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-appservice-irc#1073]
https://matrix.to/#/!BAXLHOFjvDKUeLafmO:matrix.org/$ThJUkF73GkogJnrukIjTUC9j3Ln5xQzWVdDK92UrkU4?via=matrix.org&via=feneas.org&via=privacytools.io

**Comment by Half-Shot** [comment]
This was fixed by a restart, but the question remains how the IrcEventBroker managed to allow two messages to slip by for each user.

**Comment by Half-Shot** [comment]
Thinking about this a bit more, this might just be #27

**Comment by simonmichael** [comment]
Since the recent bridge upgrade/restart (I assume) I am seeing intermittent double messages from IRC users. Eg:

![Screen Shot 2020-07-04 at 8 25 39 AM](https://user-images.githubusercontent.com/10144/86516864-1b317380-bdd9-11ea-91b2-ee273b84bf97.png)

**Comment by Half-Shot** [comment]
I believe this might have been fixed now.
