### ISSUE TITLE
Remove "enter" from matrix-messages

### ISSUE THREAD

**Issue by natrius** [matrix-org/matrix-appservice-irc#1079]
Hello, 
enter should be removed if a message is sent to irc as IRC does not seem to process enter at all. This results in an link and this annoys a lot of people. I mean, now i know it and so i don't use enter anymore (if i think about that). 

I'm not sure if this is possible and if you need more information, please tell. 

Best regards

**Comment by Half-Shot** [comment]
I'm not sure what you mean by "enter". I'm also really not sure what you mean by links either. Could you show a screenshot as an example?

**Comment by natrius** [comment]
https://en.wikipedia.org/wiki/Enter_key When pressing shift-enter it is possible to create a paragraph in one message. When this is done, the guys in IRC will get a link to an matrix.org site where the message is stored. Unfortunately i was not able to reproduce it right now. The text got split into 3 seperate texts for IRC. I'm not completely sure right now.

**Comment by Half-Shot** [comment]
Oh you're asking to drop the line splitting feature. Yes, when users send messages with lots of paragraphs it causes issues because sending huge blocks of text to IRC is frowned upon. In order to combat this, we permit a maximum of 3 lines / (or ~500 characters) before it gives you a link to the message in order to reduce spam. 

Certainly we could improve this behaviour, but the behaviour isn't going to be removed.

**Comment by natrius** [comment]
Not removed either. 

The problem was, when opening this ticket, i wrote a message, entered one "shift-enter" for a paragraph and the guys in IRC got a link and not a split message (that would be 2 seperate messages out of mine with one paragraph). 

An esxample is

`11:54:22 * Negreheb sent a long message: < https://matrix.org/_matrix/media/r0/download/matrix.org/vLoxywNKYeFYStEKJZMFkuht >`

The link is working and is provided by matrix. And i have written more without any break. With the last test it was because of the "shift-enter" and not the lenght. Or the "shift-enter" added so much length i reached the max-length, because one test last time with 

```
test
enter
test
```

was correctly split into three sperate message like you said. 

So, now i'm confused to be honest what length creates what behaviour.

**Comment by Half-Shot** [comment]
Because the line splitter allows a *maximum* of 3 lines. Have you tried doing 4 lines?

**Comment by natrius** [comment]
Ah, i see https://github.com/matrix-org/matrix-appservice-irc/blob/master/config.sample.yaml there the 3 lines as default. Basically this resolves imho in this https://github.com/matrix-org/matrix-appservice-irc/issues/701 ticket. Thanks for your help :)
