### ISSUE TITLE
Hot reloading support

### ISSUE THREAD

**Issue by dalcde** [matrix-org/matrix-appservice-irc#1084]
It would be helpful to be able to hot reload a new configuration file without restarting the whole bridge, which is fairly noisy and disruptive. There were attempts at #5 but as far as I can tell, they were not successful.

**Comment by Half-Shot** [comment]
It would be good to have yeah, some config options could be done on the fly but there are certainly things which would not be possible to change at runtime. Suspect we could put it on the roadmap for the near future.

**Comment by dalcde** [comment]
One useful and presumably not difficult one to have is reloading the 
channel mappings.

**Comment by Half-Shot** [comment]
We've started building out hot-reload support in matrix-appservice-bridge in https://github.com/matrix-org/matrix-appservice-bridge/pull/207. The next strep will be loading selected bits of config dynamically in the bridge.
