### ISSUE TITLE
URLs of uploaded images should have a file extension

### ISSUE THREAD

**Issue by ttepasse** [matrix-org/matrix-appservice-irc#1085]
Currently the IRC equivalent of Matrix images looks like this:

> Matrixuser uploaded an image: image.png (26KB)
> < https://matrix.org/_matrix/media/r0/download/example.org/qXNYnYjcyfyxXwEQkkQPlsxi >

Modern IRC Clients like Textual parse text to highlight the URLs and if the URLs seems to be an image download and display the image inline. One of the criteria for displaying URL content inline is a file extension, e.g. https://example.org/image.png​. Matrix URLs are missing that extension, making the experience of reading Matrix users in an IRC channel a little more annoying.

**Comment by Half-Shot** [comment]
Turns out you can do `https://matrix.org/_matrix/media/r0/download/example.org/qXNYnYjcyfyxXwEQkkQPlsxi/image.png` to determine a file name.
