### ISSUE TITLE
Howto use migrate-db-to-pgres.sh

### ISSUE THREAD

**Issue by cremesk** [matrix-org/matrix-appservice-irc#1086]
hello 👋
has any of you migrated your database to postgresql?
I'm just wondering how best to do it.
i have currently create the pgsql db. this is ready.

i found also the migration script:
https://github.com/matrix-org/matrix-appservice-irc/blob/master/scripts/migrate-db-to-pgres.sh

But how do I use this now?
Thanks for your help.

**Comment by Half-Shot** [comment]
Hey!

So it's an area that is poorly documented, but I'll try to explain it. The tool is useful if you have an existing database using NeDB, the file based database that creates `rooms.db` and `users.db`. If you are installing from fresh, you do not need to to run the script.

To run the script, you execute `./migrate-db-to-pgres.sh -d DATABASE_DIRECTORY -c POSTGRES_CONNECTION_STRING -p PATH_TO_PRIVATE_KEY`.

Where:

- `DATABASE_DIRECTORY` is the absolute path to your database files.
- `POSTGRES_CONNECTION_STRING` is the string you would put in your config (see https://github.com/matrix-org/matrix-appservice-irc/blob/master/config.sample.yaml#L511).
- `PATH_TO_PRIVATE_KEY` is the absolute path to the private key you used for encrypting user passwords (see https://github.com/matrix-org/matrix-appservice-irc/blob/master/config.sample.yaml#L466), if you use one.

**Comment by cremesk** [comment]
Thanks for the explanation! It works wonderfully here.

**Comment by Half-Shot** [comment]
I've since written a wiki page. https://github.com/matrix-org/matrix-appservice-irc/wiki/Migrating-from-NEdB-to-PostgreSQL
