### ISSUE TITLE
Erroneous nick changes on freenode

### ISSUE THREAD

**Issue by shinenelson** [matrix-org/matrix-appservice-irc#11]
I've been trying to change my nick using the appservice (@appservice-irc:matrix.org) on the freenode server.

It doesn't change my nick, but informs me of some other nick change after a long time (3-9 minutes). I making a wild guess that the nick change request is getting timed out and NickServ is just sending the last nick change as response.

I've noticed this only on freenode. I tried on MozNet (@mozilla-irc:matrix.org) and it worked with no issues.

PS : I'm attaching a screenshot for reference.

![screenshot from 2015-12-13 03-50-26](https://cloud.githubusercontent.com/assets/4771718/11764202/c675bde0-a14c-11e5-912d-cb187a071171.png)

**Comment by Kegsay** [comment]
Your guess is most likely correct. The bridge will send a `NICK` and then listen for the name change. If this doesn't happen, it doesn't currently timeout the listen so will then respond with the next nick change coming down that client connection. The bridge really needs to send errors back to your matrix account - see https://matrix.org/jira/browse/BOTS-86 for the issue.

**Comment by Kegsay** [comment]
Filed as https://matrix.org/jira/browse/BOTS-130 - Closing this one to keep everything in one place, thanks!

**Comment by Kegsay** [comment]
https://github.com/matrix-org/matrix-appservice-irc/issues/45
