### ISSUE TITLE
Support node 10.16

### ISSUE THREAD

**Issue by dalcde** [matrix-org/matrix-appservice-irc#1104]
Support for node 10.16 was removed in https://github.com/matrix-org/matrix-appservice-irc/commit/43cdd1970c353aa284a7ce8a5b40cd101538ec84 . However, it appears that everything still works if we run it on node 10.16 with the `--experimental-workers` flag. It would be helpful if `matrix-appservice-irc` officially supported using node 10.16 under this flag, since Ubuntu 20.04 only comes with node 10, not node 12.

**Comment by Half-Shot** [comment]
We're not going to officially support node 10.16, but as you point you you can continue to run with the `--experimental-workers` flag for now. For Ubuntu you can setup https://github.com/nodesource/distributions or https://github.com/nvm-sh/nvm for newer versions of Node.
