### ISSUE TITLE
matrix mentions/nick translation broken after upgrade

### ISSUE THREAD

**Issue by ajs124** [matrix-org/matrix-appservice-irc#1127]
I recently upgraded my matrix-appservice-irc instance from 0.17.0 to 0.20.1.
Previously, when I @mentioned someone on the same homeserver in a bridged room, it would translate their matrix name to the IRC nick they set up. Now it does not do that anymore.

**Comment by Half-Shot** [comment]
Are you sure it does that, we've never implemented logic to translate Matrix Mentions -> IRC nicks, only IRC nicks -> Matrix mentions. You probably want https://github.com/matrix-org/matrix-appservice-irc/issues/1094

**Comment by ajs124** [comment]
I could have sworn it used to do that, but rolling back to 0.17.0 doesn't do it, either.
