### ISSUE TITLE
Member list not syncing for some channels 

### ISSUE THREAD

**Issue by creativenothing** [matrix-org/matrix-appservice-irc#1134]
I have been running a matrix-irc bridge on Debian with a few bridged channels for some time now. Today I tried to add a new channel to the bridge by stopping the bridge from running, editing config.yaml to include the new bridges, and restarting the bridge. However, my old bridges are no longer syncing the member list. The new bridge syncs the user lists just fine. 

When I start the bridge, the bot (MatrixBridge) enters the IRC rooms it is bridged to, and the bridge is working in that messages go through on both sides, it's only that the member list isn't syncing, and only for my old bridges.

**Comment by Half-Shot** [comment]
Hmm, can you post your configuration for membership syncing?

**Comment by creativenothing** [comment]
This ended up being resolved very mysteriously--I changed nothing, but a few hours later the channels started syncing again. I couldn't find anything in the logs that showed (1) what was wrong in the first place or (2) what changed to make it work again. Thank you for your reply though.
