### ISSUE TITLE
bridgedClient.displayName not updated properly

### ISSUE THREAD

**Issue by cg505** [matrix-org/matrix-appservice-irc#1136]
https://github.com/matrix-org/matrix-appservice-irc/commit/ebce68e401a42917a1b39da38c83827ead53b80e#diff-823d38bb29473c121c9c3ec50262f9fcL984 (The link is kind of broken, go to MatrixHandler.js and expand and you should be able to see it.)

This line was dropped in the conversion to typescript. Since displayName is now never updated, there is weird behavior when trying to change back to your original displayName.

**Comment by nikhiljha** [comment]
What it used to/should(?) be:

https://github.com/matrix-org/matrix-appservice-irc/blob/dda2d16b3a67c205d7720d7508852c084c895f28/src/bridge/MatrixHandler.js#L983-L990

What it is:

https://github.com/matrix-org/matrix-appservice-irc/blob/ebce68e401a42917a1b39da38c83827ead53b80e/src/bridge/MatrixHandler.ts#L984-L990

**Comment by Half-Shot** [comment]
Fixed by #1137 hopefully.
