### ISSUE TITLE
Maximum for a bridged room is 100

### ISSUE THREAD

**Issue by TNTBOMBOM** [matrix-org/matrix-appservice-irc#1138]
**Describe the bug**
I have matrix room (bridged to telegram) and i want to bridge it to our IRC room, When i add the IRC bot from matrix room apps it show the message:

"Failed to make link: This room has 1182 users, but the maximum for a bridged room is 100."

To check out our matrix room is [#whonix:tchncs.de](https://matrix.to/#/#whonix:tchncs.de) , IRC room on OFTC is #whonix , Telegram [@whonix](https://t.me/Whonix)

**Desktop (please complete the following information):**
 - OS: [Debian]
 - Desktop Element installed from element-debian repository
 - Version [1.7.7]

**Additional context**
This has been discussed in #irc:matrix.org

**Comment by Half-Shot** [comment]
Hi, we don't support bridging in 1000s of users (particularly ones on Telegram) because it means we would need to create 1000s of connections on IRC for those users. Since we have a maximum capacity for our bridge, we try to have a fair usage policy of <=100 users in a room before it caps off.
