### ISSUE TITLE
Unable to bridge a previously bridged room

### ISSUE THREAD

**Issue by TurBoss** [matrix-org/matrix-appservice-irc#1166]
hello,

**the bug**
I'm getting this error when requesting irc integration again
```
Bridge returned HTTP 500 Internal Server Error: Room failed validation. You may be attempting to "double bridge" this room. Error: 1
```

**To Reproduce**

I un bridged the room from IRC because appservice was kicking all discord users that where joining the room (from self hosted discord AS)
now that there is no irc bridge discord users can join fine..
but I'm unable to bridge to IRC again

Thanks

**Comment by Half-Shot** [comment]
Hi there, if I recall correctly we typically don't allow rooms to be bridged to the matrix.org freenode bridge if they contain discord users due to the amount of connections they typically use up. I can look into exemptions for it though.

**Comment by TurBoss** [comment]
Hello, 
This room has been bridget to irc freenode,  discord, and gitte,r without issues until some moths ago while the appservice started to kick new users that joined from discord, thats why i unbridged.

Now I would like to bridge again if this is supported

The room in question is !ioXBMPfgjvfkudUWgT:matrix.org

Thank you so much!

**Comment by Half-Shot** [comment]
Where would you like to bridge it to, and who is the IRC op who can vouch for the bridge on the IRC side?

**Comment by TurBoss** [comment]
oh sorry I forgot to mention... my bad

freenode: #hazzy
chanOP: hazzy

Thanks!

**Comment by TurBoss** [comment]
I can gain OP but need the other guy to cme online

sorry for the inconvenience

**Comment by Half-Shot** [comment]
I'll try to sort it out tomorrow for you. Feel free to reach out in a PM if I don't get back to it.
