### ISSUE TITLE
'Voice only' Freenode channels are spammed by a crazy amount of "changed the power level to" messages

### ISSUE THREAD

**Issue by erciccione** [matrix-org/matrix-appservice-irc#1180]
A channel on Freenode was recently object of some spam. To temporarely fix, the OPs made the channel voice only. Beside breaking the bridge and being not allowed to write anything, the channels are full of spammy messages. See the gif:

![spamfest](https://user-images.githubusercontent.com/28106476/98137160-960ab800-1eb9-11eb-8bd0-48c45862ecf3.gif)

This happens to all three channels currently restricted. As you can see, this problem makes the chat almost unreadable.

**Comment by Half-Shot** [comment]
This is pretty serious, as it absolutely murders clients and homeservers alike. Because voice modes are drip-fed to us, we probably need to add a sensible grace period when setting power levels.
