### ISSUE TITLE
Late-arriving federation messages are forwarded as-is, causing confusion

### ISSUE THREAD

**Issue by vberger** [matrix-org/matrix-appservice-irc#1190]
**Is your feature request related to a problem? Please describe.**

When servers are cut federation-wise for some time and finally manage to reconnect (as occurred to me recently, see https://github.com/matrix-org/synapse/issues/8747 ), several old messages are then forwarded across federation, and the IRC bridge will happily replay them IRC-side.

However, this causes such message to arrive to IRC completely cut from their context (especially if the federation was only faulty in one direction), and can cause confusion / misunderstandings in the IRC room.

**Describe the solution you'd like**

Probably the bridge could do something if it detects messages that arrive quite late (by inspecting the `origin_server_ts` maybe). I currently have mainly two ideas in mind:

- simply drop the old messages, as the conversation they relate to is probably finished and they are no longer relevant
- forward them, but add a prefix to the message indicating that it was sent a long time ago (several hours or days), and probably no longer relate to the current conversation

**Comment by Half-Shot** [comment]
This is controlled by the config flag `dropMatrixMessagesAfterSecs`, which defaults to 5 minutes. If this is your own install then you can change that as you see fit.

**Comment by vberger** [comment]
Oh, thanks. I didn't realize at the time, but the late-message replay indeed occurred on a privately-owned bridge only. I'll see about that thanks.
