### ISSUE TITLE
New 0.23.0 tag not available after git pull

### ISSUE THREAD

**Issue by twouters** [matrix-org/matrix-appservice-irc#1197]
Not sure why, but the tag isn't listed after a git pull.  
Github mentions the following on [the last commit](https://github.com/matrix-org/matrix-appservice-irc/commit/f36ac2793fee517a8658be302aefbaf039b735cc): 

> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

**Comment by Half-Shot** [comment]
```
git fetch --tags
git checkout 0.23.0
```

**Comment by twouters** [comment]
uhm, that does work :man_facepalming:
