### ISSUE TITLE
Doesn't work with guest access

### ISSUE THREAD

**Issue by Xe** [matrix-org/matrix-appservice-irc#12]
`2016-01-17 03:17:10 ERROR:client-connection XS--qKKCJKOmKjcpcjvHdO@scootaloo.ponychat.net: {"command":"ERROR","rawCommand":"ERROR","commandType":"normal","args":["Closing Link: ns501493.ip-142-4-215.net (Invalid username [-qkkcjkomk])"]}`

**Comment by Kegsay** [comment]
That's awkward. Thanks @Xe for spotting this.

**Comment by Kegsay** [comment]
Filed as https://matrix.org/jira/browse/BOTS-159 - Closing this one so we keep all issues for the IRC AS in one place.

**Comment by Kegsay** [comment]
Reopening as we now track them all in Github!

**Comment by Kegsay** [comment]
The problem here is:
```
2016-01-17 03:17:10 ERROR:client-connection XS--qKKCJKOmKjcpcjvHdO@scootaloo.ponychat.net: {"command":"ERROR","rawCommand":"ERROR","commandType":"normal","args":["Closing Link: ns501493.ip-142-4-215.net (Invalid username [-qkkcjkomk])"]}
```

Basically the bridge doesn't sanitize the `-` out. Whilst `-` *is a valid character*, it is NOT a valid **first** character. We don't currently handle that.

**Comment by Kegsay** [comment]
https://matrix.org/jira/browse/BOTS-161

**Comment by Kegsay** [comment]
This has reared its ugly head again because the nick template was changed from `M-Nick` to `Nick[m]`. Guest users have a full numeric nick, and `12345[m]` is not a valid IRC nick.
