### ISSUE TITLE
#freenode_#xmonad:matrix.org only sends messages one way

### ISSUE THREAD

**Issue by liskin** [matrix-org/matrix-appservice-irc#1202]
**Describe the bug**
When I join #freenode_#xmonad:matrix.org I can see messages from IRC users but messages I send don't go through to freenode. The IRC channel mode is `+cnt`, which is:

```
12:47:26 freenode -- cmode :     +c     - No color.  All color codes in messages are stripped.
12:47:26 freenode -- cmode :     +n     - No external messages.  Only channel members may talk in the channel.
12:47:26 freenode -- cmode :     +t     - Ops Topic.  Only opped (+o) users may set the topic.
```

so that should be fine.

I tried joining a test channel (#freenode_##testicek:matrix.org), which gets mode `+ns` and that one works fine.

**To Reproduce**
1. register new account on matrix.org through https://app.element.io/
2. join #freenode_#xmonad:matrix.org
3. join #xmonad at freenode through an IRC client
4. send a message through Matrix
5. look at the IRC client, it's not there
6. send a message through IRC
6. look at Element, the message is there

**Expected behavior**
I expect messages to go both ways.

**Screenshots**
![2020-12-08-140650_769x233_scrot](https://user-images.githubusercontent.com/300342/101494066-292a8800-3967-11eb-941c-891309854c41.png)
![2020-12-08-140738_624x60_scrot](https://user-images.githubusercontent.com/300342/101494073-2cbe0f00-3967-11eb-89ff-95d442ce65da.png)

**Desktop (please complete the following information):**
 - OS: Debian Testing
 - Browser: Chrome 87

**Additional context**
Probably irrelevant, but as I have no idea how Matrix works, I'll mention it nonetheless: there also was another problem with the native #xmonad:matrix.org room seeming invite-only for me and another hacker news user while the admin saw it as not: https://news.ycombinator.com/item?id=25340848

**Comment by Half-Shot** [comment]
```
Dec  8 11:48:16 lethe freenodeirc[16275]: 2020-12-08 11:48:16 INFO:req [9niwpihsz4s00] [[M->I]] onMessage: m.room.message usr=@liskin:matrix.org rm=!kTSIlWRwtPWDMCksAw:matrix.org id=$1607428096370819rloCm:matrix.org
Dec  8 11:48:16 lethe freenodeirc[16275]: 2020-12-08 11:48:16 INFO:req [9niwpihsz4s00] [[M->I]] Relaying message in #xmonad on chat.freenode.net
Dec  8 11:48:16 lethe freenodeirc[16275]: 2020-12-08 11:48:16 INFO:IrcBridge [9niwpihsz4s00] [M->I] SUCCESS  (4ms)
```

seems to imply it should work :/

**Comment by Half-Shot** [comment]
The channel silences (but doesn't ban) unregistered users which unfortunately manifests as silently dropped messages, as the IRCd doesn't give you feedback. Going to close this as there is nothing we can do :(

**Comment by liskin** [comment]
Exactly. Turns out freenode's ircd supports the +q channel flag as well:

```
17:49:35 freenode -- cmode :     +q     - Quiet.  Prevents a user from sending to the channel or changing
17:49:35 freenode -- cmode :              nick, based on a nick!ident@host match.
```

and #xmonad had `+q $~a`, meaning users who haven't identified to NickServ are silenced.

My rusty ircop-fu from earlier days didn't know about this, I assumed that being able to join means there's no ban, and didn't realize freenode has additional modes. I don't think there's anything the matrix bridge can do about this. `+q` is meant as a last-resort temporary protection against spammers, so it's intentional that there's no feedback.

Sorry for wasting your time and thank you for looking into this.
