### ISSUE TITLE
Private/direct message history retention

### ISSUE THREAD

**Issue by pacien** [matrix-org/matrix-appservice-irc#1207]
As a Matrix user, I expect the history of a direct message room to be destroyed when both users leave said room.
IRC users however do not have the notion of persistent rooms and cannot leave the direct message rooms created by the bridge.

1. Is the Matrix user leaving a two-party conversation involving some IRC user enough for the room to be deleted?
   Is the virtual user of the IRC participant automatically leaving the room as well?
   A ghost user haunting a room alone would probably prevent the room from being garbage-collected.
2. Is the content of direct message rooms with no participants actually deleted from the involved homeserver(s)?
   Or if it is just left unreachable, when is the deletion happening?

**Comment by Half-Shot** [comment]
We should probably part the IrcUser and delete the DM mapping from the server if the Matrix user leaves. I would leave garbage collection of the room to the server as you suggested.

**Comment by pacien** [comment]
This will be fully addressed only after https://github.com/matrix-org/matrix-appservice-irc/pull/1258#issuecomment-788231860 is implemented, so this issue should perhaps be re-opened until then.
