### ISSUE TITLE
Double bridging is hampered by username uniqueness attempts

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-appservice-irc#1209]
`@telegram_406edacted:t2bot.io failed to get a IRC connection. Kicking from room: Error: Ran out of entries: telegram40`

This leads to generic 'IRC Connection Failed' errors, effectively ruining the bridge's attempt to operate. We might need to do different detection on the usernames to give them sensible names as bridges commonly use similar prefixes for users, such as the Discord bridge using the guild ID or Telegram having huge swathes of numbered users

**Comment by ftyers** [comment]
I'm getting the same problem:
```
@appservice-irc:matrix.org ha fet fora a thinkl33t (@_discord_126751079089045504:t2bot.io). Raó: IRC connection failure
```

I got the following feedback:
> that would be a bug with the IRC bridge - it doesn't do a very good job of picking usernames for users, so it thinks it has run out (it shortens to _discord_126 or so on IRC, and so it thinks it has run out of numbers to increment)

**Comment by Evidlo** [comment]
I think this is the snippet in question from [IdentGenerator.js](https://github.com/matrix-org/matrix-appservice-irc/blob/develop/src/irc/IdentGenerator.ts#L206-L222)

``` javascript
    private async getSuffixForUsername(username: string, domain: string) {
        let suffixLength = 1;
        while (suffixLength <= Math.log10(IdentGenerator.MAX_USER_NAME_SUFFIX) + 1) {
            const prefix = username.substring(
            // myusername becomes myuserna
                0, username.length - IdentGenerator.USER_NAME_DELIMITER.length - suffixLength);
            // Look for all usernames starting with myuserna
            const countForPrefix = await this.dataStore.getCountForUsernamePrefix(domain, prefix);
            // is there myuserna_1 to myuserna_9
            if (countForPrefix < Math.pow(10, suffixLength) - 1) {
                // Take the next available suffix.
                return countForPrefix;
            }
            suffixLength++;
        }
        throw Error("Ran out of entries: " + username);
    }
```

So these lines are responsible for trimming the MXID length (

``` javascript
const prefix = username.substring(
// myusername becomes myuserna
    0, username.length - IdentGenerator.USER_NAME_DELIMITER.length - suffixLength);
```

However, the next bit checks for collisions with this trimmed name

``` javascript
// Look for all usernames starting with myuserna
const countForPrefix = await this.dataStore.getCountForUsernamePrefix(domain, prefix);
// is there myuserna_1 to myuserna_9
if (countForPrefix < Math.pow(10, suffixLength) - 1) {
    // Take the next available suffix.
    return countForPrefix;
}
```

so assuming there are already N `_discord_126` IRC users, this function should return N + 1 to be appended to the username.  This seems correct to me.

**Comment by Half-Shot** [comment]
This is a hard one, the bridge isn't really aware of the user_id so we try to match against humans. This algorithm works fine if you have 5000 `dave.+`s, but not so much when you have a bridge prefix. We are quite limited by number of characters in a username so we have to be a bit careful.

I'd be up for some code that detects a @_discord_ bridge style user and does something like dcord_12675107, probably as a config argument rather than something autodetecting if possible.

**Comment by Evidlo** [comment]
> I'd be up for some code that detects a @_discord_ bridge style user and does something like dcord_12675107, probably as a config argument rather than something autodetecting if possible.

Could we possibly just use the user's display name and derive their nick from that?  It is a better experience on the IRC side than a bunch of _discord_xxx users flooding the channel, and it means you are much less likely to have thousands of users with the same prefix.

**Comment by Evidlo** [comment]
Also I threw together a little example in Python of a nick choosing algorithm that tries to use as many characters from the original display name as possible and doesn't have a hard upper limit on the length of the suffix:

``` python
#!/usr/bin/env python

max_nick_len = 11

# new Matrix users to process
mx_display_names = [
    'rms',
    'evidlo',
    'a_quite_long_discord_display_name',
]

existing_irc_nicks = [
    'evidlo',
    'evidlo0', 'evidlo1', 'evidlo2', 'evidlo3', 'evidlo4', 'evidlo5',
    'evidlo6', 'evidlo7', 'evidlo8', 'evidlo9',
    'a_quite_lon',
    'a_quite_lo0', 'a_quite_lo1', 'a_quite_lo2', 'a_quite_lo3',
    'a_quite_lo4', 'a_quite_lo5', 'a_quite_lo6', 'a_quite_lo7',
    'a_quite_lo8', 'a_quite_lo9',
]

# slightly modified version of default sorting function which lowers priority of numbers
def my_sort(word):
    alphabet = 'abcdefghijklmnopqrstuvwxyz0123456789'
    val = []
    for c in word:
        if c in alphabet:
            val.append(alphabet.index(c))
        else:
            # handle non-alphanumeric characters
            val.append(ord(c))

    return val

for mx_display_name in mx_display_names:
    proposed_irc_nick = mx_display_name[:max_nick_len]

    print(mx_display_name)
    print('  -->', proposed_irc_nick)

    n = 0
    # check for nick collisions with existing users
    # we can find unoccupied nick in a single loop with alternative sorting
    for existing_irc_nick in sorted(existing_irc_nicks, key=my_sort):
        if proposed_irc_nick == existing_irc_nick:
            # use as many chars from original display name as possible
            proposed_irc_nick = mx_display_name[:max_nick_len - len(str(n))] + str(n)
            n += 1

            print('  -->', proposed_irc_nick)

    existing_irc_nicks.append(proposed_irc_nick)
```

```
>>> %run irc_name.py
rms
  --> rms
evidlo
  --> evidlo
  --> evidlo0
  --> evidlo1
  --> evidlo2
  --> evidlo3
  --> evidlo4
  --> evidlo5
  --> evidlo6
  --> evidlo7
  --> evidlo8
  --> evidlo9
  --> evidlo10
a_quite_long_discord_display_name
  --> a_quite_lon
  --> a_quite_lo0
  --> a_quite_lo1
  --> a_quite_lo2
  --> a_quite_lo3
  --> a_quite_lo4
  --> a_quite_lo5
  --> a_quite_lo6
  --> a_quite_lo7
  --> a_quite_lo8
  --> a_quite_lo9
  --> a_quite_l10
```
