### ISSUE TITLE
when applying the mautrix-whatsapp registration.yaml matrix-synapse failures to start

### ISSUE THREAD

**Issue by schluden** [matrix-org/matrix-appservice-irc#1221]
this is my homeserver.yaml
![image](https://user-images.githubusercontent.com/48884321/105025487-aad50180-5a4d-11eb-9417-39ac29e8b1fe.png)

this is my registration.yaml
![image](https://user-images.githubusercontent.com/48884321/105025643-e8d22580-5a4d-11eb-8189-1fab52b34d79.png)

what did I do wrong? I try to solve this for 4 hours. No effect.

this is going to my journalctl -xe
![image](https://user-images.githubusercontent.com/48884321/105025990-5716e800-5a4e-11eb-89c1-1753969820c2.png)

there is no error and no failure, when I delete the entry for the registration.yaml

**Comment by schluden** [comment]
The Output of **/var/log/matrix-synapse/homeserver.log** is the following:

`PermissionError: [Errno 13] Permission denied: '/etc/mautrix-whatsapp/registration.yaml'`

**Comment by Half-Shot** [comment]
This looks like the wrong repo, perhaps you meant https://github.com/tulir/mautrix-whatsapp/
