### ISSUE TITLE
Unexplainable `@appservice-irc:matrix.org kicked $USER. Reason: Idle for 30+ days` message

### ISSUE THREAD

**Issue by tobhe** [matrix-org/matrix-appservice-irc#1223]
It looks like the inactive user cleanup is broken. We got the following message today:
```
@appservice-irc:matrix.org kicked $USER. Reason: Idle for 30+ days
```
However, the stated reason does not make any sense since the room isn't even 30 days old. Moreover the Matrix <-> IRC bridge was activated ~2 days ago, which makes me wonder how the user could have been idle for 30+ days.

The room handle is `#openiked:matrix.org` if that helps.

**Comment by Half-Shot** [comment]
The kick is performed on a per-user connection basis, i.e. the user hasn't performed any activities on the IRC connection for 30 days regardless of which rooms they are part of

*however*

if they joined the room within 30 days then that should have counted as activity. Could you give me their userId of the user either here or in a PM (@Half-Shot:half-shot.uk) so that I may investigate.

**Comment by Half-Shot** [comment]
I looked into this, but couldn't find any examples of the bridge processing this users' messages. I'm doubtful that the bridge was in the room at the time the user joined or said their message before they were kicked.

**Comment by tobhe** [comment]
> I'm doubtful that the bridge was in the room at the time the user joined

Plausible, I think i might have started the bridge after the user joined.
Would this mean the bridge bot did not see (and thus count) the join event and kicked the user because of a previous interaction in another room that was too far in the past?

**Comment by Half-Shot** [comment]
I think so, I think this was really bad luck in that:

- The user hadn't interacted in a room with the bot in the last 30 days prior to joining
- The user hadn't spoken in the new room before the kick system ran

I don't think are any action items here other than to ensure that we treat read receipts and typing notifications as activity, which is being worked on.
