### ISSUE TITLE
Permanent IRC desync on Freenode

### ISSUE THREAD

**Issue by gcp** [matrix-org/matrix-appservice-irc#1241]
I extensively use the Freenode IRC bridge for work and private conservations. Connectivity has always been spotty, but invite-only channels are a huge pain as they don't automatically reconnect if the bridge goes down (which seems to happens every few days). As of 3-4 days, I'm dealing with a sort of permanent desync that renders the IRC bridge unusable:

1) To join this invite-only channel, I message Chanserv invite #channel, then tell "Freenode IRC Bridge status" !join channel,
2) As of 3-4 days, this no longer works, and Chanserv tell me "Channel #channel is not registered."
3) Freenode IRC Bridge tells me, after trying to join "Could not join #channel on 'chat.freenode.net': err_inviteonlychan" (Gee, but Chanserv just claimed it isn't registered!)
4) On another Element session on another PC, I'm shown as being inside the channel, but trying to send any message errors out with: User @gcp:mozilla.org not in room !blablabla:matrix.org (<FrozenEventV3 event_id='$ieA1KjKFoMUPNo8TE0TcHs1deBmj79a_EuFikVNlUg0', type='m.room.member', state_key='@gcp:mozilla.org'>)

**Comment by gcp** [comment]
I verified with a real IRC client that executing the command on the server successfully generates the invite, as it was doing until 4-5 days ago.

The error is what I'd get in a real IRC client if I misspelled the name, but I'm not.

**Comment by gcp** [comment]
I managed to get this working by copy/pasting an old ```invite``` that had worked. If I retype the exact same, I get the error above.

I copy pasted both strings into a hex editor, and they're byte for byte identical.

I have no idea what's going on here.

**Comment by Half-Shot** [comment]
Hmm, looking into this. I'll investigate your invite issue. The 4th issue you mentioned feels like a Synapse side issue so I'll put in a post over there.

**Comment by Half-Shot** [comment]
@gcp is this still an issue for you, I can see from the logs that you are managing to get in?

**Comment by gcp** [comment]
1-3 have resolved now, though I didn't manage to figure out what was being copy/pasted that broke things.
