### ISSUE TITLE
Redact access tokens in log messages

### ISSUE THREAD

**Issue by piegamesde** [matrix-org/matrix-appservice-irc#1246]
**Is your feature request related to a problem? Please describe.**

When looking at the Synapse logs, I read something like:

    https://somedomain.tld/transactions/1?access_token=<redacted>

But the same issue looks like this in the Appservice logs:

    https://127.0.0.1:8009/transactions/1?access_token=<not redacted>

**Describe the solution you'd like**
Please redact all tokens. They not only are noise in the logs most of the time, but they may also lead to security issues.

**Comment by Half-Shot** [comment]
Can you give some context around the log line, I'm afraid I cannot repo and it's not clear which message this might be being leaked on.

**Comment by piegamesde** [comment]
I've had a look at this again, and it seems like the logs were coming from my reverse proxy and the appservice had nothing to do with that. Sorry for the noise!
