### ISSUE TITLE
Can't join any bridged channels

### ISSUE THREAD

**Issue by soccermitchy** [matrix-org/matrix-appservice-irc#1247]
**Describe the bug**
I get "Failed to join room - there was an error joining the room" with no errors in my homeserver logs when attempting to join a bridged channel (ie. #freenode_#kicad:matrix.org). Someone in #irc:matrix.org took a look and made sure it wasn't an issue of me having +q or +b, and I don't have any +qb modes that are applied to me. ([link to convo here](https://matrix.to/#/!BAXLHOFjvDKUeLafmO:matrix.org/$BSEmUtzbh9qlbw0oKrWfR3Nwv1Uk398mQxSLnoYIMTs?via=matrix.org&via=tchncs.de&via=nofla.me))

**To Reproduce**
1. Try to join #freenode_#kicad.matrix.org
2. Wait for about a minute
3. See an error message pop up

**Expected behavior**
I should be able to join the channel without an error.

**Screenshots**
Error when joining room:
![image](https://user-images.githubusercontent.com/443155/108673325-78398100-74b1-11eb-9476-641b9debb182.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Element desktop client
 - Version: Element v1.7.21

**Additional context**
I'm also seeing the issue in #freenode_#python:matrix.org

**Comment by Half-Shot** [comment]
This is likely to be one of the issues in https://github.com/matrix-org/synapse/labels/z-join%20fail. The homeserver handles the joining of rooms rather than the IRC bridge so it's not something we can really solve. I'd

**Comment by soccermitchy** [comment]
Not sure why I never got a notification for this, but how would I figure
out which one there is applicable to me? I didn't see anything related in
my homeserver logs.
