### ISSUE TITLE
Some IRC users are not bridged

### ISSUE THREAD

**Issue by piegamesde** [matrix-org/matrix-appservice-irc#1250]
**Describe the bug**
For some reason, not all users in an IRC room are bridged to the Matrix side when joining a channel. This results in them "joining" the Matrix room the first time they speak which is confusing.

**To Reproduce**
I don't have any explicit reproduction steps. Joining small IRC rooms makes the problem more obvious though. I mainly noticed this on freshly joined IRC rooms.

I have enabled all options on `membershipLists` in the configuration.

**Expected behavior**
All users that are on the IRC side are on the Matrix side as well.

**Additional context**
This is is really similar to #371, but in the opposite bridging direction.

**Comment by Half-Shot** [comment]
Logs would be useful here I think, if you've enabled the membership options then I'd expect it to work. Be sure to enable debug logging.

**Comment by Half-Shot** [comment]
The user is running the bridge with the botEnabled config, which has subtly different logic, see the linked PR.
