### ISSUE TITLE
Docker image overrides config port

### ISSUE THREAD

**Issue by abdulocracy** [matrix-org/matrix-appservice-irc#1272]
**Describe the bug**
The Docker image overrides the configured binding port, so I had issues when upgrading to the latest Docker image (0.25.0), as the port was changed to 9999. My config was still on 9995, but the bridge wasn't using it, therefore the homeserver couldn't reach the bridge, and therefore I had major issues that went unnoticed for a while.

Once I fixed it by adjusting the registration file to use port 9999, all the messages I had sent since last Friday were spammed into channels.

**To Reproduce**
1. Use Docker image
2. Configure port other than the default 9999 in the config file
3. Watch as it doesn't change

**Expected behavior**
It should change based on the configured port

**Comment by Half-Shot** [comment]
We did highlight the port change in the changelog, but I suspect we could have made it more obvious that this would break configuration. However, the bridge *does* warn in the logs if there is a connectivity issue so I would caution to check your logs after upgrading to make sure that things are working after upgrade (especially as we are pre-1.0).
