### ISSUE TITLE
Ability to restrict bridge users

### ISSUE THREAD

**Issue by expipiplus1** [matrix-org/matrix-appservice-irc#1287]
**Is your feature request related to a problem? Please describe.**

I'd like to set up a bridge to an IRC network, however I'd like not for the network to be accessible to any matrix user.

**Describe the solution you'd like**

Settings in the configuration to restrict who the appservice bot will interact with, and who is able to join `#irc_.*` channels.

**Describe alternatives you've considered**

This could probably be done at the home-server level, but I worry that it's easy to underspecify the restrictions. Having the necessary settings documented somewhere here would help!

**Comment by expipiplus1** [comment]
I think that some of this can be done with the dynamicChannels.federate/joinrule setting, however this only affects the dynamic channels, and not mapped channels or private messages.

**Comment by Half-Shot** [comment]
You could also use the https://github.com/matrix-org/matrix-appservice-irc/blob/365139e9f1810d54f98b42c8bd164a3c4d1f487d/config.sample.yaml#L220-L222 in combination with the federation option which will kick users who join matching a regex

**Comment by expipiplus1** [comment]
yeah, that's a good option. Feel free to close if there's nothing more on your end :)
