### ISSUE TITLE
Send non-connection metadata messages when starting up

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/matrix-appservice-irc#129]
We currently filter ALL metadata messages I->M when the bridge is "starting up". This was done to avoid spamming on restarts with connection notices. However, some metadata messages are important to pass along, e.g. `err_badchannelkey` so people know that they need to re-issue the pass. We should not be filtering out those kinds of metadata messages.

**Comment by lukebarnard1** [comment]
I'm not sure where the filtering is done, as far as can see, ```err_badchannelkey``` is handled by ```BridgedClient.prototype._joinChannel``` and simply rejects the promise to join a channel. 

So we could send a message to the admin room when the key is bad, asking the user to join manually by sending "!join server key" in the admin room.

**Comment by Kegsay** [comment]
Filtering is done here - https://github.com/matrix-org/matrix-appservice-irc/blob/master/lib/bridge/IrcHandler.js#L434

**Comment by lukebarnard1** [comment]
The thing is, that line doesn't get run when I force ```err_badchankey```. The error only occurs when a client joins, so the error handling is done (as above) in ```BridgedClient.prototype._joinChannel```.

**Comment by Kegsay** [comment]
Is https://github.com/matrix-org/matrix-appservice-irc/blob/master/lib/irc/BridgedClient.js#L153 really not being called?

**Comment by fuzzy76** [comment]
Come to think of it, I _do_ get notices about missing key from my bot when reconnecting. But that is on my private bridge (I don't use the freenode bridge anymore), so I thought that was the reason.

**Comment by lukebarnard1** [comment]
What about the fact the error listener at https://github.com/matrix-org/matrix-appservice-irc/blob/master/lib/irc/BridgedClient.js#L153 ignores errors without ```err.command``` whatever that is...

**Comment by Kegsay** [comment]
https://github.com/matrix-org/node-irc/blob/master/lib/codes.js#L512 is where that is specced, which is parsed [here](https://github.com/matrix-org/node-irc/blob/master/lib/parse_message.js#L46), and emitted [here](https://github.com/matrix-org/node-irc/blob/master/lib/irc.js#L704). The command type is `error` so it will be emitted as an `'error'` event, and it does have a `.command` value.

**Comment by lukebarnard1** [comment]
On further investigation, it looks like the bot (when enabled) is failing to join the channel on startup, which prevents the channel from being tracked. Bot metadata is always suppressed .
