### ISSUE TITLE
Add !unbridge admin command

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-appservice-irc#1297]
To allow bridge admins to unbridge rooms from their admin rooms in a similar vein to #1211 

As an extra feature, it would be nice for people with permission (but not bridge admin rights) to unbridge channels from plumbed rooms.

**Comment by donpdonp** [comment]
yes im trying to unbridge a channel right now. is there an existing, manual way to do it? like editing a db file for example.

**Comment by Half-Shot** [comment]
Yeah, you can drop the entry from the postgresql database and restart.
