### ISSUE TITLE
possible bug: IRC is bridged to matrix but not vice-versa.

### ISSUE THREAD

**Issue by les-citrons** [matrix-org/matrix-appservice-irc#1314]
IRC users appear in the matrix channel and their messages are bridged, but matrix users do not connect to the IRC channel and their messages are not bridged.

**Comment by les-citrons** [comment]
I figured out that this was because it was seemingly ignoring my hosts file and trying to connect to the IRC server via the public IP, which does not work in this context.

**Comment by les-citrons** [comment]
no, actually. the users are now joining, but the messages from matrix are not being sent to IRC.

**Comment by ottersarecool** [comment]
I have exactly the same problem, I don't know why it is happening or what could cause this.

I am running the latest ircbridge version (master branch) and synapse 1.33.2

irc -> matrix works
matrix -> irc nothing

**Comment by Half-Shot** [comment]
Does your log file contain "Homeserver cannot reach the bridge.". The bridge should check the matrix -> IRC link on startup.

**Comment by les-citrons** [comment]
ah, yes. it does contain that. I do not understand why. I configured the bridge to run on port 1113. 
in the appservice yaml, I have 
`url: '127.0.0.1:1113'`

**Comment by Half-Shot** [comment]
Hmm, it might want `http://127.0.0.1:1113`? You also need to make sure Synapse has this same value too.

**Comment by les-citrons** [comment]
ah, this appears to have fixed it. thanks!
