### ISSUE TITLE
Can't store username that contains underscore

### ISSUE THREAD

**Issue by loganrosen** [matrix-org/matrix-appservice-irc#1359]
**Describe the bug**
I tried to store my username on Libera Chat (Logan_) for SASL authentication using `!username Logan_`, but I got the message that it contains invalid characters not supported by IRC:
```
!username Logan_

Username contained invalid characters not supported by IRC.
```

This message is definitely incorrect because my username is registered with Libera Chat with an underscore. It looks like [this is because `_` is used as a delimiter by the bridge](https://github.com/matrix-org/matrix-appservice-irc/blob/develop/src/irc/IdentGenerator.ts#L226). Does this mean I can't authenticate my Libera username using Matrix?

**To Reproduce**
1. Open a DM with the bridge user
2. Say `!username` and then a username containing an underscore
3. See error

**Expected behavior**
I expected to be able to store my IRC username with Matrix and automatically authenticate using SASL.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Firefox
 - Version 90.0a1

**Comment by vberger** [comment]
It's maybe not related with the underscore, because I get the same error message with `!username Levans` (which is registered by me).

**Comment by tim-seoss** [comment]
Upper case characters are (incorrectly) rejected apparently.

**Comment by deepbluev7** [comment]
I have the same issue with "Nico[m]", presumably also because of the upper case character.

**Comment by pwr22** [comment]
I hit both of these cases with `Peter_R` :laughing:

**Comment by jonasbb** [comment]
I have the same problem with `|`. I have no problem setting my nick to `saarsec|jbushart` using `!nick`, but `!username` fails with "Username contained invalid characters not supported by IRC.".

**Comment by 4nd3r** [comment]
not all characters are equal. another example: #498

**Comment by Mikaela** [comment]
Another incorrectly invalid character seems to be `@`. It's needed for specifying device ID for Ergo IRCd and possibly also ZNC.

* https://github.com/ergochat/ergo/blob/v2.7.0/docs/USERGUIDE.md#history (point 3. 1 & 2, point 3 is #1410.

**Comment by emersonveenstra** [comment]
If you're trying to use !username for SASL, a workaround for Libera (and other networks with a standard services setup) is you can group a nick that satisfies the requirements of the bridge (so basically all lowercase letters) and use that as !username

**Comment by llucax** [comment]
That seems to work for me, not ideal but at least is a workaround. Thanks!

**Comment by progval** [comment]
I am told is is also an issue with `^`. There is no spec for usernames, but any valid nick is usually a valid username; and here are the restrictions for nicks: https://modern.ircdocs.horse/#clients
