### ISSUE TITLE
support /who

### ISSUE THREAD

**Issue by fuzzy76** [matrix-org/matrix-appservice-irc#136]
As there is no current way (that I can find) to see which users (or if any) are connected on the IRC side, support for the /who command is much needed.

**Comment by Kegsay** [comment]
There is a `!whois` command already.

**Comment by fuzzy76** [comment]
No, /who and /whois are to completely different commands. /who lists all users in a channel. /whois only shows information about a specific user.

**Comment by Kegsay** [comment]
Oh, sorry I must've misread that. We don't have any plans to add `!who`, we should be mirror IRC -> Matrix membership lists instead, but we can't until Synapse persists state events more efficiently. When that happens, we'll enable this on the matrix.org bridges.

**Comment by fuzzy76** [comment]
https://github.com/matrix-org/matrix-appservice-irc/commit/719587154fbf79fa5d8e629994e7c240b826a768 Also looks promising for sending the request "manually", but I can't get it to work.

**Comment by fuzzy76** [comment]
Is this actually coming...?
