### ISSUE TITLE
matrix-appservice-irc strips ZWSP characters leading extraneous pings

### ISSUE THREAD

**Issue by Mikaela** [matrix-org/matrix-appservice-irc#1364]
**Describe the bug**

Recent events have increased the popularity of relaybots and as some people tend to be on multiple sides of them, there is a defacto behaviour of adding a ZWSP as a second character of the sender nickname. For some reason `matrix-appservice-irc` removes that and causes me to get pinged whenever I type in some rooms, while that doesn't happen with IRC clients.

**To Reproduce**

1. Open https://testnet.ergo.chat/kiwi/#limnoria-bots with a nickname-that-pings-you-at-Matrix and `/join #limnoria-bots:libera.chat` on Matrix.
2. Say something on the first link.
3. You get pinged on Matrix regardless of there being a ZWSP.

Alternatively you can use https://ergo.chat/kiwi/#ergo / https://ergo.chat/gamja/#ergo and join `#ergo:libera.chat`, but please don't as that is an on-topic support channel while the first one is a bot testing channel that hopefully doesn't mind a bit of other testing too.

**Expected behavior**

I expect matrix-appservice-irc to not remove ZWSP characters and thus not get pinged when there is a ZWSP breaking my nicknames.

**Screenshots**

* ![IRC](https://user-images.githubusercontent.com/831184/120439007-b258cf80-c38a-11eb-8f28-2733d260e2a0.png)
  * Note how here only the last message is considered as a ping by WeeChat.
* ![Element](https://user-images.githubusercontent.com/831184/120438916-96552e00-c38a-11eb-9f53-ac5a28c5a4c8.png)
   * Messages 1 & 3 don't contain `Mikaela` they contain `M<ZWSP>ikaela` while we cannot see the ZWSP.

**Desktop (please complete the following information):**
 - OS: Fedora 34
 - Browser: Firefox
 - Version: 88.0.1

**Additional context**

* [Zero-width space on Wikipedia](https://en.wikipedia.org/wiki/Zero-width_space)

**Comment by Half-Shot** [comment]
Are you sure that the bridge is removing it and it's not your client doing it? Can you provide an example eventID?

**Comment by Mikaela** [comment]
> Are you sure that the bridge is removing it and it's not your client doing it?

Yes. I see this behaviour only in rooms using matrix-appservice-irc and not in rooms using [matterbridge with RemoteNickFormat="{NOPINGNICK}"](https://github.com/42wim/matterbridge/wiki/Settings#remotenickformat).

> Can you provide an example roomID/eventID?

The two that I mentioned, Limnoria-bots & Ergo:

* `!rDmjxKuJlBiaqVpXJV:libera.chat` / `$K1tIrDKguTIj6jGF73EC11Y-JuI6YyQ1JD-PyxY_iHA`
* `!lrCDrInJjYWsVZIWFa:libera.chat` / `$_fUOIgNB3wFUxbPCQT1i3ViQwVezaDYcEjN5atp-xjs`
