### ISSUE TITLE
Invalid Character Issue with new Libera.Chat bridge

### ISSUE THREAD

**Issue by Rspigler** [matrix-org/matrix-appservice-irc#1391]
**Describe the bug**
I was trying to register my old Freenode nick, which had an underscore `_` in the middle.  Setting `!nick` and verifying, as well as confirming the email with `verify register` in `@NickServ:libera.chat` worked with no errors.

However, trying to set up automatic identification with `@appservice:libera.chat` using `!username` errors out says that:

> Username contained invalid characters not supported by IRC.

Changing my nick to remove the underscore works.

**Expected behavior**
If I can set the Nick and register successfully, the application should be able to store the username. I also believe an underscore is a valid IRC character?

**Desktop (please complete the following information):**
 - OS: Qubes 4.0; Debian 10 standalone VM
 - Version: Element 1.7.30

**Comment by loganrosen** [comment]
This is a duplicate of #1359.

**Comment by Rspigler** [comment]
My apologies, closing.
