### ISSUE TITLE
Nicknames with slashes appear as "undefined" (RELAYMSG)

### ISSUE THREAD

**Issue by Mikaela** [matrix-org/matrix-appservice-irc#1411]
**Describe the bug**

RELAYMSG or nicknames with slashes appear as "undefined" (`@irc_undefined:liberta.casa`) on Matrix.

**To Reproduce**

1. Join a room where you can see RELAYMSG
2. See a RELAYMSG'd user or if you are op (or oper with `relaymsg` privilege) on IRC, send one by yourself through `/quote RELAYMSG #channel fake/relaymsg :message here`

**Expected behavior**

"message here" appears to be sent by nickname "fake/relaymsg", but instead appears from user "undefined"

**Screenshots**

IRC:

```
[17:45:09] <fake/relaymsg> This is a message from fake/relaymsg
[17:45:10] <cranberry> lol
[17:45:13] <M1kaela/tg> This is a message from M1kaela/tg while we aren't actually relayed there
```

![image](https://user-images.githubusercontent.com/831184/125166964-c1f7df00-e1a6-11eb-9f5c-f02998a1d615.png)

**Desktop (please complete the following information):**
 - OS: Fedora 34
 - Browser Edge
 - Version: Versio 91.0.864.67 (Virallinen koontiversio) (64-bittinen)

**Additional context**

* Client used: https://develop.element.io/
* BridgeVersion: 0.27.0
* IRCd: ergo-2.7.0-rc1-36703580fc460ec2 irc.liberta.casa
* Possibly related: https://github.com/matrix-org/matrix-appservice-irc/issues/500

**Comment by Mikaela** [comment]
Also possibly related: https://github.com/matrix-org/matrix-appservice-irc/issues/712

**Comment by Mikaela** [comment]
I found out that `/me` messages from the unknown user also become messed up.

![image](https://user-images.githubusercontent.com/831184/126066844-23cad955-a39b-4840-8f7d-3a91fa9f617f.png)


```json
{
  "content": {
    "body": "\u0001ACTION nominates matrix-appservice-irc the biggest headache since Charybdis#255\u0001",
    "msgtype": "m.text"
  },
  "origin_server_ts": 1626610714905,
  "sender": "@irc_undefined:liberta.casa",
  "type": "m.room.message",
  "unsigned": {
    "age": 5619
  },
  "event_id": "$FCKonM2YAMuLG3vVgxB6zwpH0zkxMkZKPW3XTpRWGuY",
  "room_id": "!BOgGhzZDPlkGSgoSdO:liberta.casa"
}
```

I don't know if it's a separate issue or just strongly related to this one.

**Comment by Mikaela** [comment]
@Half-Shot could you acknowledge this issue too and give it label IRCv3?

Ref: https://github.com/ircv3/ircv3-specifications/pull/417

RELAYMSG is also currently the most :+1:'d issue on Solanum which is what Libera.Chat uses, https://github.com/solanum-ircd/solanum/issues/159.

**Comment by Half-Shot** [comment]
We've not actively prioritised IRCv3 features in favour of trying to support existing features / performance improvements, and would probably wish for the community to look at implementing those. Sorry, the resources just aren't enough where we can look at these right now.

**Comment by emersonveenstra** [comment]
It's not actually an IRCv3 problem, it's because of https://github.com/matrix-org/node-irc/pull/81.

However, dendrite actually enforces the allowed mxid characters so it will be unhappy (#1432), but maybe that's a problem for later, since dendrite is already unhappy with a lot of things the bridge does.

**Comment by poVoq** [comment]
Since this is still not fixed upstream... am I correct that it might be possible to work-around this issue by using a different RELAYMSG seperator than "/"? Has anyone tried some working ones that are unlikely to be used by regular nicknames?

Edit: Confirmed, if I use a IRC nickname legal seperator like | it starts working. Not ideal of course, but a work-around.
