### ISSUE TITLE
Bridge crash on Assertion `val->IsArrayBufferView()' failed

### ISSUE THREAD

**Issue by silkeh** [matrix-org/matrix-appservice-irc#1444]
**Describe the bug**
The bridge crashes with the following error:

```
Aug 02 20:07:26 matrix-irc matrix-appservice-irc[31051]: node[31051]: ../src/node_buffer.cc:220:char* node::Buffer::Data(v8::Local<v8::Value>): Assertion `val->IsArrayBufferView()' failed.
Aug 02 20:07:26 matrix-irc matrix-appservice-irc[31051]:  1: 0xa1a640 node::Abort() [node]
Aug 02 20:07:26 matrix-irc matrix-appservice-irc[31051]:  2: 0xa1a6be  [node]
Aug 02 20:07:26 matrix-irc matrix-appservice-irc[31051]:  3: 0x9f94a2  [node]
Aug 02 20:07:26 matrix-irc matrix-appservice-irc[31051]:  4: 0x9eeede napi_get_buffer_info [node]
Aug 02 20:07:26 matrix-irc matrix-appservice-irc[31051]:  5: 0x7f261c00d9d2 IsValidUTF8 [/usr/local/share/.config/yarn/global/node_modules/utf-8-validate/prebuilds/linux-x64/node.napi.node]
Aug 02 20:07:26 matrix-irc matrix-appservice-irc[31051]:  6: 0x9d1e05  [node]
Aug 02 20:07:26 matrix-irc matrix-appservice-irc[31051]:  7: 0xc06599  [node]
Aug 02 20:07:26 matrix-irc matrix-appservice-irc[31051]:  8: 0xc08387 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
Aug 02 20:07:26 matrix-irc matrix-appservice-irc[31051]:  9: 0x140dd19  [node]
Aug 02 20:07:26 matrix-irc systemd[1]: matrix-appservice-irc@ircnet.service: Main process exited, code=killed, status=6/ABRT
Aug 02 20:07:26 matrix-irc systemd[1]: matrix-appservice-irc@ircnet.service: Failed with result 'signal'.
```

**To Reproduce**
1. Start bridge
2. Wait a bit

**Expected behavior**
Bridge does not crash

**Screenshots**
n/a

**Server (please complete the following information):**
 - OS: Debian Buster
 - Bridge version: 0.29.0
 - NodeJS version: v12.22.4

**Additional context**
This bridge is used by Finnish people, who use ungodly amounts of Latin-9

**Comment by Half-Shot** [comment]
> This bridge is used by Finnish people, who use ungodly amounts of Latin-9

Ahhhhh.

Thanks, I think this looks like a bug in `utf-8-validate`

**Comment by Half-Shot** [comment]
Failing around https://github.com/websockets/utf-8-validate/blob/739642646cddd26363b8a72d96ebd98fe29fead5/src/validation.c#L17-L18 i presume.

**Comment by Half-Shot** [comment]
@silkeh This feels like messages on IRC with some funky encoding (latin-9?) are causing us to crash, do you have some example known-broken strings the team can look at?

**Comment by silkeh** [comment]
@Half-Shot: I tried reproducing it today in a test environment to grab some logs, and I found out that just setting `encodingFallback: "ISO-8859-15"` causes this crash. The log below is from a bridge (without database) connecting to a fresh homeserver.

[debug.log](https://github.com/matrix-org/matrix-appservice-irc/files/7006383/debug.log)

**Comment by silkeh** [comment]
Can confirm this is fixed with the latest release. Thanks!
