### ISSUE TITLE
Docker image for 0.29.0 missing

### ISSUE THREAD

**Issue by hpdeifel** [matrix-org/matrix-appservice-irc#1451]
It seems the image for the final release of 0.29.0 isn't available on dockerhub. The RCs are both there, just the final release is missing:

https://hub.docker.com/r/matrixdotorg/matrix-appservice-irc/tags?page=1&ordering=last_updated&name=29

**Comment by Half-Shot** [comment]
Thanks for catching that, I'm not yet sure why the automation didn't fire.

**Comment by Half-Shot** [comment]
I've created these manually, both `release-v0.29.0` and `latest`.
