### ISSUE TITLE
multiline m.notice messages aren't pastebinned

### ISSUE THREAD

**Issue by emersonveenstra** [matrix-org/matrix-appservice-irc#1457]
**Describe the bug**
It appears m.notice messages aren't pastebinned after a few lines like normal messages.

**To Reproduce**
1. Send a m.notice message with several linebreaks

**Expected behavior**
The contents are pastebinned as usual.

**Screenshots**
From #matrix, a few minutes ago
![Screenshot_2021-08-16_21-46-36](https://user-images.githubusercontent.com/5402360/129651308-3e22c76d-31ea-45ca-897a-31149450d296.png)

**Comment by Mikaela** [comment]
Duplicate of #490.

**Comment by emersonveenstra** [comment]
oh, good catch
