### ISSUE TITLE
the idea is that the "use matrix.org?" dialog should feel no more or less invasive than a GDPR click-thru fwiw.  previews are pretty important UX though - in terms of room name, avatar, etc, otherwise it could just come up with a raw ID which is horrific.

### ISSUE THREAD

**Issue by mike22664** [matrix-org/matrix-appservice-irc#1481]
the idea is that the "use matrix.org?" dialog should feel no more or less invasive than a GDPR click-thru fwiw.  previews are pretty important UX though - in terms of room name, avatar, etc, otherwise it could just come up with a raw ID which is horrific.

_Originally posted by @ara4n in https://github.com/matrix-org/matrix.to/issues/219#issuecomment-919028354_

**Comment by Half-Shot** [comment]
I don't think this has anything to do with the IRC bridge, closing.
