### ISSUE TITLE
kick IRCbot from channels where it is not supposed to be

### ISSUE THREAD

**Issue by rubo77** [matrix-org/matrix-appservice-irc#149]
The matrixbot should be kicked from rooms, where it isnot allowed to bridge, if  `dynamicChannels` is set `enabled: false`

I had  this set to `true` before, so the bot is joined in some more rooms, than I selected manually in the `config.yaml`

Now since this is set to `false` the bot should leave the rooms not listed in the section but it doesn't, It just stays and reconnects to the rooms, where it was before I changed this option.

I would kick the bot from the matrix room, which, I think, would result in the bot being bannned from thi bridged IRC Room too. But in my case, the Bot is another admin of the Matrix room, so I cannot ban it.

**Comment by rubo77** [comment]
*bump*

This is really annoing, we cannot get rid of our bot in a room, where it os not allowed to be!

**Comment by lukebarnard1** [comment]
This has been fixed https://github.com/matrix-org/matrix-appservice-irc/pull/132, please wait for the next release :smile: or use ```develop``` branch if you want to risk it :+1:

**Comment by rubo77** [comment]
I think you're mistaken.

This issue is not about admin rooms or rooms where the boot was invited accidentally.

Please reopen

**Comment by Kegsay** [comment]
Reopening as this is a valid issue, but isn't one we're going to address in the near future.

The bridge does not currently check the database on startup for the complete list of **dynamically** bridged rooms, check to see if `dynamicChannels` is disabled, then leave those rooms (along with all its virtual users).

We aren't going to address this in the near future because:
 - This is a misconfiguration issue.
 - This is easily rectifiable via shell scripts.
 - It's unclear what should happen if you were to then re-enable dynamic channels: are those rooms still valid? Should new ones be created instead?
 - If there are a lot of virtual users in the room, the act of leaving all of the users will put intense CPU loads on Synapse.

**Comment by rubo77** [comment]
At the moment, a workaround: the channel op in the irc channel has to kick the matrix bot once.
Then the matrix bot stops reenering that room.

If the bot is not kicked, it reenters the room automatically for example after a reboot of the synclient.

 An easy solution would be to check for the bot, if either the setting is true or each room to reenter is in the list

**Comment by Kegsay** [comment]
> how could I solve this on the console with single commands? 

There is an append-only text file (typically located at `data/rooms.db`) which contains the room mappings for the bridge. You can delete all dynamic mappings by using the following:
```
# check the line count before
$ wc -l rooms.db
310 rooms.db

# Take a backup then delete lines matching "from_config":false
$ sed -i.bak '/"from_config":false/d' ./rooms.db 

# check the line count after
$ wc -l rooms.db
277 rooms.db

# check the line count of the backup
$ wc -l rooms.db.bak 
310 rooms.db.bak
```

If you then restart the bridge, the `MatrixBot` IRC user will no longer join the dynamic channels.

**This will not do anything with the Matrix-side rooms**. The matrix rooms are effectively unbridged at this point, and the Matrix users the bridge created will still be there.

**Comment by rubo77** [comment]
This found about 20 rooms, that used to be bridged but aren't any more, so it is in the right direction, but it didnt find this room:

    {"id":"!asdfasdfasdf:matrix.eclabs.de irc.eu.hackint.org #ffda-log","remote_id":"irc.eu.hackint.org #ffda-log","matrix_id":"!asdfasdfasdf:matrix.eclabs.de","remote":{"domain":"irc.eu.hackint.org","channel":"#ffda-log","type":"channel"},"matrix":{"extras":{}},"data":{"origin":"alias"},"_id":"asdfsadfsadfsaf"}

**Comment by Kegsay** [comment]
Closing this issue: see https://github.com/matrix-org/matrix-appservice-irc/issues/191 and https://github.com/matrix-org/matrix-appservice-irc/issues/192 for tracking the issues you've brought up here.
