### ISSUE TITLE
Thousands of users disconnected at the same time with "Client limit exceeded: 20000"

### ISSUE THREAD

**Issue by progval** [matrix-org/matrix-appservice-irc#1500]
Hi,

**Describe the bug**

I have noticed a few times on Libera that the bridge would disconnect many users at the same time, with "Quit: Client limit exceeded: 20000".

Yesterday, they were thousands, flooding backlogs of anyone without quit/join filtering.

**To Reproduce**

No idea

**Expected behavior**

Shed users progressively, spaced over either regular or random intervals

**Screenshots**

N/A

**Desktop (please complete the following information):**

N/A

**Smartphone (please complete the following information):**

N/A

**Additional context**

**Comment by Half-Shot** [comment]
Hiya, we hit our limit of connections with libera again last night which caused this problem. Normally, we do inactive users over a much more controlled period.

**Comment by progval** [comment]
This is not an isolated issue. It also happened twice on 2021-07-02, and once on 2021-11-12 and 2021-11-18.

**Comment by Mikaela** [comment]
How about disconnecting dead bridges that are not coming back? https://github.com/matrix-org/matrix-appservice-irc/issues/1460
