### ISSUE TITLE
define always chanop users

### ISSUE THREAD

**Issue by rubo77** [matrix-org/matrix-appservice-irc#151]
We have an IRC-room, where the Matrix bot is the only chanop now, so we would need the Matrixbot to op us as chanop too there.

There should be users definable, that are automatically opped by the Matrix bot in an IRC channel

as workaround, maybe there is a solution, that already works now?

**Comment by Half-Shot** [comment]
I believe this is a function of the ChanServ service on most irc networks. It should be able to give you op provided you've registered the channel (which I think is good practice). Failing that, your best bet is to invoke a staffer to fix it. I'm not convinced we should add the functionality for the Matrix Bot to op people who ask for it.
