### ISSUE TITLE
Cannot see messages from IRC on #debian (OFTC)

### ISSUE THREAD

**Issue by enigma9o7** [matrix-org/matrix-appservice-irc#1536]
Something odd with `#_oftc_#debian`

When joined, it shows the list of users, but the only messages shown are from other matrix users; no messages from irc users are displayed.

When checking from a real irc client, the matrix user does join the channel, and their messages are relayed to IRC.  But no messages get back to the matrix user from IRC.

It used to work right until about a week ago.

**Comment by Half-Shot** [comment]
Hiya, this is a known issue sadly due to an operational issue. See https://status.matrix.org/ for updates.

**Comment by Half-Shot** [comment]
This *should* now be fixed.
