### ISSUE TITLE
IRC Kicks appear as leaves

### ISSUE THREAD

**Issue by mweinelt** [matrix-org/matrix-appservice-irc#156]
On `0.4.0` kicks on IRC appear as leaves in Matrix.

IRC

```
:hexa-!~hexa-@freifunk/darmstadt/hexa- KICK #chaos-darmstadt fluxx :fluxx
```

Matrix

```
{
  "origin_server_ts": 1473085071262,
  "sender": "@irc_fluxx:darmstadt.ccc.de",
  "event_id": "$14730850718dwiwT:darmstadt.ccc.de",
  "unsigned": {
    "prev_content": {
      "membership": "join",
      "avatar_url": null,
      "displayname": "fluxx (IRC)"
    },
    "prev_sender": "@irc_fluxx:darmstadt.ccc.de",
    "replaces_state": "$1473016089531WnrsM:darmstadt.ccc.de",
    "age": 248
  },
  "state_key": "@irc_fluxx:darmstadt.ccc.de",
  "content": {
    "membership": "leave",
    "avatar_url": null,
    "displayname": "fluxx (IRC)"
  },
  "membership": "leave",
  "type": "m.room.member",
  "room_id": "!iBrjpoGgBjoArWOnld:darmstadt.ccc.de"
}
```

Vector

```
fluxx (IRC) left the room.
```

**Comment by Kegsay** [comment]
This is working as intended.

When an IRC user kicks another IRC user, the bridge needs to map this onto Matrix. It has 2 Matrix users and it needs 1 to kick the other. However, The room may be configured such that the Matrix user is unable to kick users at all. In order for this operation to be mirrored under all circumstances, the bridge forces the kicked user to leave the room instead, which every Matrix user *can* do.

We could tweak the bridge to attempt to kick first then fallback to leaving, so this issue isn't completely invalid, it's just not something we're going to waste time doing when there are bigger issues out there.

**Comment by erdnaxeli** [comment]
Another idea: if the bridge cannot cannot kick the user, we can do somethink like `/me was kicked by <user>` with the user being kicked, and then left.
