### ISSUE TITLE
"(IRC)" should only be part of the display, not of the message

### ISSUE THREAD

**Issue by pchampin** [matrix-org/matrix-appservice-irc#1563]
**Is your feature request related to a problem? Please describe.**
When I use auto-completion to mention an IRC user (say 'john'), my matrix client auto-completes it as 'john (IRC)'.
While I don't mind it being displayed "john (IRC)" in Matrix (it is an interesting info), I don't think that this precision should be part of the actual message sent to IRC.
- for human IRC users, it might be surprising
- for some bots, it prevents them from working (because they expect something like `<their_name>, <command>` and don't recognize `<their_name> (IRC), <command>`).

**Describe the solution you'd like**
Either use "(IRC)" only in the Matrix client, but *not* in the messages sent to IRC,
or (if it is too complex), drop the "(IRC)" mention all together (or make it configurable).

**Comment by Mikaela** [comment]
Which bridge and client are you seeing this with? It may be an issue with that particular instance as the "(IRC)" suffix was dropped back in August 2018 https://github.com/matrix-org/matrix-appservice-irc/issues/194#issuecomment-415734087 (and before that in 2016 "Riot" used to remove it automatically https://github.com/matrix-org/matrix-appservice-irc/issues/194#issuecomment-268208287).

**Comment by pchampin** [comment]
> the "(IRC)" suffix was dropped back in August 2018
Was it? Interesting :thinking: 

I am using Element Desktop for Linux:
Element version: 1.10.11
Olm version: 3.2.8

My server is matrix.org.
An example IRC channel I use is https://matrix.to/#/#_w3c_#rdf-dev:matrix.org

**Comment by tadzik** [comment]
This is indeed a misconfiguration of w3c bridge on matrix org, due to the fact that this is the IRC bridge's default behaviour. Dropping it from the example config is probably a sensible thing to default to.

**Comment by pchampin** [comment]
Is it something that I should discuss with the people at Matrix.org? The people at W3C?

**Comment by tadzik** [comment]
That's something that we, as a team maintaining matrix.org bridges, need to do – shouldn't be long now :)
