### ISSUE TITLE
IRC bridges make `/join` and `/leave` requests with a malformed body

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-appservice-irc#1583]
We see lots of this on requests to `POST /_matrix/client/r0/join/{roomId}` and `POST /_matrix/client/r0/rooms/{roomId}/leave` from the IRC bridges:

```
2022-07-26 00:01:39,758 - synapse.http.servlet - 663 - WARNING - POST-73077 - Unable to parse JSON: Expecting value: line 1 column 1 (char 0) (b'')
```

... which suggests it is making requests with a malformed (empty?) body. Currently Synapse accepts this, but it's not spec-compliant and we'll be fixing this in Synapse soon: https://github.com/matrix-org/synapse/issues/13388.

Please could you make sure to include (at least) an empty json object in the request body?

**Comment by Half-Shot** [comment]
These requests are handled by `matrix-bot-sdk`, so it's possible that library is buggy. Will take a look.

**Comment by Half-Shot** [comment]
Opened https://github.com/turt2live/matrix-bot-sdk/issues/248 to track the upstream bug

**Comment by Half-Shot** [comment]
Believe this has been fixed for a while.
