### ISSUE TITLE
Disconnect IRC puppets when their corresponding Matrix user goes offline

### ISSUE THREAD

**Issue by CST1229** [matrix-org/matrix-appservice-irc#1584]
**Is your feature request related to a problem? Please describe.**
At least one person who's in a channel I'm also in has complained that the Matrix-IRC bridge (specifically, the one on Libera Chat, which I assume is an instance of this) keeps the IRC puppets online forever, which they don't like and can be confusing, especially for people who don't know ("how and why does [insert user] stay connected for so long??").

**Describe the solution you'd like**
If possible, when a user on Matrix goes offline, the corresponding IRC puppet should also part and/or quit. This would probably come with a central bridge bot (only to maintain room history) that is required for disconnecting IRC puppets but is optional otherwise.

~~Making Matrix puppets leave when the IRC user parts/quits~~ Some way to not have all IRC users' past nicknames be permanently in the room would also be nice, but is not required.

**Describe. alternatives you've considered**
Setting the puppet's away status instead of fully leaving and rejoining (this way, no central bot would be needed and it would still be slightly clearer).

**Additional context**
none

**Comment by progval** [comment]
> Making Matrix puppets leave when the IRC user parts/quits would also be nice, but is not required.

They already do this

**Comment by CST1229** [comment]
> > Making Matrix puppets leave when the IRC user parts/quits would also be nice, but is not required.
> 
> They already do this

Okay, but I have noticed puppets who are definitely not in the channel in its corresponding room's member list list, so that might be something else.

**Comment by progval** [comment]
That is a known issue, there are a bunch of tickets about this on this bug tracker

**Comment by Half-Shot** [comment]
>Okay, but I have noticed puppets who are definitely not in the channel in its corresponding room's member list list, so that might be something else.

That can also happen if the room admin explicitly disables this feature.

**Comment by Half-Shot** [comment]
I think as @progval says, there are other issues catering to the things you mentioned but thank you for bringing it to our attention.
