### ISSUE TITLE
@appservice:libera.chat won't reply

### ISSUE THREAD

**Issue by yuuyins** [matrix-org/matrix-appservice-irc#1592]
**Describe the bug**
`@appservice:libera.chat` won't reply me `@yuu:matrix.org` (which supposedly should https://libera.chat/guides/faq#can-i-connect-with-matrix)

**To Reproduce**
1. `/msg @appservice:libera.chat !help`
2. no reply

**Expected behavior**
reply

**Screenshots**

**Desktop (please complete the following information):**
- NixOS 22.11.20220725.5a0e0d7
- Element version: 1.11.0
- Olm version: 3.2.8

**Additional context**
people suggested reporting it here https://matrix.to/#/!OGEhHVWSdvArJzumhm:matrix.org/$xubycNxO3TufEXNiLLvpN7oJAJuZpML-zQodTEaoNbw?via=matrix.org&via=libera.chat&via=wolfo.tech

**Comment by jaller94** [comment]
Mhh. the bot does reply to me.
I always forget if this DM room with the bot needs to be unencrypted or not.

**Comment by yuuyins** [comment]
@jaller94 i tested both encrypted and unencrypted. it does not reply me.

**Comment by jian-lin** [comment]
The room needs to be unencrypted for the bot to reply to you.

I used to enable encryption by default on my home server by setting `encryption_enabled_by_default_for_room_type = "invite"`. After changing that to default, I can use the bot now.

**Comment by yuuyins** [comment]
@jian-lin i'm using matrix.org homeserver. yuu:matrix.org

**Comment by yuuyins** [comment]
![oof](https://user-images.githubusercontent.com/86538850/185459776-27932bba-464c-419b-bf1e-05427a0722e0.png)

oh well
