### ISSUE TITLE
Add an explanation how to block the Matrix bot from a freenode channel to README

### ISSUE THREAD

**Issue by rubo77** [matrix-org/matrix-appservice-irc#160]
On some Channels on freenode IRC it is not allowed to use the Matrix bridge,

there should be an easy explanation in the README, how to remove all Matrix activity from specific IRC channels.

You can bann every username, and every nickname, from that particular server somehow with this command:

    *!*@gateway/shell/matrix.org/*

You have to be op on those channels, but It needs some more explanation how to use that command and where to enter it ;)

**Comment by eternaleye** [comment]
That won't work if the user has a cloak and has identified (I'm an example; feel free to whois me on Freenode)

**Comment by rubo77** [comment]
This is theonly complain I mostly get on different channels: 

"The history must only be visible for users that appear in the userlist in the IRC room"

Until this can be assured, ther has to be a way for the channel ops to ban all matrix users

**Comment by Kegsay** [comment]
Instructions on how to manage an IRC network are not the domain of this issue tracker. We cannot supply an IRC command which will be universally applicable to block bridge-created traffic across all bridges.

Closing this.
