### ISSUE TITLE
#guile:libera.chat doesn't relay messages

### ISSUE THREAD

**Issue by Kreyren** [matrix-org/matrix-appservice-irc#1613]
**To Reproduce**
1. join the room `#guile:libera.chat`
2. Try send any message and check http://logs.guix.gnu.org/guile if it was relayed to the IRC users

**Comment by Kreyren** [comment]
CC @Half-Shot @kegsay @lukebarnard1 @jaller94 annoyed people on matrix told me in diplomatic way to annoy you bcs it's not fixed for me and https://github.com/matrix-org/matrix-appservice-irc/issues/1590 https://github.com/matrix-org/matrix-appservice-irc/issues/1575 so i made a meme and used the magical `@` character

![](https://user-images.githubusercontent.com/11302521/191718067-df28f193-0db5-4cf2-bafb-16fbdb0d0929.png)

**Comment by jesopo** [comment]
```
10:24:27 [lc] -!- mode/#guile [+ntz]
10:24:30 [lc] -!- #guile q $~a helium.libera.chat 1662267401
10:24:30 [lc] -!- #guile q End of Channel Quiet List
```

I'm going to assume the bridged user was not logged in to nickserv, and thus their message wasn't relayed to the IRC channel. `+q $~a` mutes people that are not logged in to nickserv, and `+z` suppresses the warning given to a muted user trying to speak, to instead forward their attempted messages to the channel's operators.

if the bridged user couldn't send messages to the channel, the `logs.guix.gnu.org` bot wouldn't have seen the message

**Comment by Half-Shot** [comment]
Thanks @jesopo!
