### ISSUE TITLE
Quits aren't bridged to matrix

### ISSUE THREAD

**Issue by jkhsjdhjs** [matrix-org/matrix-appservice-irc#1618]
When incremental membership syncing is enabled, quits aren't synced to matrix, only parts and joins are. Enabling debug logging shows that the bridge doesn't even register quits. Since this worked fine with 1.34.0 and because the bridge isn't aware of quits I assume that there has been a regression in matrix-org-irc with the update from 1.2.1 to 1.3.0.

**Comment by sergaderg** [comment]
I've noticed name changes have also stopped syncing properly, perhaps the same issue?

**Comment by jkhsjdhjs** [comment]
This has been fixed in https://github.com/matrix-org/node-irc/pull/103
