### ISSUE TITLE
Can't join #libera using Element 

### ISSUE THREAD

**Issue by jbjoeB** [matrix-org/matrix-appservice-irc#1632]
Hello,

First time using matrix and I pretty much have the jist of it. Im connect to libera.chat and I do !join #libera using appservice and nothing happens. I can join other rooms easily I get an invite. Any ideas how to fix? #libera is a very informative channel 

Thanks

**Comment by Half-Shot** [comment]
This sounds like a slow room join rather than an IRC bridge issue. Please update if you've got more details.

**Comment by jbjoeB** [comment]
I still can't join #libera using appservice as you know in appservice you just !join #channelhere I can join all channels on libera except #libera I joined as my znc user and it worked fine. Is there a command I can do to reset my settings?
