### ISSUE TITLE
Partial outage of the Libera bridge

### ISSUE THREAD

**Issue by progval** [matrix-org/matrix-appservice-irc#1633]
Two people just reported in #libera-matrix that the appservice bot is very slow/unresponsive. At least one of them runs their own homeserver.

A message sent to #matrix-spec:matrix.org at 15:24 was sent to IRC at 15:30. Messages sent between 16:50 and 17:00 were relayed either at 17:10, 2:49 (out of order), or not at all, depending on sender.

IRC->Matrix seems to be affected too. (tested in my own channel, not #matrix-spec, ofc)

**Comment by Half-Shot** [comment]
We've given it a kick.

**Comment by progval** [comment]
Seems to work, at least on my channels and #matrix-irc

**Comment by podiki** [comment]
Also had a problem (slow/messages not coming from IRC->Matrix) but seems to be operational now, thanks.
