### ISSUE TITLE
No messages from matrix users arrive on libera

### ISSUE THREAD

**Issue by srett** [matrix-org/matrix-appservice-irc#1675]
Since yesterday (2023-03-06) between 08:38 and and 11:20 UTC, messages from all matrix users stopped arriving on libera.chat. One user's bridge user had a ping timeout after that and reconnected automatically, but that didn't fix the issues. All other bridged users stayed connected throughout. How to fix this?

**Comment by progval** [comment]
Already reported to https://github.com/matrix-org/synapse/issues/15216

**Comment by Half-Shot** [comment]
We're going to track this on the Synapse side. Thanks both for reporting :+1:
