### ISSUE TITLE
Cannot `!unlink` room from Libera

### ISSUE THREAD

**Issue by c-x-berger** [matrix-org/matrix-appservice-irc#1691]
I'm trying to unlink a Matrix room from IRC via `unlink !roomid:example.com irc.libera.chat #channelname`, but when I message `@appservice:libera.chat` to do so, I just get a cryptic error: `Failed to unlink room. Check the logs for details.` I've double checked that the ID and channel name are correct. I have PL 100 in the Matrix room.

Obviously I can't investigate Libera's logs myself, so... what should I do here?

**Comment by Half-Shot** [comment]
This was broken and fixed in https://github.com/matrix-org/matrix-appservice-irc/pull/1692, update should be out soon.
