### ISSUE TITLE
2023-03-28 outage of the Libera bridge

### ISSUE THREAD

**Issue by progval** [matrix-org/matrix-appservice-irc#1693]
(timestamps in UTC)

* Somewhere between 8:51 and 8:54, the bridge stopped relaying IRC->Matrix messages.
* From 8:56 to 9:02, puppets timed out
* At 9:06, the bridge sent an IRC->Matrix message, timestamped to 9:06, even though I sent it at 8:54
* at 9:07, puppets started reconnecting
* at 9:21, about a tenth of the puppets are back online, some channels still did not have any puppet at all

Matrix users did not get any notification of the outage, and https://status.matrix.org/ is green.

**Comment by Half-Shot** [comment]
Looks like we had a shudder as a result of some admin actions. I'm having a look, mostly seems to be reconnections.

**Comment by Half-Shot** [comment]
Bridge restarted. Should be back in a bit. I'll do a quick status line.

**Comment by Half-Shot** [comment]
Well I spoke too soon. It had another issue after recovering.

**Comment by Half-Shot** [comment]
Issue logged as #1694 , we're watching the recovery now.

**Comment by alanz** [comment]
Is it possible to inject something equivalent to a ChanServ message to the affected rooms saying this has happened? So we can know to look at alternate logs for anything possibly missing

**Comment by Half-Shot** [comment]
This issue did recover, so closing.
