### ISSUE TITLE
Matrix HQ isn't bridged to Libera.Chat anymore

### ISSUE THREAD

**Issue by progval** [matrix-org/matrix-appservice-irc#1707]
Last message received on Libera is today at 08:44:12Z.

IRC messages don't seem to be received on matrix.org either.

**Comment by Half-Shot** [comment]
Sounds like federation spltibraining?

EDIT: Confirmed, it's federation troubles resulting from todays spam. Should recover eventually.

**Comment by progval** [comment]
i see, thanks
