### ISSUE TITLE
Libera messages aren't relayed to Matrix

### ISSUE THREAD

**Issue by progval** [matrix-org/matrix-appservice-irc#1708]
It seems to affect every channel

* #libera:libera.chat since some time between 12:37:25 and 13:25:57 (tested from matrix.org)
* #emacs:libera.chat since some time between 12:25:16 and 13:18:33 (tested from matrix.org)
* #guix:libera.chat since some time between 13:07:00 and 13:21:00 (tested from matrix.org)
* #libera-matrix:libera.chat (tested from matrix.org and mozilla.org)
* #irc:matrix.org (tested from matrix.org and mozilla.org)
* some private rooms
* existing PMs (but not new PMs)

(timestamps in UTC)

**Comment by progval** [comment]
Looks like the bridge just started backfilling 7 hours' worth of logs

**Comment by Half-Shot** [comment]
Identified as a federation outage from L.C to the rest of the federation. https://status.matrix.org/incidents/w7k9pw397tj1

**Comment by Half-Shot** [comment]
The host seems to have finished backfilling and is now handling traffic normally.

**Comment by Half-Shot** [comment]
Going to close, @progval etc please ping if you're still seeing issues.

**Comment by podiki** [comment]
I don't know if this is a holdover from that event, but not currently seeing libera messages relayed to the Matrix side, but vice versa does work. This appears to have started within the past ~12 hours or so from what I can see
