### ISSUE TITLE
IRC messages don't appear

### ISSUE THREAD

**Issue by ApostolosB** [matrix-org/matrix-appservice-irc#1728]
Go to a channel that uses a bridge between matrix and irc.
Post a comment in IRC
You wont see anything in matrix
Posting a comment on matrix makes it appear on IRC

**Comment by progval** [comment]
duplicate of matrix-org/libera-chat#6

**Comment by ApostolosB** [comment]
This seems to be fixed. I can see IRC messages. I'll close this.
