### ISSUE TITLE
IRC quits/parts are not bridged

### ISSUE THREAD

**Issue by mcnesium** [matrix-org/matrix-appservice-irc#1730]
In version `0.38.0`, when IRC users quit/part an IRC channel, their corresponding Matrix equivalents are not being removed from the corresponding Matrix room.

**Comment by jkhsjdhjs** [comment]
Duplicate of https://github.com/matrix-org/matrix-appservice-irc/issues/1618
0.34 seems to be the last good version

**Comment by mcnesium** [comment]
This issue is obsolete. Closing.
However, please see #1776
