### ISSUE TITLE
Question: Where to report outages of the bridge?

### ISSUE THREAD

**Issue by airone506** [matrix-org/matrix-appservice-irc#1735]
Matrix <> Libera IRC bridge in these days frequently has massive outages with 100% of IRC message loss, duration for many hours up to a few days. Only join/leave IRC messages are being bridged. https://status.matrix.org/ usually reports the bridge as fully operational, incidents are published retrospectively or with a big delay.

**What would be the right place to report these outages?**
- support@matrix.org: response takes many days if ever;
- #libera-matrix Libera channel: the good people in the channel always give a response, but they can do nothing about the outages;
- #irc:matrix.org Matrix room, bridged to #matrix-irc Libera channel: some info about outages usually reported by the users, but no effect on reported outages;
- open an issue here for every such separate outage?

**Comment by airone506** [comment]
I started a separate thread [here](https://github.com/matrix-org/libera-chat/issues/5).

**Comment by Half-Shot** [comment]
Hey there, we are moving libera.chat specific support issues (and outage reporting) to https://github.com/matrix-org/libera-chat to seperate issues from the code repository. We'll be making more noise about it soon, but please start using that.
