### ISSUE TITLE
status.matrix.org says the W3C bridge is 100% up

### ISSUE THREAD

**Issue by progval** [matrix-org/matrix-appservice-irc#1750]
But it is 100% down since 8 months ago (#1647).

There's also a leftover "Torn IRC bridge" that is 100% up, which seems to be Freenode.

**Comment by Half-Shot** [comment]
The torn bridge is it's own network, though it probably doesn't really *need* a status page entry.

W3c the bridge is technically up and in use, according to my notes.

**Comment by thibaultamartin** [comment]
The W3C bridge got portalled rooms disabled, but it's still up and running for plumbed rooms? I'll reach out to them to clarify the situation

**Comment by progval** [comment]
Indeed, my bad.
