### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by altf4arnold** [matrix-org/matrix-appservice-irc#1789]
Hello,

I'm trying to install the bridge on a Debian 12 using the documentation. 

When I execute the instructions to install from git (release 1.0.1), I get 
```
00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.
```

yarn install --global matrix-appservice-irc

Also didn't work (even in root)

**Comment by morguldir** [comment]
https://stackoverflow.com/questions/53471063/yarn-error-there-are-no-scenarios-must-have-at-least-one

You have the wrong yarn :3

**Comment by altf4arnold** [comment]
Indeed. That was the problem. Thank you :-)
