### ISSUE TITLE
MediaProxy cannot GET media

### ISSUE THREAD

**Issue by pwpreacher** [matrix-org/matrix-appservice-irc#1828]
I have the bridge configured to a small irc network with an unfederated Matrix server - 

Latest version of the bridge from git. Version of server is 1.117.0

when i try to look at the media through the media proxy like   https://xxxxxxx/media/v1/media/download/AULqvYiasrP97M-gUTqfoaXsaizgy8NNFDHwf7RoBQIpuVUUE9C0Qr0WWr1gbe1W72Hkg2P1vlwe59rE8uXjcaNCeSujO1wgAGtuaWdodGlyYy5uZXQvS0F6bnRRTVVvQnJGWGlRSUZmbW11RUlZ 

I get the reply from the server

Cannot GET /media/v1/media/download/AULqvYiasrP97M-gUTqfoaXsaizgy8NNFDHwf7RoBQIpuVUUE9C0Qr0WWr1gbe1W72Hkg2P1vlwe59rE8uXjcaNCeSujO1wgAGtuaWdodGlyYy5uZXQvS0F6bnRRTVVvQnJGWGlRSUZmbW11RUlZ

not sure what is going wrong

**Comment by pwpreacher** [comment]
Okay problem solved, I had setup a media.xxxxxx reverse proxy and so had setup media.xxxxxx/media as the link, which is what caused the problem the solution was to just setup media.xxxxxxx

**Comment by poVoq** [comment]
I have the same issue, but your explanation of the solution is not quite clear to me. Could you please share a snippet of your Nginx config or relevant parts of the config.yaml here? Thanks!

**Comment by poVoq** [comment]
Ok, after moving everything to a dedicated subdomain it works here now. Would be still interesting to understand why it didn't work with /media no matter what I tried.
