### ISSUE TITLE
Recent commit messages reference the wrong PRs

### ISSUE THREAD

**Issue by progval** [matrix-org/matrix-appservice-irc#1829]
It looks like these recent commit messages: https://github.com/matrix-org/matrix-appservice-irc/compare/3.0.2...3.0.3

were made as PRs in a new private repository, squash-merged, and pushed to this one. This makes Github create commit messages referencing PR numbers in your private repository, but also link to unrelated issues and PRs in this repository.

**Comment by tadzik** [comment]
Yeah, that's exactly what happened.

Unfortunate, but I don't think it's worth fixing now (given that it'd require rewriting git history). I'll remove them from the changelog though.

**Comment by tadzik** [comment]
Please do reopen if you can think of a better way to address this. Thanks for the callout!
