### ISSUE TITLE
Allow 1:1 channel name mapping

### ISSUE THREAD

**Issue by mweinelt** [matrix-org/matrix-appservice-irc#186]
I am trying to privde a matrix irc bridge for hackint and subsequently use `irc.hackint.org` as its domain. The proper channelnames in my opinion would be `#channel:irc.hackint.org` but that is currently impossible to achieve.

What I can get is `##channel:.irc.hackint.org` but that is very counterintuitive and it doesn't looky very pleasant tbh.

**Comment by Kegsay** [comment]
This breaks because channels can start with characters other than `#` (notably `&`), so you need a double `#` somewhere.

**Comment by mweinelt** [comment]
Indeed `&channels` exist, but they're usually local to a single ircd and as such, at least in my opinion, rarely used and of less relevance.

**Comment by mweinelt** [comment]
Fwiw, we achieved this a long time ago by patching the schema like this

```diff
diff --git a/lib/config/schema.yml b/lib/config/schema.yml
index 4ca77f9..b7c5fc7 100644
--- a/lib/config/schema.yml
+++ b/lib/config/schema.yml
@@ -240,7 +240,7 @@ properties:
                                     type: "boolean"
                                 aliasTemplate:
                                     type: "string"
-                                    pattern: "^#.*\\$CHANNEL"
+                                    pattern: "^.*\\$CHANNEL"
                                 whitelist:
                                     type: "array"
                                     items:
```

With this change you can set 

```
        # The room alias template to apply when creating new aliases. This only
        # applies if createAlias is 'true'. The following variables are exposed:
        # $SERVER => The IRC server address (e.g. "irc.example.com")
        # $CHANNEL => The IRC channel (e.g. "#python")
        # This MUST have $CHANNEL somewhere in it.
        # Default: '#irc_$SERVER_$CHANNEL'
        aliasTemplate: "$CHANNEL"
```

**Comment by Kegsay** [comment]
The bridge code will likely assume that if a string passes the `aliasTemplate` check that it starts with `#`. If this is not true for any reason, it's likely to cause it to crash, which would be disruptive for the entire bridge. I'm happy that your monkey-patch works, though I'd be even happier if you PR'd a more comprehensive fix so everyone can benefit :)
