### ISSUE TITLE
Provide a way to remove a bridged client entirely

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/matrix-appservice-irc#195]
If someone removes their Matrix account (or deactivates or whatever), there should be a way to tell the bridge to stop bridging that connection entirely.

The HS doesn't currently poke ASes when accounts are deactivated (and that wouldn't help for federated HSes) so we can't really do it like that. We can add a `!disconnect` or `!kill` option to the IRC admin room, but that doesn't help for the general case where we have guests piling up.

**Comment by Kegsay** [comment]
This is very similar to https://github.com/matrix-org/matrix-appservice-irc/issues/74

**Comment by lukebarnard1** [comment]
We now have `!quit` (https://github.com/matrix-org/matrix-appservice-irc/pull/253) but we still need to deal with guests piling up.

**Comment by Kegsay** [comment]
Dealing with inactive users piling up isn't an IRC bridge specific problem - we have this issue on Matrix HQ. I'd rather we make a Matrix solution which the bridge piggybacks off on (eg idle timers resulting in kicks, which we already mirror).
