### ISSUE TITLE
IRC Admin Room -> Network-specific Name

### ISSUE THREAD

**Issue by lukebarnard1** [matrix-org/matrix-appservice-irc#198]
Ideas:
- Need to have the first two words to distinguish between admin rooms.
- Probably shouldn't have the word "room" in the name, it's already a room.
- Maybe a topic should describe what it does!

Candidates:
- ~~Freenode Admin Room~~ includes word room
- ~~Freenode IRC Admin Room~~ includes word room
- ~~IRC Admin (Freenode)~~ can't distinguish with first two words
- ~~irc.freenode.net Connection Admin~~ too long, use topic instead
- **irc.freenode.net Admin, /w topic**

**Comment by Kegsay** [comment]
This totally happened.
