### ISSUE TITLE
Basic ops bridging

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-appservice-irc#206]
If a Matrix-originated user is given ops in IRC (by chanserv or another chanop), surely we can simply increase their power on the Matrix side of the room to 50 or something, so they can then go and configure the Matrix side of the room

**Comment by Kegsay** [comment]
We cannot map the full complexity of chanops vs matrix power levels. If the person on IRC giving the Matrix user ops is unaware of the differences, they may be inadvertently giving them much more power than they think they are. This is problematic. In the case where both sides know of Matrix and the implications of power level 50, then this could work rather well.

**Comment by ara4n** [comment]
We don't need to map the full complexity of chanops.  Given we know '50' is de facto moderator in Matrix, I suggest we just map op to 50 and be done with it.  If you've set up weird power levels in the room, then it's your own lookout.

**Comment by Kegsay** [comment]
Agreed - it's the pragmatic solution here.

**Comment by Kegsay** [comment]
I want to get this in the next version of the IRC bridge.

**Comment by Mikaela** [comment]
Are there plans for bridging voice somehow? I know it doesn't directly exist at Matrix and there isn't badge for it, but there is muting room by setting power level required to talk to something and giving talking users some higher power level.

I guess it's not so important, but some rooms use it for showing ops (I wish they were opped), others show regulars and others contributors or wiki editors and similar and I thought I could ask in this issue.

**Comment by Kegsay** [comment]
We have no plans in the near future to bridge voice. It's a really slippery slope: we just want very basic ops bridging for the immediate future.

**Comment by Kegsay** [comment]
https://github.com/matrix-org/matrix-appservice-irc/pull/327

**Comment by ara4n** [comment]
@kegsay i think this can be closed?

**Comment by ishitatsuyuki** [comment]
Does that one support forwarding of kick/ban from Matrix -> IRC? Otherwise it sounds useless.

**Comment by Kegsay** [comment]
@ishitatsuyuki kicks/bans are already mirrored.

**Comment by Mikaela** [comment]
Assuming the IRC ghost is opped?

**Comment by Kegsay** [comment]
@Mikaela correct.

**Comment by Kegsay** [comment]
> i think this can be closed?

Yes.
