### ISSUE TITLE
Re-invite matrix users that have left a bridge created IRC<->Matrix PM room

### ISSUE THREAD

**Issue by lukebarnard1** [matrix-org/matrix-appservice-irc#217]
If you leave a PM room that let you chat with an IRC user, messages sent IRC->Matrix appear to go nowhere. A new invite should be sent to re-invite the matrix user that has left.

**Comment by Kegsay** [comment]
I thought I fixed this months ago... did we break it?

**Comment by Kegsay** [comment]
https://github.com/matrix-org/matrix-appservice-irc/issues/41

**Comment by Kegsay** [comment]
@lukebarnard1 can you repro this? If not, please close.

**Comment by Kegsay** [comment]
I'm going to go with "this is fixed and if it isn't, it'll be re-opened".
