### ISSUE TITLE
Bridge will spam HS with visibility

### ISSUE THREAD

**Issue by lukebarnard1** [matrix-org/matrix-appservice-irc#220]
The bridge currently will spam HS with visibility: private/public on startup because it will receive channel modes and assume that the room is out of sync.

**Comment by lukebarnard1** [comment]
IRL: Apparently this is fine but we'll keep this here until testing confirms that we don't see any issues.

**Comment by Kegsay** [comment]
From trying the FN bridge, I didn't notice any problems here. However, the MODEs were trickled back and I'd love to know by whom. I don't think the bridge does this?

**Comment by lukebarnard1** [comment]
The bridge does tell node-irc to floodProtect by sending in a constant of 700ms, and when experimenting by decreasing this, it does indeed alleviate the trickling `onMode` issue.

https://github.com/matrix-org/matrix-appservice-irc/blob/master/lib/irc/ConnectionInstance.js#L11

**Comment by Kegsay** [comment]
Oh awesome so it's us doing that. \o/ cool - this issue is resolved then.
