### ISSUE TITLE
Presence-based membership list syncing

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-appservice-irc#222]
We really really really need to be syncing membership list from IRC to Matrix by default so that folks in Matrix don't end up speaking to long-since-gone users on the IRC side.  We've held off historically as the volume of join/part spam is too high and chews CPU & diskspace on synapse with all the state changes.

A relatively nice solution could be:
- When IRC users quit, the bridge changes their presence to `disconnected` (a new state)
- If they come back within N minutes (after bouncing their clients; a netsplit etc), their presence is restored to online.
- Otherwise they are parted from the room with an actual membership change.

Clients would treat 'disconnected' presence events very similarly to part events; they're just not persisted in the DAG (but are persisted otherwise, so actually perfectly useful).

Discussing with @erikjohnston there are concerns that this may be overkill given the biggest source of offensive join/part traffic are netsplits, and we can typically recognise and suppress those by the quit messages (although one might still want to bridge them into presence data).

Suggestion is to do some stats to find out what patterns there are in typical IRC join/part spam - specifically, how many parts are transient, and how many of those are netsplits, and so what the best mitigation is.

**Comment by ara4n** [comment]
To progress this, let's:
 * [ ] Analyse some Freenode IRC logs to see how much join/part spam we can suppress if we:
   * Shift to a 15 minute window for bridging joins/parts (using presence in the interim)
   * Special-case netsplitted users (giving them an hour to come back)
 * [ ] Need to make Riot at least finally collapse joins & parts onto a single line so that during an initial cleanup we don't spam people too much with all the parts. https://github.com/vector-im/vector-web/issues/349
 * [ ] Trickle the parts on initial bridge startup to avoid DoSing synapse (although let's go as fast as we can)
 * [ ] ...unless we can get synapse to do some kind of bulk DAG operation to dump them all (perhaps on local only rooms as a special case?)

**Comment by Kegsay** [comment]
This is blocked on Riot correctly collapsing joins/parts to avoid pissing off every Riot user in the world.

**Comment by jimmycuadra** [comment]
A possibly related issue is that Matrix doesn't handle IRC users changing their nicknames. If user Foo changes their nick to Bar, both Foo and Bar show up in the user list from then on, and the Matrix user has no idea which nickname the person is actually using on the IRC side.

**Comment by Kegsay** [comment]
That is https://github.com/matrix-org/matrix-appservice-irc/issues/71

**Comment by Kegsay** [comment]
Riot now collapses join/parts.
