### ISSUE TITLE
+s leaking into rooms that are public

### ISSUE THREAD

**Issue by lukebarnard1** [matrix-org/matrix-appservice-irc#223]
We need to look at the total graph that each room is a part of - i.e any channels it is mapped to and any rooms those channels are mapped to and any ......... etc.

This graph can then be checked to see if ANY of the channels within it are +s and if they are, set the visibility to private.

This also needs to be checked every time the mode changes. So we need the following:

- [x] New data structure to maintain a cache of +s and private/public and mappings between channels and rooms.
- [x] When frontier users join rooms, make sure to trigger 'mode' so that onMode is received at least once for each channel. 
- [x] When onMode, update the data structure and solve any discrepancies by making matrix as private as needed. That means if a public room is connected M -> #bla <-M2-> #secrets and #secrets has +s, then M should be made private ASAP!

@Kegsay I'm assuming the above looks sane to you?

**Comment by Kegsay** [comment]
Mostly, but I think you *may* be overcomplicating the graph lookup:

> i.e any channels it is mapped to and any rooms those channels are mapped to and any ......... etc.

You don't need to recursively do this. You only need this graph to perform 2 actions:
 - Given a room ID, should this Matrix room be public or private? (Frontier entries; syncs state on startup)
 - Give a mode change to `+-s`, which Matrix rooms should be made public/private? (Live changes as you get them)

For the first case, this is really easy: (Python pseudo-code)
```py
room_id = "!foo:bar"
chans = get_mapped_chans(room_id)
visibility = "public"
for chan in chans:
  if chan.has_mode("+s"):
    visibility = "private"
    break
```

For the second case, this is a bit more involved since you need to loop-back on yourself once, but certainly not recursively:
```py
chan = "#foo"
room_ids = get_mapped_rooms(chan)
for room_id in room_ids:
  # NB: This bit is the same as the first snippet
  visibility = "public"
  more_chans = get_mapped_chans(room_id)
  for c in more_chans:
    if c.has_mode("+s"):
      visibility = "private"
      break
  print "%s is %s" % (room_id, visibility)
```

**Comment by lukebarnard1** [comment]
Not sure why we shouldn't do it recursively? If I plumb a secret channel into a room that is public and that room is plumbed into a channel that is -s and is that -s channel is plumbed into a room that is public, shouldn't _both_ rooms become private?

**Comment by Kegsay** [comment]
You're right. I think you're describing this afaict:
```
 IRC        |        Matrix

#secretz ---------------+
                        |
                   !public:room
                        |
   .--------------------+
#public
   `-------------- !another:public
```

So yes, you need to walk the entire graph of linked rooms to figure out if `+s` has contaminated the lot.

**Comment by Kegsay** [comment]
Done now~
