### ISSUE TITLE
userTemplate matches against federated homeservers

### ISSUE THREAD

**Issue by mweinelt** [matrix-org/matrix-appservice-irc#232]
Lets assume there is a user @irc_ralith:matrix.org.

@irc_ralith matches our current `userTemplate: "@irc_$NICK"`, albeit with a different homeserver.

@irc_ralith:matrix.org will not get bridged to IRC when joining #channel:irc.hackint.org, because he is assumed to be a virtual user by the bridge.

Worse, if the template were `@$NICK`, which is desirable, everybody would be found to be virtual and therefore noone would get bridged.

**Comment by mweinelt** [comment]
duplicate of #190

**Comment by Kegsay** [comment]
Fixed on `develop`: #277
