### ISSUE TITLE
I->M: Out of order PMs

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/matrix-appservice-irc#235]
Bug: Saying `help` to NickServ returned an out of order multi-line response.

> Thomasj: Just tested sending help to freenode nickserv. I'm now receiving messages out of order
> 
> Kegan: as for the ordering, it looks like the first message executes a different code path which may (haven't looked at the code to know for sure) result in out of ordering. When the bridge first gets a message from an IRC user in a PM, it checks to make sure that the real Matrix user is still in their PM room (and invites them if they are not). I suspect that check is not guarded against concurrent execution, but the act of sending messages is (that's built into the JS SDK's MatrixClient).
> 
> Kegan: If my theory is right, saying `help` again should produce the response in the correct order
> 
> Thomasj: Coming in the correct order now it seems

so what's happening there is this:

```
           --> Msg1 --> checkInRoom ------------------------------------> sendMessage
           |
NickServ ----> Msg2 --> checkInRoom -----> sendMessage
           |
           --> Msg3 --> checkInRoom ---------------------> sendMessage

Sends Msg2,Msg3,Msg1
```

the calls to `sendMessage` maintain a queue, but the bridge is calling `sendMessage` in the wrong order because `checkInRoom` races and returns at random points.

**Comment by fuzzy76** [comment]
Could this be related to #145 as well?

**Comment by Half-Shot** [comment]
I'd say this is pretty conclusively fixed.

![image](https://user-images.githubusercontent.com/2072976/74032994-29f03780-49ad-11ea-88c2-f12d27038ac6.png)
