### ISSUE TITLE
Splitting messages truncation

### ISSUE THREAD

**Issue by unclechu** [matrix-org/matrix-appservice-irc#238]
I get again and again same error with UTF-8 (Cyrillic for example) in big messages, it looks like some of unicode symbol bytes is sliced and broken, and people who use encoding auto-detection feature in their IRC clients see this messages in non-unicode wrong encoding. Usually only one symbol is broken but whole message is in wrong encoding.

Message could be broken even if it isn't sliced to parts.

People that use IRC clients said they can set `utf8` for everything and they can read the messages but only one symbol in truncated.

**UPD** It looks like this issue is not about only unicode. Also big message with only numbers (that just is 1 byte because it's ASCII chars) splits with 1 symbol lost for every part.

<img src="https://matrix.org/_matrix/media/v1/download/matrix.org/DKEvIMxOQqHINEWBuVyWwzvV">
<img src="https://matrix.org/_matrix/media/v1/download/matrix.org/UUKHbVPSCfqntOahVOHHXQsF">

**Comment by Kegsay** [comment]
I suspect this is https://github.com/matrix-org/matrix-appservice-irc/issues/135 just in a different form.

**Comment by Kegsay** [comment]
On further reflection, I still believe this is #135 just in another form, so closing this issue in favour of #135.
