### ISSUE TITLE
Restructure message for uploaded content / long posts to avoid confusion

### ISSUE THREAD

**Issue by eternaleye** [matrix-org/matrix-appservice-irc#239]
Multiple users on the IRC side have been confused by the formatting of these messages

Some have their client try to eat the space after the URL, breaking it; others assume the IRC bridge failed to properly escape a space

It might be best to format it as `/me uploaded <filename> : <url>` or something similar

**Comment by lukebarnard1** [comment]
FTR, the current appearance for images/files is:
```
http://localhost:1234/_matrix/media/v1/download/localhost:4321/PQoiokwsVXbZzGvXXiotIgia - some_image.jpeg (115KB)
```
and long posts are pastebinned to
```
http://localhost:1234/_matrix/media/v1/download/localhost:4321/gVyzaGQIdPooXdolVkADRdfr - user[m]_2016-10-26_13:13:34.txt
```

**Comment by Kegsay** [comment]
Superseded by #258
