### ISSUE TITLE
Remove rate limiting on NickServ/ChanServ

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/matrix-appservice-irc#240]
Requires:
- The AS reg file has a flag to say turn off rate limiting (default: rate limiting is on).
- Synapse to honour the reg file
- The bridge to flip rate limiting off on reg file generation.

**Comment by lukebarnard1** [comment]
- [ ] IRC bridge registration file should set `rate_limiting: false` in reg file
- [ ] Synapse should understand that flag and turn rate limiting off for all virtual users of the AS

**Comment by lukebarnard1** [comment]
Added support label as the freenode bridge at matrix.org will be redeployed tomorrow on 0.6.0 to test that this works. If it does, I'll close this issue.

**Comment by Kegsay** [comment]
It does work.
