### ISSUE TITLE
Support TLS (Freenode)

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/matrix-appservice-irc#241]
This needs to be turned on. We didn't previously because it [interacted badly](https://github.com/matrix-org/matrix-appservice-irc/issues/39) with ident, but now we're on IPv6 this isn't an issue (since we don't use ident).

**Comment by Kegsay** [comment]
We seem to be hitting a throttling/limiting problem when we enable TLS on our IPv6 connections. New connections end up `ETIMEOUT`ing after aprox 1000 connections, and then they seem to trickle in 5 minute gaps. Need to talk to Freenode staff before we can enable this again.

**Comment by Mikaela** [comment]
Was @freenode ever contacted? I recall this issue being noticed last week.

**Comment by Kegsay** [comment]
Not yet.

**Comment by Kegsay** [comment]
Haven't forgotten about this - I need to work on https://github.com/matrix-org/matrix-appservice-irc/issues/272 first before we can realistically re-enable this.

**Comment by Kegsay** [comment]
FYI I think I know why Freenode falls over on TLS: https://github.com/matrix-org/matrix-appservice-irc/issues/352

**Comment by Kegsay** [comment]
All outstanding issues preventing us from trying TLS again on Freenode have been fixed. I would like to analyse the CPU usage of the bridge prior to deploying this on Freenode given TLS is computationally expensive: I'm particularly worried about startup times and reconnection times.

**Comment by Kegsay** [comment]
> I would like to analyse the CPU usage of the bridge prior to deploying this on Freenode given TLS is computationally expensive

As of today, I have added support for doing 10 second cpu profiles via SIGUSR2. I'm using this to debug general cpu spin problems, but will also use this to profile general background levels of work to see if turning on TLS will exacerbate anything. See #404 for spin issues.

**Comment by Kegsay** [comment]
CPU usage with #404 fixes applied is down a lot at startup and BAU runtime (50% and 10% respectively). This is good news because it means setting up TLS at startup for all 9k connections will have a lot of headroom.

As a result, I intend to turn on TLS at the next Freenode bridge restart (1-2 weeks) so this issue can finally be closed. It's worth noting that all the other bridges have been using TLS for ages (oftc, moznet, snoonet, gimpnet), it's just Freenode that has caused us logistical problems.

**Comment by Kegsay** [comment]
This happened. It works. :tada:
