### ISSUE TITLE
We should consider setting umode +R on bots to stop them receiving PM spam

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-appservice-irc#302]

**Comment by TJuberg** [comment]
Unless the bots are expected to respond to any commands you might consider setting +g as well. In essence only allowing people the bot sends messages to, to respond. Though +R would take care of most. However be warned that any chanops that are not currently identified (thus marked as registered) will not be able to respond to a plumbing request with +R which should probably be mentioned in the riot GUI if implemented.

`+g Ignores private messages from unknown users, instead informing you someone is attempting to message you. You can choose to receive messages with the /accept command. Messaging a user automatically accepts them.`

**Comment by Mikaela** [comment]
I think that in this context bots mean bridged users at IRC and thus are people.

I personally don't use native IRC clients with any networks that don't have umode +g as I need it, but I can see it causing trouble with people who don't know about it.

For example if you are talking with a IRC user and they have connection problem or quit in the middle of the discussion (or if there is night in the middle or something), the IRC user will be confused as they are unable to respond to the Matrix user if their message is the first after reconnection. The Matrix user can also be confused if they don't receive message they are expecting.

**Comment by Kegsay** [comment]
This is now a configurable option: https://github.com/matrix-org/matrix-appservice-irc/blob/d2a741d87c34d0dc4ef9cb14143c4009261056d2/config.sample.yaml#L283

and +G is currently set on OFTC.
