### ISSUE TITLE
initial /sync sometimes fails

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-appservice-irc#303]
looks like we have a 5 minute timeout somewhere on /sync responses (in dendron, perhaps?). if the final attempt to /sync completes close to the 5 minute mark, then the response may get truncated, which the ircas seems to silently ignore and thus fail to run.  Need to increase the timeout, use a better LB, or move away from /sync.  Also unclear why this wouldn't affect normal clients too (or perhaps it does)

**Comment by Kegsay** [comment]
Interesting! So *that's* why it sometimes seems to give a valid response with 0 rooms. This will hopefully go away when https://github.com/matrix-org/synapse/pull/1680 lands on matrix.org

**Comment by Kegsay** [comment]
We've moved away from `/sync`.
