### ISSUE TITLE
Provide a list of bot commands

### ISSUE THREAD

**Issue by lbeltrame** [matrix-org/matrix-appservice-irc#316]
As the subject says, it may be needed to quickly evaluate what the bot can do and what can't. In my particular case, I'm interested in how services like NickServ are handled. 

I've looked in the source but I didn't find a proper list.

**Comment by Kegsay** [comment]
Looks like I beat you to it! https://github.com/matrix-org/matrix-appservice-irc/pull/314 - This isn't on any of the matrix.org bridges yet.
