### ISSUE TITLE
!join should not work if dynamic channels are disabled

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/matrix-appservice-irc#320]
Apparently it does!

**Comment by lukebarnard1** [comment]
https://matrix.to/#/!SudviOJlimDvrGdFCY:matrix.org/$14821865251298785FGCgA:matrix.org

**Comment by erdnaxeli** [comment]
Why should it not?

**Comment by Kegsay** [comment]
Because dynamic channels means "I'm okay with any random matrix user joining any random IRC channel that I'm bridging to". That's a **lot** of freedom. Some people may want to restrict the bridge to only allow channels `#foo` and `#bar`, so they may want to disable dynamic channels and have a few config file mappings instead. When dynamic channels are disabled, we don't service the alias requests, but it looks like `!join` requests still work, when they should only work for the config file mappings.

**Comment by Half-Shot** [comment]
Fixed by https://github.com/matrix-org/matrix-appservice-irc/pull/957
