### ISSUE TITLE
Stop matrix memberlist spamming up with GitHub123 users from IRC GH integ

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-appservice-irc#322]
Need a way to reap em, or honour the external msgness or something

**Comment by Mikaela** [comment]
There is also Not-123 and #commits at freenode possibly shows a lot more of those bots.

Wouldn't #222 fix this?

**Comment by ara4n** [comment]
i'm not sure if this is due to the GH bots being external messages or presence list sync fail on FN...

**Comment by Kegsay** [comment]
https://github.com/matrix-org/matrix-appservice-irc/issues/42
