### ISSUE TITLE
Support +k channels

### ISSUE THREAD

**Issue by fuzzy76** [matrix-org/matrix-appservice-irc#33]
Any plans of supporting these? I really need it. :-/

**Comment by fuzzy76** [comment]
Is this waiting on https://matrix.org/jira/browse/SPEC-61 or could a temporary hack be made?

**Comment by fuzzy76** [comment]
Would the !join command sent to the appserver-bot (forgive me if I'm mixing terms here) be a potential place to add this?

Looks like adding a parameter to the code at https://github.com/matrix-org/matrix-appservice-irc/blob/master/lib/bridge/matrix-to-irc.js#L232 and sending the key to irclib would do the trick...?

**Comment by Kegsay** [comment]
Yes, we can augment the `!join` command to allow `+k` access, as a quick win, since it is unlikely that Matrix will sprout the equivalent support anytime in the immediate future.

**Comment by fuzzy76** [comment]
I was hoping to be able to contribute this, but after discovering that the underlying irclib neither had key support nor any documentation, I had to give up. Would love this feature, though. 👍  (I actually have to keep a weechat instance up for one +k channel)

**Comment by Kegsay** [comment]
Looks like this bit needs to be augmented with a password: https://github.com/matrix-org/node-irc/blob/master/lib/irc.js#L902 as per https://en.wikipedia.org/wiki/List_of_Internet_Relay_Chat_commands#JOIN

Probably would need a `joinWithKey` function in addition to the existing `join`.

**Comment by Kegsay** [comment]
Actually, scratch that, you should just be able to do `.join("#foo keyhere")` with a space separator as per https://tools.ietf.org/html/rfc2812#section-3.2.1
