### ISSUE TITLE
#freenode_#machomebrew:matrix.org fails with 'you are not invited'

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-appservice-irc#334]
The IRC channel is chanmod +cnt, which should work fine

**Comment by Mikaela** [comment]
Same with #freenode_#toktok:matrix.org, I mentioned it at #irc:matrix.org once, but as it still appears invite-only and there is an open issue, I thought I could mention it.

**Comment by Kegsay** [comment]
This was caused by https://github.com/matrix-org/matrix-appservice-irc/issues/224 - we need to run a script to make sure that all public alias rooms that are NOT `+ki` have the correct `join_rule`.

**Comment by Kegsay** [comment]
https://github.com/matrix-org/matrix-appservice-irc/issues/187
