### ISSUE TITLE
User name sometimes truncated in github notifications coming from IRC

### ISSUE THREAD

**Issue by xyzz** [matrix-org/matrix-appservice-irc#350]
IRC:
![irc](https://cloud.githubusercontent.com/assets/1065521/22154510/e0d788ba-df3c-11e6-8f60-6d0adf3df27a.png)
Matrix:
![matrix](https://cloud.githubusercontent.com/assets/1065521/22154515/e45cb5d2-df3c-11e6-9c5d-a94dc6956b1e.png)
Matrix message source:

```json
{
  "origin_server_ts": 1484919974650,
  "sender": "@freenode_vitasdkbot:matrix.org",
  "event_id": "$148491997413845SzBzb:matrix.org",
  "unsigned": {
    "age": 978
  },
  "content": {
    "body": "[vita-toolchain] 173210 opened pull request #109: Use INSTALL_RPATH (master...library) https://git.io/vM9O6",
    "msgtype": "m.notice",
    "formatted_body": "[<font color=\"fuchsia\">vita-toolchain</font>] <font color=\"silver\">3210</font> opened pull request #109: Use INSTALL_RPATH (<font color=\"purple\">master</font>...<font color=\"purple\">library</font>) <font color=\"navy\"><u>https://git.io/vM9O6</u></font>",
    "format": "org.matrix.custom.html"
  },
  "type": "m.room.message",
  "room_id": "!WMcHXkArACbUaOtreb:matrix.org"
}
```

You can see the username is "173210" but it's truncated to "3210". This does not happen to other github users so it's probably because of numerical username?

**Comment by Kegsay** [comment]
Interesting. This seems like a formatting bug I->M.

**Comment by Kegsay** [comment]
Looks like this is https://github.com/matrix-org/matrix-appservice-irc/issues/353
