### ISSUE TITLE
When splitting messages the bridge does not always make messages short enough

### ISSUE THREAD

**Issue by maralorn** [matrix-org/matrix-appservice-irc#355]
Hey guys,

I just sent a long line (434 characters) from matrix into an IRC channel. The message was split, because it apparently exceeds IRC servers limits. The beginning and the last word were sent correctly but before the last word whole words (consisting of 14 characters) are missing completely.

Kind regards

**Comment by mweinelt** [comment]
The last word was also split in two, the second part was on the next line.

**Comment by Kegsay** [comment]
https://github.com/matrix-org/matrix-appservice-irc/issues/135

We're aware it's a problem, but haven't been able to isolate the cause yet. Will need to check upstream with `node-irc` to see if there are any PRs to fix this.
