### ISSUE TITLE
long messages that are links to txt files have incorrect encoding

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/matrix-appservice-irc#360]
It should always be `utf-8` but apparently people sometimes get `windows-1252`. This may be a Synapse thing. @NegativeMjark - as custodian of the content repo, thoughts?

**Comment by NegativeMjark** [comment]
I don't think the content repository changes the MIME-type of uploaded content. So the problem is probably with whatever is doing the uploading.

**Comment by Kegsay** [comment]
https://github.com/matrix-org/matrix-appservice-irc/pull/440
