### ISSUE TITLE
provisioning can end up creating admin rooms

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/matrix-appservice-irc#361]
If the user is alone in a room and tries to provision a room and that provisioning fails to complete for whatever reason (e.g no op on the IRC side), then the bridge sees this as an invite and not a provision. Since there is only 1 user in the room and that user invited the bridge bot to the room, it concludes that it must be an admin room. I don't see an easy way to detect this on the bridge side since they look identical (just invites into a 1:1 room).

**Comment by Half-Shot** [comment]
This should no longer happen, as we use `event.content.is_direct` to determine if an invite is meant to be a PM/Admin Room.
