### ISSUE TITLE
Dynamic mapping to a +i channel does not create invite-only room

### ISSUE THREAD

**Issue by erdnaxeli** [matrix-org/matrix-appservice-irc#362]
Hi,

I tried to join a room corresponding to a channel with the +i mode, and the created room is accessible to "Anyone who knows the room's link, apart from guests".

Reproduction:
- on the IRC network, join a new channel
- set mode +i
- join it from matrix

Version: 0.7.1 (a2b025683176924fcc5abb8dbb05b75572fc6b33)
Network: irc.iiens.net (UnrealIRCd)

Here is the `debug.log` file when trying with a channel name `#ohlol`: [ohlol.txt](https://github.com/matrix-org/matrix-appservice-irc/files/791112/ohlol.txt).

**Comment by Kegsay** [comment]
The log is pretty damning: it's a race between creating the room and querying `/mode` on the channel.

**Comment by Kegsay** [comment]
This does now.
