### ISSUE TITLE
does not cleanup users from matrix-groups

### ISSUE THREAD

**Issue by krombel** [matrix-org/matrix-appservice-irc#363]
in the matrix-group are more users than in the same group at the irc-side.

example
- on #freenode_#freenode:matrix.org has 18942 members while #freenode on irc.freenode.net has just 1553 users.

Maybe some "Disconnect/leave"-messages are not handled (correctly) or those messages just does not reach the gateway to be handled. In the second case a cleanup-script may be usefull

**Comment by Kegsay** [comment]
Dupe of https://github.com/matrix-org/matrix-appservice-irc/issues/344
