### ISSUE TITLE
Gitter users have unrecognisable names on IRC

### ISSUE THREAD

**Issue by xelra** [matrix-org/matrix-appservice-irc#364]
If someone is `Jim Carter @jimmieboy` on Gitter, they get a `@gitter_jimmieboy:matrix.org` account on Matrix. On IRC they're displayed as `JimCarterGitter[m]` and that name even gets truncated if it's too long. It's unrecognisable though, because the really important name is `jimmieboy`, which means you're constantly browsing GitHub, only to learn the names of the people in the chat and make sense of it all.

The name on IRC should be `jimmieboy[g]`. It would be really great if that could be changed.

**Comment by Kegsay** [comment]
This isn't a thing which the IRC bridge knows about. It uses the display name and that's it. You'll be better placed to file an issue with [that project](https://github.com/matrix-org/matrix-appservice-gitter/issues) instead.

**Comment by xelra** [comment]
That will not work, because in the same way that the irc bridge displays `jimmieboy (IRC)` on Matrix, the gitter bridge displays `Jim Carter (Gitter)` on Matrix.

In both directions the display name is not suitable for bridging, but `@freenode_jimmieboy:matrix.org` and `@gitter_jimmieboy:matrix.org` is.

**Comment by Kegsay** [comment]
This is a good point. The "correct" solution is to implement https://github.com/matrix-org/matrix-doc/issues/646 and allow bridges to identify when they are bridging bridged users so they can modify their logic accordingly. Until that point however, the IRC bridge's behaviour will not be changed.
