### ISSUE TITLE
Handle Multi-Line Matrix Messages Bridged to IRC.

### ISSUE THREAD

**Issue by MilkManzJourDaddy** [matrix-org/matrix-appservice-irc#366]
...as done in Matrix IRCd
> ...by splitting them into multiple lines. Best we can do, given IRC limitations.
https://github.com/matrix-org/matrix-ircd/pull/26 - Merged 

See also: [issues 258 comment](https://github.com/matrix-org/matrix-appservice-irc/issues/258#issuecomment-257821004) by [Kegsay](https://github.com/Kegsay).

It is noted that often IRC clients handle multi-line issued by `<shift>+<enter>` et cetera, by timing the delivery, and avoiding "flood".  It is possible that the bridge could do the same.

If this has already been merged, then clarification might help.

**Comment by Kegsay** [comment]
Multi-lined messages are already handled. They are sent as separate messages IRC side. There is a [limit](https://github.com/matrix-org/matrix-appservice-irc/blob/master/config.sample.yaml#L298) as to how many lines will be sent, but if you send below that number then they will already be split and sent.
