### ISSUE TITLE
bridge #redecentralize:matrix.org with freenode #redecentralize

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-appservice-irc#370]
the freenode channel as no ops, so they can't manually bridge it. would be nice if there was an easy way for us to manually override in scenarios like that.

**Comment by Kegsay** [comment]
Really interesting question, I'm not sure how best to approach that if there are no channel ops.

**Comment by Mikaela** [comment]
In my opinion it's not a bridge issue, but network issue and #recentralize people should contact @freenode and formally register as a group so they would manually op someone with OperServ and that someone could register it with ChanServ.

**Comment by Kegsay** [comment]
I'm inclined to agree with @Mikaela on this. If they instead want a Matrix community only then don't bridge to freenode. If they want the `#redecentralize` name on Freenode then they need to speak to Freenode. Pretty simple really.

**Comment by Mikaela** [comment]
I think I can safely close this as there weren't any comments disagreeing that this is freenode's issue.
