### ISSUE TITLE
Add NoteServ' Functionality.  But, Clarify if Nicknames are Registered.

### ISSUE THREAD

**Issue by MilkManzJourDaddy** [matrix-org/matrix-appservice-irc#372]
It is seen on Matrix where a native Matrix MXID will send to an IRC Nick', only to get a notification that the IRC user is unreachable.  

The "NoteServ(er)" is common enough on IRC, albiet "Store & Forward".  
Matrix routinely stores room messages.
IIRC, some IRC servers *might* have the ability to feed the last few lines, from before a Nickname connected, like XMPP.  

But, when doing so, it might be important to distinguish between **Registered** and **UN**registered Nickmames, perhaps prompting a native Matrix MXID to verity if they want to send a "NoteServ(er)"/stored message for an IRC Nickname that is not registered.

This should be considered for bridging to existing IRC networks, and Matrix IRCd alike.

**Comment by Kegsay** [comment]
Dupe https://github.com/matrix-org/matrix-appservice-irc/issues/348
