### ISSUE TITLE
IRC Mentions Do Not Always Trigger Matrix Notifications.

### ISSUE THREAD

**Issue by MilkManzJourDaddy** [matrix-org/matrix-appservice-irc#376]
This is because one needs to manually enter their IRC nickname as a keyword.  

But one does not always know how the appservice (re)connects a MXID into a nickname.  

And, the appserviced bridge might not keep a list of preferred IRC nicknames, unlike a native IRC client.

**Comment by pravi** [comment]
It would be very nice if IRC mentions are automatically highlighted.

**Comment by devnoname120** [comment]
Maybe at least show mentions made to the username that was specified with !nick (if specified). Maybe it's not very hard to implement and this would mitigate this issue.
