### ISSUE TITLE
Clarify the Power Sharing Between Matrix and IRC, in Provisioned and Manually Bridged Rooms, in the Wiki.

### ISSUE THREAD

**Issue by MilkManzJourDaddy** [matrix-org/matrix-appservice-irc#377]
This seems to be a confusing issue.  And even the Developers are strained to provide a clear answer, as the roadmap may not be set in stone.

And we must make distinction between how it works in rooms that are Provisioned, automatically, apart from rooms that are bridged by the integrations, sometimes called "plumbed" or "piped". There is a `m.<type>` somewhere.

So, let's Wikify the current way it works, and note how it is expected to change, here:  https://github.com/matrix-org/matrix-appservice-irc/wiki/

**Comment by Mikaela** [comment]
I quickly wrote https://mikaela.info/english/2017/03/19/imitate-matrix-atheme.html based on what I wrote to #irc:matrix.org earlier and I *think* it would fit somewhere under this wiki page or ops syncing page.

**Comment by Kegsay** [comment]
This happened. https://github.com/matrix-org/matrix-appservice-irc/wiki/Permissioning-in-Portal-vs-Plumbed-rooms
