### ISSUE TITLE
Apparently snoonet bridge rejoined rooms today which had previously been bridged

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-appservice-irc#378]
presumably they were disabled in scalar; the bridge was restarted; the disable didn't stick. users are unhappy as it was unbridged for a reason. @kegsay (or whoever): ask me for details

**Comment by ara4n** [comment]
apparently membership list reappeared and started syncing, but messages weren't bridged.

this is also the first instance i know of where drama has been caused by a room being multibridged - linking previous separate communities on freenode & snoonet on matrix => drama.

**Comment by Kegsay** [comment]
Yeah, I need to know:
 - Which side got disconnected (FN or Snoonet)
 - When this was done
 - When things got re-enabled

Will IRL with you.

**Comment by Half-Shot** [comment]
Whatever happened here, it's lost to the winds of time.
