### ISSUE TITLE
Some private messages from IRC users are silently not delivered to the Matrix user

### ISSUE THREAD

**Issue by afranke** [matrix-org/matrix-appservice-irc#382]
I am using a matrix.org account to access GIMPNet channels. Two IRC users (on Polari and Pidgin) from this network tried to talk to me in private, but I never got their messages. I got messages from other users with different IRC clients (xchat-gnome, hexchat, irssi).

The Polari user is able to send messages to someone who’s using another Matrix server and bridge than the one at matrix.org

The Polari user is registered with NickServ so the default +R flag shouldn’t be an issue. Still I tried `!cmd irc.gimp.org MODE AlexandreFranke -R` and didn’t get an error, but I still can’t get his messages.

**Comment by bochecha** [comment]
I'm the Polari user who can't spam @afranke any more.

I'll be happy to test anything you need in order to be able to spam @afranke all day long once again.

**Comment by aperezdc** [comment]
In case it is of use, I _can_ spam @bochecha using a private instance of the IRC bridge, which is configured with `userModes: ""` (it is not setting any user mode, except for those set by the server).

**Comment by bochecha** [comment]
> I can spam @bochecha

More importantly, you receive my private messages.

I receive private messages from @afranke just fine, it's just he doesn't receive mine.

**Comment by Mikaela** [comment]
I think this is side-effect of https://github.com/matrix-org/matrix-appservice-irc/issues/302.

**Comment by afranke** [comment]
> I think this is side-effect of #302.

Really? Even considering

> The Polari user is registered with NickServ so the default +R flag shouldn’t be an issue. Still I tried !cmd irc.gimp.org MODE AlexandreFranke -R and didn’t get an error, but I still can’t get his messages.

as I stated in my first comment?

**Comment by Kegsay** [comment]
as per #irc:matrix.org

> hmm, Alexandre Franke I just sent you a PM on gimpnet and it went through (in that the logs show that it was received and forwarded) and I am not registered with NickServ on gimpnet, so you must've turned off +R

**Comment by ara4n** [comment]
we've now disabled -R on gimpnet entirely, as it was causing mass confusion, and the network isn't big enough to suffer from PM spam.  If this situation changes we'll put +R again.

**Comment by afranke** [comment]
> we've now disabled -R on gimpnet entirely, as it was causing mass confusion, and the network isn't big enough to suffer from PM spam. If this situation changes we'll put +R again.

You may have solved #390 but this issue is still present. @bochecha (who is a registered user) still can’t send me private messages. Please reopen this issue.
