### ISSUE TITLE
Should freenode portal rooms be created with guest access allowed?

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-appservice-irc#383]
See https://github.com/vector-im/riot-web/issues/3335 - we have a huge UX problem for folks trying to use Riot as a bouncer for IRC.  Is it deliberate that FN rooms deny guests, and can we change it?

**Comment by Kegsay** [comment]
> Is it deliberate that FN rooms deny guests

Yes, because:
 - Enabling guest access by default becomes a trivial ban bypass tool (refresh page => done).
 - It encourages the spread of idle connections, as people visit a link then leave, polluting all freenode channels and increasing resource drain for us (and pissing off other channels). We only clear idlers infrequently.

> for folks trying to use Riot as a bouncer for IRC

We should be telling these people to **make an account**. Guest accounts are ephemeral (nuke your local storage and you're locked out), so if people are genuinely using guest accounts as a bouncer (and hence doing things like authing with NickServ) then they will need to repeatedly re-auth and re-join channels as the accounts inevitably get dropped.

**Comment by Mikaela** [comment]
I think it might be deliberate thinking of https://github.com/matrix-org/matrix-appservice-irc/issues/304 which would possibly be worse if gurst access to IRC rooms was allowed as currently guests seem to stay in the room until the idle kicker script monthly kicks them.

However having bridged rooms accessible to guests could help promote Matrix, I have two where I would allow guest access if freenode had ops syncing enabled as they aren't important enough. With one of them multiple webchat users would likely jump to Matrix and possibly deprecate Telegram in favour of it.

**Comment by Kegsay** [comment]
I'm not seeing any reasons to enable this by default. People just need to make an account, sorry. If individual groups want to allow guests, then they totally can do this (and many already have), but the default option should be conservative for both our sake and the channel being bridged's sake.

**Comment by ara4n** [comment]
Perhaps I'm just missing how one turns on guest access for a portal room?

I agree we may not want it by default, but some people (eg the indieweb example I gave) clearly do want guest access - just like all the other IRC web interfaces out there which don't require you to do a registration. Expecting the option of parity there is not unreasonable (or merits being closed unilaterally)

Reopening until we've reasoned this through fully.

**Comment by Mikaela** [comment]
> Perhaps I'm just missing how one turns on guest access for a portal room?

Either by requesting for PL 100 from Kegan or getting PL50 with ops syncing. 

> just like all the other IRC web interfaces out there which don't require you to do a registration.

They generally send IP address of the user to the IRCd so they work like the user was running IRC client locally while Matrix also works as a bouncer masking the original IP address and making it more difficult to ban only the abusive user and more tempting to just ban the Matrix bridge, so I don't think they can be compared.

**Comment by Kegsay** [comment]
This will be mitigated by the riot-web ILAG stuff I suspect.

**Comment by Half-Shot** [comment]
What he said, is there any reason to keep this around now that we are discouraging guests?

**Comment by Kegsay** [comment]
AFAIK there is no reason to keep this around now.

**Comment by Half-Shot** [comment]
Aye, closing. Please shout if it should not be the case.
