### ISSUE TITLE
IRC reconnections can consume all HTTP workers

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/matrix-appservice-irc#384]
The Freenode bridge occasionally loses a subset of its IRC connections (because it's Freenode). Because we have so many connections, this subset can be hundreds of users. Reconnections are generally pretty quick, but there is a characteristic spike in CPU usage and memory usage which has been difficult to track down. Latency times also spike for a few minutes after this event.

I caught the Freenode bridge in the act of doing this today and tailed the logs to see what it was doing. I think I know the cause now. It's the reconnection messages. The bridge will attempt to send 2N messages (where N is the number of dropped connections) to Matrix to say:
 - Connection lost
 - Reconnecting

And then another one on successfully reconnecting. This is consuming all the HTTP workers, increasing latency times and resulting in the characteristc spikey CPU graphs (Synapse blocks these requests for ages ~~probably~~definitely due to load).

Synapse got very unhappy because of this. Oops.

**Comment by Kegsay** [comment]
Spoke with @lukebarnard1 and debouncing these requests is probably the best trade-off here, given they do get reconnected quite rapidly. A 5 minute grace period followed with a QueuePool of 50 in-flight requests (they are all to different rooms) should work.

**Comment by Kegsay** [comment]
> The Freenode bridge occasionally loses a subset of its IRC connections (because it's Freenode)

I looked into this a bit more and yup, this just seems to be the way it is. The bridge logs show that all connections on `hobana.freenode.net` started getting pinged (this usually means trouble, we never usually get pings from the ircd because we pre-emptively send them pings which serve as 'traffic' and keep the connections alive), and then started getting knifed at 09:22 UTC with ping timeout messages. We spread out our connections to more servers now, so this only killed around 10% of our users (700 or so connections), but this at least explains why we lost them in the first place.

**Comment by Kegsay** [comment]
I have reason to believe this is also the cause of the outage between 01:00-08:00 UTC on 2017/03/03 - we were **still** trying to send reconnection notices 6 hours after the event(!).

**Comment by Kegsay** [comment]
I have set `sendConnectionMessages: false` on the Freenode bridge (which will take effect on the next restart) as a temporary measure to protect again this failure mode.

Debouncing connection messages will help for quick reconnects, but doesn't help the worst-case (e.g. our IPv6 link going down), because we will still fundamentally want to send 1000s of messages to Matrix ASAP. I don't see a nice way around this currently.

**Comment by Kegsay** [comment]
This has now taken effect on Freenode.

**Comment by Kegsay** [comment]
Tagged as `matrix.org-support` since this affects the Freenode bridge: no connection notices.

**Comment by Half-Shot** [comment]
#604 means we no longer immediately retry all connections and instead do N connections at a time which helps recovery somewhat.

**Comment by Half-Shot** [comment]
This seems to have been solved by #604. Going to close.
