### ISSUE TITLE
No way to see who’s an IRC chanop on Matrix

### ISSUE THREAD

**Issue by afranke** [matrix-org/matrix-appservice-irc#385]
With ops bridging we have users as Moderators when their ghost is given op. There is currently no way to see which IRC users (that are not ghosts of Matrix users) are ops. Granted, giving them Moderator on Matrix doesn’t make sense, but there should still be an indicator.

**Comment by Kegsay** [comment]
This is more than just informational now, it's actually needed for https://github.com/matrix-org/matrix-appservice-irc/issues/453 to work.

**Comment by Mikaela** [comment]
Do I understand correctly that this issue now also requires mapping mode +v which allows speaking in moderated rooms?

**Comment by Kegsay** [comment]
Yeah it'll need to be added to the `modePowerMap` in the config file in order for #453 to actually work correctly.

**Comment by Kegsay** [comment]
https://github.com/matrix-org/matrix-appservice-irc/pull/465
