### ISSUE TITLE
Members from #freenode #nm are not listed

### ISSUE THREAD

**Issue by albfan** [matrix-org/matrix-appservice-irc#386]
Using plain IRC I can see all members from that channel

Using /join #freenode_#nm:matrix.org I can't see nobody. But messages are posted on both clients, so bridge is working

**Comment by Mikaela** [comment]
Duplicate of https://github.com/matrix-org/matrix-appservice-irc/issues/344 ?

**Comment by albfan** [comment]
It seems thanks
