### ISSUE TITLE
Mechanism for migrating portal rooms to plumbed rooms

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-appservice-irc#387]
A typical flow for IRC bridging is that folks try it out via a portal, and then want to plumb it into an existing Matrix room.  As there is no way to evict the previous portal, all hell breaks loose with doubly-bridged users everywhere.

We need some kind of mechanism to migrate the portal room into a plumbed room, either by supporting turning a portal room into a plumbed room (by giving users ops in the portal room), or by somehow providing a mechanism to evict portals.

**Comment by Mikaela** [comment]
Doesn't ops syncing fix this for most of the users?

**Comment by Kegsay** [comment]
@Mikaela - I believe so. @ara4n ?

**Comment by ara4n** [comment]
i'm not sure how getting ops in a portal room helps replace the portal with a plumb?

**Comment by Kegsay** [comment]
> We need some kind of mechanism to migrate the portal room into a plumbed room, either by supporting turning a portal room into a plumbed room (by giving users ops in the portal room)

Are we crossing wires here? It completely helps!

**Comment by ara4n** [comment]
i'm failing to reason through the flow (even though i suggested it ;P). how does one de-portal a room if you have ops in it?

**Comment by Kegsay** [comment]
Conceptually a portal room has the following properties:
- no matrix admins
- well known alias which indicates the channel it is bridged to (#freenode_...)

A plumbed room has the following properties:
- At least 1 matrix admin
- Bridged to 1 or more channels

ergo a portal room with a matrix admin is a subset of plumbed rooms.

**Comment by Kegsay** [comment]
In other words, "how do you deportal a room if you have ops in it" is nonsensical.

**Comment by Kegsay** [comment]
I don't believe there is any actionable item to do here.

**Comment by Matrixcoffee** [comment]
Not quite sure why this got closed. Let's not turn this into a definition war.

The actual problem is that when someone plumbs a room via "manage integrations", the old bridge-generated room is also left intact, so there are now two matrix rooms going to the same IRC room, with an ugly Matrix<->IRC<->Matrix bridge between them.

This is confusing to users. (Which room to join?)

**Comment by Kegsay** [comment]
> Not quite sure why this got closed

Because the issue is:

> Mechanism for migrating portal rooms to plumbed rooms

to which the answer was:

> Doesn't ops syncing fix this for most of the users?

You're asking a different question about how to handle multi-bridged rooms, which is not what this issue is about. Multi-bridging in and of itself is not a bug, but how it is currently being used (in order to get ops and set names/topics) is sub-optimal because of what you describe.

**Comment by ara4n** [comment]
If you read my original comment this was entirely about multibridged rooms. My question continues to be: can we have a way to remove a portal (or route a portal alias to a plumbed room) if people want to migrate a room from portal to plumbed without getting lost in multibridge confusion?

**Comment by ara4n** [comment]
@kegsay: perhaps we can discuss this IRL on monday to try to converge on the same page rather than diverge...

**Comment by MilkManzJourDaddy** [comment]
*Ahmm*...  Looking at the case of Matrix⇿Freenode:
* The IRCOp's issued the I:line, not Channel Op's, who might be unaware.  
* Some channel Op's have banned the bridge/gateway, or default MXID⇿nickname mask, altogether.  
* Some use the IRC Portals to evade IRC bans.  
* Many IRC crossovers just use Matrix IRC Portals as a "bouncer" (BNC/ZNC) that logs. 
* Many are unaware of differences between how messages express on IRC, or customs/practices there.  
* When chan' Op's actively decide to allow the "Plumbed" instance, it's better...  
	* There is more moderation of what passes into their channel.  
	* More goodwill diplomacy between Matrix & IRC.  
	* Unified communities for projects, et cetera.  
	* Matrix room Admin's/Mod's can handle some issues, instead of chan' Op's appealing to IRCOp's/Matrix Dev's.
* It is probably better for just one "Plumbed" bridging instance, per IRC channel. 
* There are differences between how IRC works, and Matrix works.  Let Matrix Mod's understand the Matrix side.   
* This would eliminate issues like [Modify the admin settings for a bridge IRC room \#91](https://github.com/matrix-org/matrix-appservice-irc/issues/91), or requests to also bridge Portals into Slack, et cetera.  And, the workload is shifted onto the room Moderation/Admin'.

IMHO, here is what *could* be done, scripted, when IRC channel Op's permit the Plumbed bridge instance:  
* Change to alias of the Portal room, appending something like:  **\#[\_]<IRC-Net'>\_\#<IRC-chan'>-archive:<Matrix-HS>**, i.e. **\#freenode_#guardianproject-archive:matrix.org**; or perhaps instead of a  dash "-", a sigil/character that is allowed in Matrix Aliases, but not for IRC channel names.  
* (The users' MXIDs should remain joined, due to the room's ID, over the Alias).
* Add the original Portal alias to the newly Plumbed room.
* Issue a room message that the bridging of that IRC channel has been moved to Matrix room <insert Matrix alias>. (Optionally, also include the old Portal alias.  The user may click either.)   
* (kick)ban the (ro)bot and stop Matrix⇿IRC traffic. 
* Mute all users.
* Let the all resume in the native Matrix Plumbed room, and keep the archive-log in the Portal room.
* Done.

*Now if I still need to STFU/GTFO, I can delete this comment. (Or just edit out/rem' out this line.) :-|*

**Comment by Mikaela** [comment]
> My question continues to be: can we have a way to remove a portal (or route a portal alias to a plumbed room) if people want to migrate a room from portal to plumbed without getting lost in multibridge confusion?

Do I understand correctly that the request turns into: when room is plumbed, have the appservice remove the #_network_#whatever:example.net and add (or let the user add) it to the newly plumbed room where the user has PL100?

If so, it seems like a good idea to me removing the requirement of asking Kegan for PL100. Also the original comment and possibly issue title should be clarified. 

The issue that would still be there is that the users of the portal room would have to move by themselves, but that doesn't seem like an issue as IRC channel renames do happen. 

~~Alternative solution would possibly be forgetting plumped rooms entirely and instead inviting the user to portal room and sending a message to the IRC op asking if they would like to make the Matrix ID the room owner/founder (closest to PL100 at IRC).~~ won't work unless the bridge starts supporting ambiguous IRC services and checking ChanServ info and whatever different networks invent.

**Comment by MilkManzJourDaddy** [comment]
Perhaps this also refers to what I raise in [Mechanism for Forking Rooms, and Merging Rooms. \#859](https://github.com/matrix-org/matrix-doc/issues/859).  And thinking of both at the same time compounds the thought process.  

But, I've given it more thought, what I suggested above.  

While it might not be ideal to have more than one Matrix Plumbed into one IRC channel, it could happen.  And that would make doing the above, or reversing it, more complex.  

The process should be reversible, should IRC channel Operators decide to nix the bridging.  While that might be less likely if they liaison with Matrix Moderators, it is possible.   And, perhaps the bridge should retain the Portal aliases.

So, when IRC channel Operators allow their channel to be Plumbed to at least 1 Matrix room, perhaps:  
### In the companion Portal room:
* Mute all Matrix side MXIDs in the Portal room.  And, set the Power Level of new joiners to mute/below event PL.
* Stop Matrix⇿IRC traffic in the Portal room.  If necessary, (kick)ban the bridge (ro)bot.  
* Issue a room message, such as: "The bridging of this IRC channel now occurs in the following room; \#matrixroom:homeserver.tld.  Please continue there.  Archival logs will remain here."  That could be repeated, should the IRC channel be Plumbed into other Matrix rooms.  
*  Then, hopefully with little complaint, all activity would resume in the native Matrix Plumbed room, and the archive of the IRC log remains in the Portal room, with the Portal alias.
* Done.
---

### In the event that IRC channel Operators decide to remove the bridging into a Plumbed room...
In the room that had been Plumbed:
* Issue a room message, such as: "The bridging of this room into the \<IRC Network> IRC channel <\#channel> no longer occurs in this room.  See: \#\_IRC-Network\_\#IRC-Channel:homeserver.tld."   
### In the Portal Room:
* Redact the message referring to the formerly Plumbed room.
### If that formerly Plumbed room was the only one Plumbed...
In the Portal room:
* **un**mute all Matrix side MXIDs in the Portal room.  Allow Power Level zero to send room messages.  
* Resume Matrix⇿IRC traffic in the Portal room, reintroducing the bridge (ro)bot, if it had to be ejected.

**Comment by MilkManzJourDaddy** [comment]
Upon further reflection, users may want to see an uninterrupted log in the Portal rooms, despite how the IRC traffic is piped through the plumbing.  And it could change.  So...

---
When IRC channel Operators allow their channel to be Plumbed to at least 1 Matrix room:  
### In the companion Portal room:
* Mute all Matrix side MXIDs in the Portal room.  And, set the Power Level of new native MXID joiners to mute/below event PL.  Make certain that this can **not** be overridden, under nearly any circumstance, not even from IRC.  If necessary, affect the (ro)bot.
* In the place of the default text-box message for muted users:
	* Place a message, such as: "The bridging of this IRC channel now occurs in the following room(s): \#matrixroom:homeserver.tld.  Please continue there.  logging continues here."  Be certain that the alias in the text-box is clickable.
	* Should limited text-box display space, such as for mobile, be of concern, and if multiple Matrix rooms get the IRC channel Plumbed, alternatively a succinct text-box message could point to the Portal room topic, appended or prepended with the alias(es) of the Plumbed room(s).  i.e.
	 	* Text-Box Message: "Matrix⇿IRC Bridging is now in room(s) \<Room-Alias|"listed in the topic"\> \[See also: [The FAQ/Wiki](https://github.com/matrix-org/matrix-appservice-irc/wiki/)\]."  
	 	*  Topic \<append|prepend\> "The bridging of this IRC channel now occurs in the following room(s): \#matrixroom:homeserver.tld.  Please continue there.  logging continues here."   Be certain that the IRC side cannot affect this part of the topic.
*  Then, hopefully with little complaint, all Matrix side activity would resume in the native Matrix Plumbed room.  The Portal room continues logging, uninterrupted, regardless of Piping/Plumbing changes.  The Portal/Bridge retains the Portal alias.
* Done.
---

### In the event that IRC channel Operators decide to remove the bridging into a Plumbed room...
In the room that had been Plumbed:
* Issue a room message, maybe m.notice, such as: "The bridging of this room into the \<IRC Network> IRC channel <\#channel> no longer occurs in this room.  See: \#\_IRC-Network\_\#IRC-Channel:homeserver.tld."  
* Make certain that such a message, or a separate message, gives notice/pings/mentions/highlights all in the formerly Plumbed room, with sufficient Power Level to edit the Topic.  Something like IRC wallchops.  Have them edit out any Topic reference to the formerly piped IRC traffic.  If nothing like /wallchops exists on Matrix, perhaps it should.  
### In the Portal Room:
* Edit/Redact the text-box message/Topic, removing references to the formerly Plumbed room.
### If that formerly Plumbed room was the only one (remaining to be) Plumbed...
In the Portal room:
* Redact the any prepended/appended part of the topic referring to the formerly Plumbed room.
* **un**mute all Matrix side MXIDs in the Portal room.  Allow Power Level zero to send room messages.

**Comment by MilkManzJourDaddy** [comment]
Whether or not they are IRC channel Op's or IRCOp's...  Certainly any crossover from IRC would want to try out [Portal Rooms](https://github.com/matrix-org/matrix-appservice-irc/wiki/Permissioning-in-Portal-vs-Plumbed-rooms#portal-rooms), if the IRC channel they like is not already [Plumbed](https://github.com/matrix-org/matrix-appservice-irc/wiki/Permissioning-in-Portal-vs-Plumbed-rooms#plumbed-rooms).  I've brought over some people from IRC.  

But trying out Admin'/Mod'/Custom-PL powers seems to be a separate issue than the Portal/Plumbed paradigm.  I'm willing to bet that is part of the issue.  But they can learn in other rooms.  Some Admin' might even temporarily give them up to Matrix ≦PL99 in something Plumbed like [#matrix-irc-test:matrix.org](https://riot.im/app/#/room/#matrix-irc-test:matrix.org:matrix.org).  And on the other side of the bridge, seen in **read-only** Portal room: [#freenode_#matrix-irc-test:matrix.org](https://riot.im/app/#/room/#freenode_#matrix-irc-test:matrix.org:matrix.org), but actually, `Freenode #matrix-irc-test`, temporarily give them Op's, powers, less-than Founder.  

Then, they would have the experience to Admin' any Matrix room they Plumb.  Or they could just jump right into the deep end of the pool, and ask for support in [#matrix:matrix.org](https://riot.im/app/#/room/#matrix:matrix.org:matrix.org) or [#matrix-irc:matrix.org](https://riot.im/app/#/room/#matrix-irc:matrix.org:matrix.org).

**Comment by ara4n** [comment]
Having IRL'd with @kegsay we're now on the same page:
 * as @Mikaela says, being able to get ops on portal rooms solves much of this (once this is rolled out), except...
 * if folks have independently created separate plumbed and portal rooms whilst getting familiar with using Matrix for an existing community, and then want to somehow kill the portal room in favour of the plumbed one to avoid ugly doublebridging. this is essentially a request for being able to merge rooms though, and a separate bug: https://github.com/vector-im/riot-web/issues/2299
 * Portal rooms where the user has gained ops are still unable to set room name, delegate power by editing power levels, or change history visibility(!) These are all reasons why folks might then go and create a plumbed room anyway, and suffer doublebridging ugliness. We can fix this however by changing the default power levels for portal rooms. I'll file this as a new bug.

@MilkManzJourDaddy: i get that you are trying to help, and that buried somewhere in your comments are some good ideas. however, your way of presenting and discussing them overall ends up being entirely counterproductive over all. This bug is now drowned in huge rambling comments which take ages to decrypt and overall waste our time and anyone else's who's reading it. In short, it seriously damages the usefulness of an otherwise useful resource (be it Github or a Matrix room etc). So, please either keep it concise, focused and free of subjective sidebars or we'll have to ban you across the board.

**Comment by ara4n** [comment]
@Kegsay i'm seeing more and more people getting bitten by this - e.g. the confusion in https://twitter.com/matrixdotorg/status/866650347028303873 with #clojure on FN, and just now this came up:

cjd✨ | Matthew: Is there any ETA on being able to get control of #freenode_# channels ?
Matthew | cjd✨: yes. i believe that as of today if you have ops on the freenode side you should also get ops on the Matrix side (although need to check)
cjd✨ | cool
Matthew | alternatively you may need to bridge it explicitly (and then have ops propagate)
cjd✨| seems it did not work
so I've got #cryptpad:matrix.org and #freenode_#cryptpad:matrix.org and I guess there's really no way to unify them anyway, even if I get 50% power over #freenode_#cryptpad:matrix.org
Matthew | yeah, the double bridging problem is a mess that needs more thought :(
cjd✨| Maybe the thing to do is just allow people who have authorized bridges opt to shut down the #freenode_#xxx bridges on request ?
then that name becomes an alias to their authorized bridged channel
it solves the problem in the short term :)

The latter suggestion sounds quite interesting to me (and is back on the original track of this bug).

So: how come freenode portal rooms don't seem to bridge ops?
And, in the absence of being able to merge rooms, how about we let authorized plumbed rooms vape portal rooms, pointing the portal alias into the plumbed room, to try to avoid double-bridging?

**Comment by Kegsay** [comment]
> how come freenode portal rooms don't seem to bridge ops

They do. I just tested it to be sure.
```
IRC:
* kegan gives channel operator status to kegan[m]

Matrix:
@appservice-irc:matrix.org changed the power level of @kegan:matrix.org from Default (0) to Moderator (50)
```

De-opping works as well.

**Comment by Kegsay** [comment]
> in the absence of being able to merge rooms, how about we let authorized plumbed rooms vape portal rooms, pointing the portal alias into the plumbed room, to try to avoid double-bridging?

We don't. The correct solution is to do #408. Vaping a portal room and replacing it with a plumbed room can create a schism between IRC and Matrix users, making it impossible for regular Matrix people to join particular IRC channels (because the room no longer exists and is at the whim of whoever controls the plumbed room). At this point we cease to be a bridge to all channels and people cannot treat the bridge as a bouncer, as there will be channels which just plain don't work.

Nearly if not all reasons given for plumbing are to add Matrix-specific information like the room name / avatar / alter history visibility. These things are things we should let authorised Matrix users do. They shouldn't be able to modify `join_rules` to make it impossible to join a channel. I have *zero* desire to have to step in and moderate 2 sides of a community when they end up with conflicting room rules which cannot be harmonised by the bridge.

**Comment by locutis-of-borg-1999** [comment]
then why bother with plumbs at all    make peeps forever start by getting everyone registered on freenode and get authorization from irc authorities before bridging for a bounce logger    irc people dont give a shift about ports or plumbs   butt that guy u banned said to mute the ships port room and suggest also redirect to the plumb room like be in both butt only post in 1  sounded simple butt for all the posts he took to work it out

**Comment by ara4n** [comment]
@Kegsay okay, fair enough.

**Comment by kroeckx** [comment]
> The correct solution is to do [element-hq/element-web#408](https://github.com/element-hq/element-web/issues/408).

That link seems wrong. Can you point to the right place or clarify?
