### ISSUE TITLE
Troubles setting the IRC bridge

### ISSUE THREAD

**Issue by ArchangeGabriel** [matrix-org/matrix-appservice-irc#398]
Hi,

I’m trying to configure the IRC bridge on my HS, and I must say it’s quite hard. For instance, `http://where.the.appservice.listens` is never explained, I had to figure out that the app binds on all interfaces (which is quite an issue for me, but there is already #95 for that).

Nevertheless, I’ve managed to write a configuration file (which probably won’t work/do what I want it to do), but then I fail to register it:
```
$ sudo node /usr/lib/node_modules/matrix-appservice-irc/app.js -r -f /etc/synapse/irc.yaml -u "http://localhost:9999" -c /usr/lib/node_modules/matrix-appservice-irc/config.yaml
Loading config file /usr/lib/node_modules/matrix-appservice-irc/config.yaml
Fatal TypeError: Cannot read property 'visibility' of undefined
    at _toServer (/usr/lib/node_modules/matrix-appservice-irc/lib/main.js:23:37)
    at /usr/lib/node_modules/matrix-appservice-irc/lib/main.js:77:22
    at Array.forEach (native)
    at Object.<anonymous> (/usr/lib/node_modules/matrix-appservice-irc/lib/main.js:76:26)
    at next (native)
    at tryCatcher (/usr/lib/node_modules/matrix-appservice-irc/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/usr/lib/node_modules/matrix-appservice-irc/node_modules/bluebird/js/release/generators.js:97:49)
    at Object.generateRegistration (/usr/lib/node_modules/matrix-appservice-irc/node_modules/bluebird/js/release/generators.js:201:15)
    at Cli.generateRegistration (/usr/lib/node_modules/matrix-appservice-irc/app.js:39:14)
    at Cli._generateRegistration (/usr/lib/node_modules/matrix-appservice-irc/node_modules/matrix-appservice-bridge/lib/components/cli.js:171:46)
    at Cli.run (/usr/lib/node_modules/matrix-appservice-irc/node_modules/matrix-appservice-bridge/lib/components/cli.js:117:14)
    at Object.<anonymous> (/usr/lib/node_modules/matrix-appservice-irc/app.js:49:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
```

This is on ArchLinux, `npm` version is `4.4.1` and `nodejs` is `nodejs-lts-argon 4.8.0`.

**Comment by ara4n** [comment]
This sounds like you've deleted the dynamicChannels section from the 
config, and the app assumes that it exists.  If you really don't want to 
support bridging arbitrary channels on demand, you'll want something like...

       dynamicChannels:
         enabled: false

...in the config.

In terms of how fiddly this is to set up: agreed that there are some 
stumbling points currently.  If you can flag up where they are or PR 
improvements to the README it'd be much appreciated.  Thanks for 
sticking with it.

**Comment by ArchangeGabriel** [comment]
Yes, I removed a lot of things from the config file, I must it’s not very clear whether having the fields is required or not, especially when default are listed. What are this default referring to then (I assumed that they were hardcoded in the app, but then why is listing the default value required?)? The one in the sample file? But they don’t even match for some options…

Anyway, adding this to the file made it success for the registration. I’ll try to enhance the README when I will have everything working on my side.

**Comment by ArchangeGabriel** [comment]
Hum… How is password protected channel support supposed to work (I’ve seen https://github.com/matrix-org/matrix-appservice-irc/pull/93, but don’t understand it)?

Just:
`/join #irc_freenode_$CHANNEL:homeserver.name <password>`
?

**Comment by ara4n** [comment]
yes, i believe so.

**Comment by ArchangeGabriel** [comment]
Hum… I don’t have an admin control room with the bridge (or, more exactly, I have one for another network, and then a second one for that other network appeared — I’ve thus left the first one, thinking that this could be because of some config changes), and when I try this in another room it just send the content of this command to the room.

**Comment by ArchangeGabriel** [comment]
Seems like I’m having issues with dynamicChannels. Whatever I ask to join (using `/join #network_#channel:home.server`, since the `!join network #channel` syntax does not seems to be accepted), I’m invited by `@appservice-irc:home.server` to an empty channel with just me and him.

The only thing I’ve been able to do is use an explicit mapping for a room created before hand, then upon starting the IRC bridge it would recognize the room, connect it properly and also invite me in a Bridge Status room (which never happens with only dynamic)…

**Comment by ArchangeGabriel** [comment]
So, maybe I should describe exactly what I’m trying to do. I want to setup the IRC bridge with the following requisites:

– Connect to one (or two, but no need for dynamic here) channels that live on irc.domain.name. I don’t want those to be federated (i.e. only the users registered on my HS, which is me + eventually some other people, should have access to these rooms).
– Connect to one channel on irc.freenode.net, which also happens to be password protected (so I don’t want anyone else to be able to join this room, even other people on my HS). Also, I might want to be able to join more channels later on (most of which I expect to be fine with federation/allowing access to anyone — well, they’re on matrix.org anyway), but also have the possibility to leave some of them at any time and *delete* every related data from my HS when I do so. I’d probably not join them through `matrix.org`, because I want my username on IRC to be `$DISPLAY` and the one of IRC users to be `$NICK (IRC)`, which is probably not the configuration of `matrix.org`, at least for the first one.

In all cases, I want to be able to access every message that arrives when I’m not connected on my phone or desktop, and also keep an history of the channel (that’s why I want to use IRC through Matrix). I don’t want to have a bot sitting in the channels, but I kinda expect myself to always be listed in the channel connected users (I mean, I must somehow be listed there to receive messages anyway, but it’s even a feature for me that other people don’t see when I really connect/disconnect). I want to see every connected IRC users at a given time, and have leaving/joining messages in the conversation history.

Any help configuring all of that would be greatly appreciated (especially having a minimal conf file)!

Here is my current attempt, non-working per previous comment:
```
homeserver:
  url: "http://localhost:8008"
  domain: "domain.name"

ircService:
  servers:
    irc.domain.name:
      name: "SomeName"
      networkId: "SomeName"

      port: 6697
      ssl: true
      sslselfsign: false

      sendConnectionMessages: true

      botConfig:
        enabled: false
        nick: "MatrixBot"
        joinChannelsIfNoUsers: true

      privateMessages:
        enabled: true
        federate: false

      dynamicChannels:
        enabled: true
        createAlias: true
        published: true
        joinRule: public
        federate: false
        aliasTemplate: "#somename_$CHANNEL"
        whitelist:
           - "@myuser:domain.name"

      membershipLists:
        enabled: true
        floodDelayMs: 10000

        global:
          ircToMatrix:
            initial: true
            incremental: true

          matrixToIrc:
            initial: true
            incremental: false

      matrixClients:
        userTemplate: "@SomeName_$NICK"
        displayName: "$NICK (IRC)"

      ircClients:
        nickTemplate: "$DISPLAY"
        allowNickChanges: true

        idleTimeout: 0
        lineLimit: 3

    chat.freenode.net:
      name: "Freenode"
      networkId: "Freenode"

      port: 6697
      ssl: true
      sslselfsign: false

      sendConnectionMessages: true

      botConfig:
        enabled: false
        nick: "MatrixBot"
        joinChannelsIfNoUsers: true

      privateMessages:
        enabled: true
        federate: false

      dynamicChannels:
        enabled: true
        createAlias: true
        published: true
        joinRule: public
        federate: false
        aliasTemplate: "#freenode_$CHANNEL"
        whitelist:
           - "@myuser:domain.name"

      membershipLists:
        enabled: true

        floodDelayMs: 10000

        global:
          ircToMatrix:
            initial: true
            incremental: true

          matrixToIrc:
            initial: true
            incremental: false

      matrixClients:
        userTemplate: "@Freenode_$NICK"
        displayName: "$NICK (IRC)"

      ircClients:
        nickTemplate: "$DISPLAY"
        allowNickChanges: true

        idleTimeout: 0
        lineLimit: 3

  databaseUri: "nedb://etc/synapse/data"

  # Configuration for the provisioning API.
  #
  # GET /_matrix/provision/link
  # GET /_matrix/provision/unlink
  # GET /_matrix/provision/listlinks
  #
  provisioning:
    # True to enable the provisioning HTTP endpoint. Default: false.
    enabled: false
    # The number of seconds to wait before giving up on getting a response from
    # an IRC channel operator. If the channel operator does not respond within the
    # allotted time period, the provisioning request will fail.
    # Default: 300 seconds (5 mins)
    requestTimeoutSeconds: 300

  # WARNING: The bridge needs to send plaintext passwords to the IRC server, it cannot
  # send a password hash. As a result, passwords (NOT hashes) are stored encrypted in
  # the database.
  #
  # The path to the RSA PEM-formatted private key to use when encrypting IRC passwords
  # for storage in the database. Passwords are stored by using the admin room command
  # `!storepass server.name passw0rd. When a connection is made to IRC on behalf of
  # the Matrix user, this password will be sent as the server password (PASS command).
  passwordEncryptionKeyPath: "/etc/synapse/passkey.pem"
```

The option I’m especially not sure about are `joinChannelsIfNoUsers`; `createAlias`, `published`, `joinRule` and `whitelist` (in `dynamicChannels`); `floodDelayMs`; `incremental in matrixToIrc` and `idleTimeout`. Also everything in the `provisioning` part, and I’m not sure how password works (when should I register/enter a password for IRC?).

But what is sure, is that this configuration doesn’t seems to work (see above).

What is especially not clear is which option are mandatory, which aren’t, and what “defaults” means (again, see above comments).

**Comment by ara4n** [comment]
i think the best bet on this is going to be to talk it through with someone on #irc:matrix.org or #bridges:matrix.org.  The core team is drowning a bit currently, but the wider community can certainly help with this.  The key thing you seem to be missing is that you enter commands like `!join` into the 1:1 admin room with the bridge.  If you've gone and closed your admin room, then you'll need to rejoin it first or otherwise trigger it to talk to you again.

**Comment by ArchangeGabriel** [comment]
Hum, I see, except that I’ve never been invited to any admin room with dynamicChannels set. The only case it happened is when I specified no dynamicChannels and an explicit mapping. Is there any explanation somewhere on getting into the admin room? I’ll try to ask on the mentioned room ASAP, but that might not be possible before next WE.

**Comment by Kegsay** [comment]
This issue tracker is not a support forum. Please ask questions on #irc:matrix.org or #bridges:matrix.org and someone will get back to you. If there are actionable issues you believe need to be addressed with the bridge, then please make an issue for each item.
