### ISSUE TITLE
We don't relay IRC connection limits to the Matrix side

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-appservice-irc#401]
So it appears in Matrix as if we're happily joined the channel, with no evidence that a) your bot hasn't connected, b) nobody can hear you.  Meanwhile we relay I->M messages as normal, which is far from ideal - similar to https://github.com/matrix-org/matrix-appservice-irc/issues/212

**Comment by Kegsay** [comment]
There is no error code for this, so we'll need to manually grep the error text to see if we're hitting a connection limit, and if so, relay this to the admin room.

**Comment by Mikaela** [comment]
Would treating KILL as error work or does it happen without errors or anything that the admin room should be aware of?

**Comment by Half-Shot** [comment]
https://github.com/matrix-org/matrix-appservice-irc/pull/639 kicks the user if they fail to join due to connection limits with a reason telling them to try again later. It's far from perfect but it should make freenode happy.

**Comment by Half-Shot** [comment]
I think this is good enough for now.
