### ISSUE TITLE
Ability to trigger a reconnection from the admin room

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-appservice-irc#402]
We surely need a ! command in the admin room to tell the bridge to try to reconnect me to the network.  e.g. my connection to gimpnet appears to be stuck somehow (after we hit connection limits), but i have no way to tell the bridge to try to reconnect me

**Comment by Kegsay** [comment]
The bridge will keep trying to reconnect you if your connection is lost. I have no desire to add in a manual way to do this, as I don't want to open up a spam vector. Frequent connection attempts from a banned user on Freenode has got the entire bridge banned before, I'm not willing to let this happen again.

**Comment by itsrachelfish** [comment]
@Kegsay What if somebody used the "quit" command in the bridge room? Or what if somebody left the bridge room? How do they reconnect to the server?

**Comment by Half-Shot** [comment]
@itsrachelfish Rejoin the rooms that you were kicked from, a rejoin will cause a reconnection.
