### ISSUE TITLE
TeleIRC/Telegram is unhappy with the uploaded content format

### ISSUE THREAD

**Issue by Mikaela** [matrix-org/matrix-appservice-irc#406]
Via https://github.com/matrix-org/matrix-appservice-irc/issues/258#issuecomment-289063235 which also has longer version.

Currently the format to Telegram via TeleIRC is `*Michaela: uploaded an image: screenshot.9.jpg (71KB) - https://matrix.org/_matrix/media/v1/download/disroot.org/mtewvcPGqPsWmYCQmZKEhdQW*` and Telegram treats \* as part of the URL resulting to 404 error and the content not being downloaded/previewed.

My suggestion would be closing the link into `<>` resulting to `*Michaela: uploaded an image: screenshot.9.jpg (71KB) - <https://matrix.org/_matrix/media/v1/download/disroot.org/mtewvcPGqPsWmYCQmZKEhdQW>*` which Telegram appears to understand and which I think to be some kind of a standard (at least it has been Supybot default for years). This way I think the dash in the middle could also be dropped.

![screenshot 12](https://cloud.githubusercontent.com/assets/831184/24304180/2d70cf00-10c1-11e7-97a3-4b3729391f55.jpg)

**Comment by Kegsay** [comment]
@t3chguy did this.
