### ISSUE TITLE
Give users a help message on bot room join

### ISSUE THREAD

**Issue by Cadair** [matrix-org/matrix-appservice-irc#407]
It would be useful if when joining a room with the bot (i.e. `@appservice-irc:matrix.org`) if it sent you a message saying something like "type !help to see what commands the bot supports".

**Comment by Kegsay** [comment]
We already do this when the bot initiates a conversation with a Matrix user and creates a new PM room. The message is:

> You've joined a Matrix room which is bridged to the IRC network $domain, where you are now connected as $nick. This room shows any errors or status messages from IRC, as well as letting you control the connection. Type !help for more information

This message isn't displayed if the Matrix user is the one who starts the conversation.
