### ISSUE TITLE
Cannot interact with @appservice-irc:matrix.org after homeserver reinstall

### ISSUE THREAD

**Issue by NickHu** [matrix-org/matrix-appservice-irc#415]
I had previously had a homeserver at `nickhu.co.uk`, where I was able to set up a connection to freenode with my nick `NickHu`. Since then, I've had to reinstall my homeserver fresh (same domain but fresh db), but I forgot to issue a `!quit` on the old homeserver, and now `@appservice-irc:matrix.org` doesn't join chats, and furthermore it seems like the connection from freenode still lingers from the previous install - despite that homeserver being long dead. As a consequence, I can't reclaim my freenode nick either.

**Comment by Kegsay** [comment]
Message me and I can remove this connection.

**Comment by NickHu** [comment]
It seems to have magically resolved so that I'm connected to freenode again, with the same bridged nick as before, so all seems to be well apart from being unable to interact with `@appservice-irc:matrix.org`

**Comment by Kegsay** [comment]
Make a new private chat with `@appservice-irc:matrix.org` then do `!nick` and it should be fine,

**Comment by Kegsay** [comment]
Closing this. PM me if this is still a problem or go to `#irc:matrix.org` or `#matrix-irc` on Freenode. Thanks.

**Comment by NickHu** [comment]
I'm still having the same problem, and now none of my matrix -> freenode messages are working. I'm on #matrix-irc, some support would be appreciated

**Comment by PureBasic** [comment]
It happened to me also. I created another account to check if the problem was the service or my account. The new account allowed me to interact.
So I logged back to my first account and it apparently solved the issue. 

So yeah, old school turn it off and back on!
