### ISSUE TITLE
Membership list can desync

### ISSUE THREAD

**Issue by TheLastProject** [matrix-org/matrix-appservice-irc#425]
On OFTC, an IRC server where memberlist syncing is enabled, a few users that aren't in the channel anymore are still listed in the memberlist. I do not know how this desync happened or when it started happening, but it affects `bill-auger_` (who used to connect through IRC and thus got the Matrix nick `@_oftc_bill-auger_:matrix.org`) in `#_oftc_#pext:matrix.org`, for example.

I don't have more information than this, but if there's any way I could help debug I am happy to assist.

**Comment by Ralith** [comment]
This might be #71.

**Comment by TheLastProject** [comment]
Thanks for the link, but I don't think it is. Normally, user and user_ nicks tend to be caused from disconnections. In this case, it seems more like the bridge missed a disconnection event.

**Comment by Ralith** [comment]
If an IRC user changes their nick and leave the channel, there will be no disconnect or leave message for the old nick, so it will remain indefinitely.

**Comment by Kegsay** [comment]
@Ralith is absolutely correct, this is #71 rather than a random missed QUIT. Closing as dupe for now - @TheLastProject if you have evidence to the contrary please feel free to add to this issue.

**Comment by erdnaxeli** [comment]
This can happens too if the connection with the server IRC is lost. When the bridge connects back to the IRC server, old users which were disconnected too are not removed.

I understand the bridge do not see the /quit of those users, so it do not remove them. But on reconnection it should list users and remove the missing one (if users syncing is activated ofc).

**Comment by Kegsay** [comment]
We already do this when the bridge restarts: https://github.com/matrix-org/matrix-appservice-irc/blob/b4a35c37b3908bee61d4a34b2238fc05179eeb92/lib/bridge/MemberListSyncer.js#L351

**Comment by erdnaxeli** [comment]
Yep, but it should be done en reconnection too, not only restart.
