### ISSUE TITLE
Wrong anouncement on IRC-side when posting audio-files to Matrix room.

### ISSUE THREAD

**Issue by scrdcow** [matrix-org/matrix-appservice-irc#429]
I tried to post various audio-files to a Matrix room bridged to IRC. On the IRC-side it did not post a '/me' with a link, only the filename. Tried it both over matrix.org freenode bridge and on my own matrix-appservice-irc instance on various channels. The following tested filetypes created misbehaviour. mp3, ogg, mod, sid, flac, wav. So it seems to have something to do with 'audio' MIME type or such since all other various files I tried have been working fine.

Reproduction:
- Try to post some audio-file on a Matrix room that is bridged to IRC.

Version:
- The freenode bridge on matrix.org, dunno what version it uses.
- On my side: matrix-appservice-irc 0.7.2  with inspircd 2.0.17-1+deb8u2 on private network and matrix-synapse-0.20.0, if it matters.

**Comment by Kegsay** [comment]
Probably because the bridge doesn't know how to handle audio `msgtypes`. https://github.com/matrix-org/matrix-appservice-irc/blob/master/lib/models/MatrixAction.js#L11

**Comment by jansol** [comment]
Just ran into this in two separate rooms, causing confusion that escalated way beyond what's necessary in both cases.

**Comment by Half-Shot** [comment]
This was fixed, so closing.
