### ISSUE TITLE
Enable ops syncing on matrix.org networks

### ISSUE THREAD

**Issue by Mikaela** [matrix-org/matrix-appservice-irc#438]
I think I might be annoying with asking about the status with ops syncing so often and there is also issue of not having tracking issue for it, so I am opening this one. I also think issue https://github.com/matrix-org/matrix-appservice-irc/issues/408 depends on this and possibly through it https://github.com/matrix-org/matrix-appservice-irc/issues/383 .

* * * * *

* [ ] espernet
* [ ] foonetic
* [x] freenode
* [x] gimpnet
* [ ] moznet
* [ ] oftc
* [x] rizon
* [ ] snoonet

* * * * *

Gimpnet was the first network where the ops syncing was enabled and after that, if I recall correctly, there was talking about possibly enabling it on Snoonet next, but I don't remember if that happened yet.

(Almost) everyone naturally wants to see it enabled at freenode, but I think there was talk about it needing to be tested more throughly before being enabled on freenode which is the biggest network and where something going wrong might cause issues.

**Comment by Kegsay** [comment]
Freenode is enabled and even seems to work.

**Comment by Mikaela** [comment]
Doesn't every network have this after this long time?

**Comment by Half-Shot** [comment]
As far as I'm aware, yup.
