### ISSUE TITLE
Long messages should be uploaded as UTF-8

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/matrix-appservice-irc#439]
When the IRC bridge sees a long message from matrix it uploads it to the media repository. It currently uploads UTF-8 with a content type of `text/plain`, but the default charset used when none is specified is `us-ascii` causing browsers (and everything else) to use the wrong charset and so display garbled characters.

The bridge should upload with a content type of `text/plain; charset=utf-8`

**Comment by Kegsay** [comment]
Dupe https://github.com/matrix-org/matrix-appservice-irc/issues/360
