### ISSUE TITLE
Suppress leave and join messages

### ISSUE THREAD

**Issue by gbraad** [matrix-org/matrix-appservice-irc#443]
Is it possible to suppress leave and join messages? In certain rooms the ratio of these notifications can be higher than actual messages.

**Comment by Kegsay** [comment]
This depends on your client. Please open an issue on whatever client you happen to be using:
 - [riot-web](https://github.com/vector-im/riot-web)
 - [riot-android](https://github.com/vector-im/riot-android)
 - [riot-ios](https://github.com/vector-im/riot-ios)
 - [other clients](http://matrix.org/docs/projects/try-matrix-now.html)

**Comment by gbraad** [comment]
Ah, so it is client based. In this case `riot-android`. Will file an issue. Thanks

**Comment by Kegsay** [comment]
Yep, I use riot-android too and I appreciate it's annoying. Sorry about that.
