### ISSUE TITLE
metrics: track active connections

### ISSUE THREAD

**Issue by kegsay** [matrix-org/matrix-appservice-irc#446]
We currently monitor a "remote user count" for connections to IRC networks. We should make use of the user activity graphs @leonerd has already set up and track 1 hour / 1 day / etc counts for these users.

I suspect this will be valuable when we want to fine tune idle connection timeouts values for https://github.com/matrix-org/matrix-appservice-irc/issues/388 - currently we set this to 30 days but we have not even the slightest idea of how many users this will then disconnect.

The numbers produced by these graphs will always be underestimates (that is, they will say there are fewer people using connections when the real number is higher) because we have no way to distinguish lurkers who do not say anything ever vs genuine idle connections. It's a start though.

**Comment by leonerd** [comment]
If we're going to have one of these in IRC, then one thing I would like to apply across all of the bridges is some disk-based persistence of activity times. The times are currently only stored in memory about every user, so on a restart they're all reset again. It then takes an hour before the HAU graph is correct, a day before the DAU, etc etc. This ties in with other unrelated thoughts that also want longterm-persisting data on disk. I suspect the solution will either be SQLite or BDB or somesuch...

**Comment by Half-Shot** [comment]
We now do have stats for this, and we also use the metrics to kick idle users periodically.
