### ISSUE TITLE
Matrix.org does not enforce IRC +m (mute)

### ISSUE THREAD

**Issue by hackers-terabit** [matrix-org/matrix-appservice-irc#453]
When a matrix user joins a #room in IRC that is moderated,moderates expect control over who speaks in a channel and who is allowed in the channel/room. 

+m channel flag in IRC prevents users from speaking(stands for mute),I use this control to selectively decide who gets to speak in a channel.

Matrix however allows matrix users to see each other messages sent to an IRC room even when the room is set to +m. 

This is unacceptable since it effectively overrides our controls. We treat matrix and other webshells as IRC  clients not as an independently moderated rooms that happen to send messages to irc channels outside of irc channel operators oversight and moderation.

Since this bug effectively bypasses our most basic moderation control,we have been forced to ban matrix.org users from our irc channel.

We truly welcome matrix users and hope the development team,being aware of the limits and nuances of moderating IRC channels considers this to be a very serious bug and fixes it to enable a more complete IRC integration.

**Comment by Kegsay** [comment]
There's currently no way for the bridge to enforce something like `+m` retroactively, only proactively by looking at which nicks can speak and then modifying `m.room.power_levels` accordingly.

It can't do it retroactively because it isn't on the critical path for message sending in Matrix, and hence cannot return an error to the client when they attempt to send a message. Provided muting is implemented as a user mode (such that the bridge can trivially map this to a Matrix user) rather than say a list of hostmasks (which the bridge cannot reliably map to Matrix users), this should be doable.

**Comment by hackers-terabit** [comment]
@Kegsay fyi, if a room has +m only +v users can speak,so if a room has +m set on irc,the matrix room should also disable speaking for everyone until +v is set for specific users

**Comment by Kegsay** [comment]
Should be doable, given we already check for usermodes for +o. Is it exclusively +v only able to speak, or are +o also allowed?

**Comment by hackers-terabit** [comment]
@Kegsay +o are allowed to speak as well. I should also mention +q which quiets a user (in any channel not just +m) however it like with +m is overriden by +v. Essentially +m takes a whitelist approach by muting everyone,many channels don't have it set,the default is to use +q (blacklist/reactive approach). 

In our case we are forced to use the +m proactive approach since we make it a priority to allow unregistered users including matrix users. (Low entry barrier means more bots,spam,trolls)

ty again for taking being willing to fix this.

**Comment by Kegsay** [comment]
Okay, if `+o` can speak then we can do this. If they couldn't, we'd have problems. So the final algorithm looks like:
 - On startup, check for `+m`ness of all channels. Also listen for it toggling on and off after startup.
 - Is the channel `+m`? If yes:
    * Get a list of nicks which are `+v` and/or `+o` (or higher, according to `PREFIX`)
    * Change the power levels in the matrix room such that:
      * By default no one can speak (`events_default` > 0)
      * Users who have `+o` or higher are given moderator levels (50) - we already do this but this is an optional thing, we'd need to enforce it more generally in this specific case.
      * Users who have `+v` get some power level > 0 (e.g 1) so they can send events into the room.
 - Is the channel `+m`? If no:
    * Reset `events_default` back to 0.

This can be implemented using 2 listeners probably. The first simply listens for `+v` and gives the target a power level of 1, and removes that on `-v`. We can do this today in config.yaml by setting the appropriate [modePowerMap](https://github.com/matrix-org/matrix-appservice-irc/blob/master/config.sample.yaml#L93) entry. Separately, we listen for chanmode `+m` and change the `events_default` from 0 to 1, so by default no one matrix-side can speak. Provided we already bridge ops (`+o`) then this should simply work.

This doesn't actually sound too hard now. We'd still need to explicitly check for `+m` on startup, but iirc I think we already do request all chanmodes but just discard the ones we don't understand, so it should just be an if statement. Modifying difficulty appropriately, though I'm going to be away for the next few weeks so I won't have a chance to tackle this :(

**Comment by hackers-terabit** [comment]
That sounds perfect. Thank you.

**Comment by hackers-terabit** [comment]
@Kegsay any update?

**Comment by Kegsay** [comment]
I've got a patch working on a branch, but I need to fix #385 first otherwise native IRC users who have permission to speak on the channel will be unable to speak on Matrix as we do not bridge that yet.

**Comment by Kegsay** [comment]
https://github.com/matrix-org/matrix-appservice-irc/pull/465

**Comment by Kegsay** [comment]
Patch has landed on `develop` - it'll take a while (days) for it to be deployed on the matrix.org networks as it goes through further testing. Will update this issue when this is done.

**Comment by hackers-terabit** [comment]
@kegsay thank you so much. Great work.

**Comment by Kegsay** [comment]
This has landed on the Freenode bridge.
