### ISSUE TITLE
Hide WebRTC bots on IRC

### ISSUE THREAD

**Issue by afranke** [matrix-org/matrix-appservice-irc#466]
When someone starts a call, a bot joins the room. That bot has a ghost on the IRC side, which is unnecessary. The bridge could “filter it out”.

**Comment by Mikaela** [comment]
I think this could possibly be called as duplicate of https://github.com/matrix-org/matrix-appservice-irc/issues/47 which would be a better (or the) solution.

**Comment by Kegsay** [comment]
The bridge doesn't know it's a bot, needs additional info from Matrix.

**Comment by Half-Shot** [comment]
Closing this as I don't think this is an actionable item. Separately, the verto bridge isn't in use anymore.
