### ISSUE TITLE
Why do nicks require beginning with a letter?

### ISSUE THREAD

**Issue by Spydar007** [matrix-org/matrix-appservice-irc#467]
[BridgedClient.js dictates that nicks must start with a letter](https://github.com/matrix-org/matrix-appservice-irc/blob/master/lib/irc/BridgedClient.js#L489). Is there a technical reason for this? It doesn't appear so, since commenting it out seems to work fine. This block means we cannot have nicks beginning with any of the special characters.

Any of the characters in the block above (dictated in RFC 2812 §2.3.1) can be used to begin a nick, except `-` and 0-9.

**Comment by Kegsay** [comment]
Ah, the earlier RFC 1459 didn't include special characters, but I see that RFC 2812 does include special characters, so that can be changed. Can't start with `-` or numbers though as you state.

**Comment by Kegsay** [comment]
There is no technical reason for it.

**Comment by mweinelt** [comment]
I wouldn't say that this is a quick win per se. It requires handling of the 432 numeric, if the network does not support it.

```
NICK 4foo                                                                                                                                                                                                                                                               :guybrush.hackint.org 432 somenick 4foo :Erroneous Nickname
```

**Comment by Kegsay** [comment]
We already handle that numeric when people issue `!nick`.

**Comment by TheButterZone** [comment]
One of my grouped Freenode nicks starts with a {

"must start with a letter"
