### ISSUE TITLE
Handle redacts

### ISSUE THREAD

**Issue by Mikaela** [matrix-org/matrix-appservice-irc#473]
I think that if a media file is redacted, the bridge should also remove the copy of it that it has linked to IRC.

I don't know how this should be done with long pastes as the Matrix user isn't even aware when their message gets pastebinned. Maybe the appservice could tell about the paste in the admin room and when redacting warn that to get the paste removed, they will need to redact the other lines too and possibly link to the paste?

**Comment by Kegsay** [comment]
Redaction of media is a Matrix thing, not an IRC bridge thing. E.g I send an image, I redact it, my HS invalidates the MXC URI. IRC users click on the link, it 404s.

I don't think we should do redaction of pastebinned messages either. We fundamentally cannot redact text we have sent to IRC. The fact that we *sorta* can redact multi-line messages which have been pastbinned doesn't really help explain to the user that in most cases we cannot redact the message.

Closing this, but I'm happy to re-open this if I'm missing something here.

**Comment by Mikaela** [comment]
I have understood that when I upload a media file, the bridge copies it and reuploads it and sends that file to IRC and when I redact the original file, the IRC link continues working.

If this is not a IRC bridge issue, where should I open this?

**Comment by t3chguy** [comment]
@Mikaela I believe no copying occurs and a direct link to the matrix.org HS's cache of the file is used. matrix-doc would be the place about such meta-issues.
