### ISSUE TITLE
Matrix.to links in new highlights

### ISSUE THREAD

**Issue by mweinelt** [matrix-org/matrix-appservice-irc#477]
Addressing a person in a message since a few days creates a markdown link to matrix.to when sent to IRC. This is a bit too much.

As seen on IRC:
```
14:33 <@maralorn> [md-](https://matrix.to/#/@md:darmstadt.ccc.de): Let me just calculate that.
```

```
{
  "origin_server_ts": 1500640427622,
  "sender": "@maralorn:maralorn.de",
  "event_id": "$15006404272677zUJrV:maralorn.de",
  "unsigned": {
    "age": 4056788
  },
  "content": {
    "body": "[md-](https://matrix.to/#/@md:darmstadt.ccc.de): Let me just calculate that.",
    "msgtype": "m.text",
    "formatted_body": "<a href=\"https://matrix.to/#/@md:darmstadt.ccc.de\">md-</a>: Let me just calculate that.",
    "format": "org.matrix.custom.html"
  },
  "type": "m.room.message",
  "room_id": "!rjzCtKKuZqPJCgeUSX:irc.hackint.org"
}
```

**Comment by Kegsay** [comment]
I think @lukebarnard1 @dbkr and co are aware of this. You should bring it up with them on the riot-web repo.

**Comment by maralorn** [comment]
@Kegsay Are you saying riot should format the message differently?

**Comment by Kegsay** [comment]
Yes. The IRC bridge's algorithm for processing Matrix messages is:
 - Does it have a `formatted_body` as HTML?
    * NO: Use `content.body`.
    * YES: Can the bridge represent **all** the HTML tags as IRC control codes?
        * NO: Use `content.body` as it's the safe plaintext representation.
        * YES: Convert HTML tags to IRC control codes and send `formatted_body` representation.

In this case, the bridge cannot process `<a>` tags so it falls back to `content.body`. Typically for HTML messages like this, this is the raw markdown the user entered, and given markdown is designed to be readable in its raw form, this worked well up until now. The problem now is that there is a difference between the characters you type into Riot and the `content.body` that is sent (it's automatically linkifying usernames). This goes against user expectations and so Riot should be formatting the plaintext body as the user entered (without markdown linkification).

Note that I'm not saying that Riot should never be putting markdown links into `content.body` - if the user actually types those characters then it should really be sending those characters.

**Comment by lukebarnard1** [comment]
>if the user actually types those characters then it should really be sending those characters.

This won't be the distinguishing factor we use because people might not be using markdown mode in the Riot message composer. But if people expect mentions of rooms and users to appear in a certain way (i.e. room aliases for rooms, display names for users) then we can certainly keep those plain.

**Comment by grahamperrin** [comment]
A screenshot of the problem: 

![2017-07-30 09 23 44 hexchat grahamperrin freenode - -ghostbsd](https://user-images.githubusercontent.com/192271/28754031-19e8c356-7535-11e7-8f3e-ba220bbbaf8f.png)

**Comment by lukebarnard1** [comment]
@grahamperrin this looks like a separate issue, could you make a new one to track it?

**Comment by lukebarnard1** [comment]
So this was fixed by https://github.com/matrix-org/matrix-react-sdk/pull/1242
