### ISSUE TITLE
Notification setting: only when mentioned isn't respected on bridged channels 

### ISSUE THREAD

**Issue by MoritzFago** [matrix-org/matrix-appservice-irc#480]
I joined the openwrt freenode channel trough the bridge provided by matrix.org. My notification settings are set to:only when mentioned, but I get notifications for every message in the channel.
Steps:
1. Join bridged channel like #freenode_#openwrt:matrix.org
2. Set notification settings to only when mentioned 
3. Get notifications for all messages, regardless off the setting.

**Comment by Mikaela** [comment]
I haven't encountered this issue by myself and would like to ask a few questions:

* Which client are you using?
* What is your display name?
* What do you have as highlight/key words (or something like that) in Riot Web settings?

I think that the issue is answered by either of the two later question.

**Comment by MoritzFago** [comment]
> Which client are you using?  

I am using Riot 0.4.3 on iOS and 
```
Version of matrix-react-sdk: 0.9.7
Version of riot-web: 0.11.4
Version of olm: 2.2.1
``` 
on my mac
> What is your display name?

it is moritz|m
> What do you have as highlight/key words (or something like that) in Riot Web settings?

<img width="536" alt="matrix notificaion settings" src="https://user-images.githubusercontent.com/4459068/28746493-b39054ea-748d-11e7-9da9-bf870c3c416f.png">
these, with no keywords
As far as i get it, because the bridged channel shouldn't be a group chat, the messages didn't contain neither of my names or keywords, i shouldn't get notifications for these messages. It works perfect for messages from the hackint-owned matrix bridge.

**Comment by Mikaela** [comment]
I don't know about Riot iOS, but in Android when looking at rooms there are three dots on the right to the room and right to the timestamp and touching it there is option for notifications. Could you confirm that *it's not* checked?

On Riot Android it being checked means notifications on all messages, unchecked only on mentions.

I wasn't able to find any relevant issues at their issue tracker (https://github.com/vector-im/riot-ios/issues/662 seemed the most relevant to me), but I still think that this is not a matrix-appservice-irc issue. Could you check with `#riot-ios:matrix.org` ? [I asked about this there, but I am going to sleep, so I don't have answer yet.](https://matrix.to/#/!tDRGDwZwQnlkowsjsm:matrix.org/$15014409741466rYRhP:disroot.org)

**Comment by MoritzFago** [comment]
As per my test, notifications are changed to only when highlighted, when you "Mute Notifications" in riot mobile, but when i set the same setting via the webclient, i still get messages. This differs from the behavior of the hackint provided bridge.

**Comment by Kegsay** [comment]
Please open an issue with the respective client repository. The IRC bridge does not control when to notify users.
