### ISSUE TITLE
Support sending arbitrary IRC commands through

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/matrix-appservice-irc#49]
https://matrix.org/jira/browse/BOTS-27

The use case here is to send explicit NICK and PASS irc commands.

We need to think about how this will affect the bridge semantics (doing something via raw IRC commands vs via the bridge).

**Comment by Kegsay** [comment]
Ideally this would literally be sending a message with the line-delimited command like:
```
NICK foo
```

But the bridge can support multiple networks, so it'd need to know which network you're on about. I **guess** we could augment it with the name of the domain first (and omit it if there is only 1), e.g:

```
irc.freenode.net
NICK foo
JOIN #bar
irc.somewhere.else
NICK baz
```
- Change nick to 'foo' on freenode
- Join channel #bar on freenode
- Change nick to 'baz' on somewhere

**Comment by eternaleye** [comment]
There's also that some commands ([`UHNAMES`](https://en.wikipedia.org/wiki/List_of_Internet_Relay_Chat_commands#UHNAMES) and [`NAMESX`](https://en.wikipedia.org/wiki/List_of_Internet_Relay_Chat_commands#NAMESX), both of which are invoked via `PROTOCTL`) alter the format the server uses for its messages.

**Comment by Kegsay** [comment]
@eternaleye - interesting to know, thanks. I assume this is a per connection option rather than a per server option, so:
 -  the current bridge will never have seen the different forms before 
 -  implementing this feature would mean the bridge may encounter this format.

**Comment by Kegsay** [comment]
Punting this from the next release, it will be in the next next release.

**Comment by Kegsay** [comment]
The next next release cycle is now upon us... reassigning.
