### ISSUE TITLE
m.notice is excempt from automatic pastebinning

### ISSUE THREAD

**Issue by Mikaela** [matrix-org/matrix-appservice-irc#490]
When user sends more than three lines, their message gets pastebinned. If a bot does the same, the messages go through triggering spam protections (https://github.com/matrix-org/matrix-appservice-irc/issues/471#issuecomment-322770808).

**Comment by deepbluev7** [comment]
So, we accidentally triggered this, when a bot sent a notice containing the output of the unix "yes" command. This led to half an hour of IRC spam. I don't think that is that good of a behaviour, since it will easily get the bridge banned.
