### ISSUE TITLE
Support !whois

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/matrix-appservice-irc#50]
https://matrix.org/jira/browse/BOTS-182

This is specifically so users can check to see if the IRC user they want to speak to is online, given we can't do member list syncing I->M

Related: https://github.com/matrix-org/matrix-appservice-irc/issues/49

**Comment by rryan** [comment]
Would you be open to contributions on this one? I keep wanting this :)

**Comment by Kegsay** [comment]
We're open to all contributions in general, just be sure to base your changes off `develop` rather than `master`. Bugs marked as `quick-win` are ideal targets.

**Comment by Kegsay** [comment]
@rryan Are you adding this in? The bridge will now at least say `err_nosuchnick` when you try to PM an IRC user who is offline, so the need may be less pressing now.

https://github.com/matrix-org/matrix-appservice-irc/issues/83 may be a better way of tracking improvements on the cutting edge.

**Comment by rryan** [comment]
Hi @Kegsay -- I got a patch working but am having trouble getting sign-off from my employer.  I think it's best to consider me not working on it for now until/if I can sort it out.

**Comment by Kegsay** [comment]
Righto, thanks for the quick response!

**Comment by Kegsay** [comment]
https://github.com/matrix-org/matrix-appservice-irc/pull/90 - progressing..

**Comment by Kegsay** [comment]
https://github.com/matrix-org/matrix-appservice-irc/pull/96
