### ISSUE TITLE
!quit error message sends templating variables

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-appservice-irc#512]
When sending `!quit` to the matrix.org espernet bridge, the following is returned if you're in no channels: `You are not in any channels on ${bridgedClient.server.domain}. `

**Comment by Mikaela** [comment]
Do the templating variables make this not a duplicate of https://github.com/matrix-org/matrix-appservice-irc/issues/461 ?

**Comment by turt2live** [comment]
In my opinion, it depends on which is easier to solve. They're two separate issues, but fixing #461 would fix this. If this ends up being easier to fix, then I'd recommend fixing it as it is user-facing.

**Comment by Half-Shot** [comment]
I believe we fixed this a while back.
