### ISSUE TITLE
Joining a channel with a dash in the name creates a "direct chat" instead of a room

### ISSUE THREAD

**Issue by unthingable** [matrix-org/matrix-appservice-irc#521]
Example, on Freenode: `!join ##haskell-beginners`

```
@appservice-irc:matrix.org joined the room.
@appservice-irc:matrix.org made future room history visible to all room members, from the point they joined.
@appservice-irc:matrix.org changed the room name to ##haskell-beginners.
```

**Comment by Mikaela** [comment]
I think this happens when you are the first user to join the IRC channel from Matrix and then *Riot* labels it as direct chat as it only has you and the appservice in it.

**Comment by unthingable** [comment]
D'oh, of course, too many `#`. Pardon, and thanks!

**Comment by Mikaela** [comment]
No problem, thanks for thinking of reporting it.
