### ISSUE TITLE
Message encoding

### ISSUE THREAD

**Issue by kolis** [matrix-org/matrix-appservice-irc#533]
Hello,
I'm in a Swedish speaking channel and some of the user have message encoding that does not render properly. Eg, like this `v�rre �n f�rr` instead of `värre än förr`. Some messages are properly encoded, mainly those using IRCCloud client.

Are there encoding settings for this appservice?

**Comment by Mikaela** [comment]
I think the issue is with some users using some other charset than UTF-8 and that the bridge cannot support/guess every possible encoding. I would request those users to change their charset to UTF-8.

**Comment by kolis** [comment]
Yes, everyone should be using utf-8. Thanks for response. I was hoping there was some solution to this, but I understand it would be difficult to allow mixed encodings.
