### ISSUE TITLE
Increase hardcoded maxSockets limit

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-appservice-irc#539]
The bridge currently has a hard limit of 1000 concurrent HTTP outbound connections.   This is peanuts when the freenode bridge restarts, given there are god knows how many Matrix users who need to be joined to the right IRC channels, and /join is slooow (see https://github.com/matrix-org/synapse/issues/2758).  As a result, other traffic gets completely starved out.  I don't see any reason why this shouldn't be more like 10K concurrent connections

**Comment by turt2live** [comment]
Fix through a configuration options exposed by https://github.com/matrix-org/matrix-appservice-irc/pull/681

**Comment by Half-Shot** [comment]
Actually occurs to me that we don't actually need nearly as many as 1000 since the join fix. Oh well :/
