### ISSUE TITLE
URLs of pasted images confuse some URL catchers

### ISSUE THREAD

**Issue by vivia** [matrix-org/matrix-appservice-irc#543]
Hello,

When someone using Matrix uploads an image into an IRC channel, the image is uploaded to the Matrix servers, and a link is pasted into the IRC channel. This link contains the image inside angle brackets. That confuses some URL catchers (like the Sakura terminal emulator) and think that the angle bracket is part of the URL.

Could you please change it to include spaces between the angle brackets and the URL, or something else that won't append random characters?

Thanks!

**Comment by ara4n** [comment]
This is a follow-on from https://github.com/matrix-org/matrix-appservice-irc/issues/258#issuecomment-357493849.  That one's closed, so let's continue the discussion here.

Agreed that `< http://foo >` would be better.

**Comment by ara4n** [comment]
sorted :)
