### ISSUE TITLE
!whois breaks when bridged to multiple IRC networks

### ISSUE THREAD

**Issue by aidalgol** [matrix-org/matrix-appservice-irc#547]
When the appservice is configured to bridge only one IRC network, the `!whois` command returns WHOIS information as expected.  When the appservice is configured to bridge multiple IRC networks, `!whois` always returns the error message "A server address must be specified."

`develop` branch, commit a03d15cb57e9bd106b82f98a7860635e92a32ea5

**Comment by aidalgol** [comment]
`!whois` works when provided with the server address.  The help string needs updating.

**Comment by fuzzy76** [comment]
OTOH this made the help text really confusing when the appservice bridges only one network. It claims you need to provide a server address, but that does not work. You seem to need to leave it out when you only have one network.
