### ISSUE TITLE
!cmd is case sensitive

### ISSUE THREAD

**Issue by aidalgol** [matrix-org/matrix-appservice-irc#550]
As reported by @Mikaela, the `COMMAND` argument to `!cmd` must be uppercase, even though the IRC protocol itself is (generally) case-insensitive.

**Comment by Mikaela** [comment]
Duplicate of https://github.com/matrix-org/matrix-appservice-irc/issues/273 which didn't previously mention !cmd which is why I didn't find it while thinking that this would be a duplicate.
