### ISSUE TITLE
@appservice-irc:matrix.org not responsive, and Matrix -> Freenode messages not getting through

### ISSUE THREAD

**Issue by NickHu** [matrix-org/matrix-appservice-irc#555]
![image](https://user-images.githubusercontent.com/450276/36353308-c6d41d8c-14bc-11e8-8c5c-43fd7ef762be.png)
Weirdly though, I can receive messages from Freenode -> Matrix perfectly fine.

**Comment by Stebalien** [comment]
I'm also getting this but I can't use the relay *at all*; complete silence in all IRC rooms and all rooms related to the relay. For example, `@appservice-irc:matrix.org` is completely non-responsive. After leaving the direct chat with `@appservice-irc:matrix.org` and re-creating the room, it never joins the room.

**Comment by simoniz0r** [comment]
I am experiencing the same problem.  It actually joined my invite yesterday, but it hasn't responded to me for about a month now.  It was working fine when I first setup my original Matrix account, but is now unresponsive.

**Comment by Half-Shot** [comment]
Having checked the logging, I am just not seeing any events come our way for some admin rooms which leads me to assume the problem is upstream in synapse. This problem is also experienced when users try to PM bridge services. (@benparsons was having issues trying to register himself with freenode the other day)

**Comment by Half-Shot** [comment]
I think the situation improved itself.

**Comment by slondr** [comment]
Still happening to me right now

**Comment by Half-Shot** [comment]
Please create a new issue rather than necroposting.
