### ISSUE TITLE
Error "err_bannedfromchan"

### ISSUE THREAD

**Issue by ankitjain28may** [matrix-org/matrix-appservice-irc#556]
Anyone please help me out, I am getting an error on joining IRC group through matrix.org

@appservice-irc:matrix.org kicked ankitjain. Reason: IRC error on #drupal-google: err_bannedfromchan

**Comment by Mikaela** [comment]
> `2018-02-22T20:01:30+0200 -- [#drupal-google] *[m]!*@* banned by leguin.freenode.net on 2018-01-22T23:15:29+0200`

You can change your nick by saying `!nick newnick` in direct chat with `@appservice-irc:matrix.org`.
