### ISSUE TITLE
Ability to unbridge arbitrary rooms

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-appservice-irc#557]
We have an unbridge.sh, perhaps referenced in the wiki for matrix-appservice-irc, which hits the unplumb API - but we need a way to knife bridging of portal rooms. In the past, I manually edited rooms.db and then restarted the bridge, but nowadays that's obviously untenable

**Comment by richvdh** [comment]
For the record, unbridge.sh is simply:

```
curl -XPOST -H "Content-Type: application/json" -d '{"user_id":"'$user'", "remote_room_server":"chat.freenode.net", "remote_room_channel":"'$ircchan'", "matrix_room_id":"'$matrix_room_id'"}' "http://localhost:3505/_matrix/provision/unlink"
```

.... and as such isn't really even worth mentioning in the wiki.

**Comment by richvdh** [comment]
I did something approximating unbridging by:
* adding the room to blocked_rooms in the database
* manholing in to invalidate the cache on `hs.get_datastore().is_room_blocked`
* masquerading as the appservice-irc user to kick out the matrix users

**Comment by wsdjeg** [comment]
@richvdh  Hi, I also encount same issue, and I just create #576 , I want to completely delete the bridging room `https://riot.im/app/#/room/%23freenode_%23vim-china:matrix.org` do you know how to do it? I am admin of the irc channel `#vim-china` in freenode

**Comment by Half-Shot** [comment]
`!unlink` / `!unbridge` now does this. You can do it if you are a bridge admin.
