### ISSUE TITLE
Support for IRC Direct Client to Client transfer of files

### ISSUE THREAD

**Issue by rogersachan** [matrix-org/matrix-appservice-irc#558]
I cannot send a matrix.rog/riot.im user a file using Direct Client-to-Client, instead the user receives a PM with an SHA-256 checksum.

Reproduction:
* Log into freenode on hexchat and navigate to a channel with the desired recipient.
* Find user to send to on the left, right click on their name, and click 'Send a file'.
![image](https://user-images.githubusercontent.com/7173984/36826008-c0c3be06-1cd8-11e8-9cf3-6532478267fc.png)
* Choose the file to send in the dialog
* SHA message will be sent and riot.im/matrix.org client will not prompt for download of file.

**Comment by Mikaela** [comment]
DCC is not standardized or regardless has every client doing it the different way and as it requires open port on both sides I think it doesn't work for most of people and I think it would be far out of scope of matrix-appservice-irc and if it was up to me, I would close this issue.

* https://en.wikipedia.org/wiki/Direct_Client-to-Client

**Comment by Half-Shot** [comment]
Agreed on this. I think it's fair to expect people to chuck a dropbox/gdrive/nextcloud or whatever link rather than sending files directly. I'm going to close it on the basis that I don't think it's a good idea to add it. Sorry :disappointed:
