### ISSUE TITLE
#freenode_#fyne:matrix.org is broken

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-appservice-irc#559]
it looks like it's failing to connect on the IRC side entirely

**Comment by ajwillia-ms** [comment]
I conneted this for the first time today, at the same time as #freenode_#edevelop which is working as expected.
The fyne room seems to show up as a direct chat with a user called #fyne

**Comment by ajwillia-ms** [comment]
Hi,

Is there anything I can do to help move this along?

Thanks

**Comment by eemeli** [comment]
I think I'm experiencing the same issue with `#freenode_#yaml-dev:matrix.org`. The actual channel has eight users on it, but from Riot it appears to only have one, and none of the messages that do show up in its [logs](http://colabti.org/irclogger/irclogger_logs/yaml-dev)

**Comment by jaller94** [comment]
Closing as we're no longer bridging to Freenode.
