### ISSUE TITLE
Auto-pastebin large messages to avoid spamming

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/matrix-appservice-irc#56]
https://matrix.org/jira/browse/BOTS-64

**Comment by sbts** [comment]
Ideally this would be configurable per channel (command to the AS user)
General public channels would want pastebining, while special purpose channels may not, eg: #ledgersmb we are very happy with the current behavior.

**Comment by Kegsay** [comment]
I'm not sure how much chan ops should get a say though - as I was under the impression anti-spam bots are network-wide rather than per-channel -- So even if you guys are happy with it, I can't allow it if it means it leaves black marks on the bridge (see #101)

**Comment by jansol** [comment]
AFAIK there are network-wide flood limits, but some channels employ their own bots for enforcing even stricter rules.

**Comment by sbts** [comment]
@Kegsay well the current rate-limiting behaviour doesn't seem to trigger any issues with the network side anti-spambots, and we are trying to encourage users in general to move over to native matrix clients instead of IRC.
However we do need to retain the IRC bridging for a long long time to come as it's been the primary support channel for many many years and there are users that will simply expect it to exist when they have an issue in 10 years time :-(

**Comment by Kegsay** [comment]
> some channels employ their own bots for enforcing even stricter rules

That's fine, since it will just affect the user sending the messages being kicked and/or banned. My primary concern is the overall bridge health.

> well the current rate-limiting behaviour doesn't seem to trigger any issues with the network side anti-spambots

[It did trigger issues](https://github.com/matrix-org/matrix-appservice-irc/issues/101), which is why I'm pushing for this issue to be fixed.

> However we do need to retain the IRC bridging for a long long time to come as it's been the primary support channel for many many years and there are users that will simply expect it to exist when they have an issue in 10 years time :-(

I'm not following your thought pattern here. Bridging will still work, just large (for whatever definition of large) messages will be uploaded into Matrix first (effectively as a `.txt` file) and then that URL will be sent instead - much like how we currently do for images. What am I missing here?
