### ISSUE TITLE
Provide some way of explicitly disconnecting from an IRC network

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/matrix-appservice-irc#57]
https://matrix.org/jira/browse/BOTS-94

bridged IRC users should quit the target network if they are not on any channels or offer some other way to quit the network. satdav claims he's still on moznet despite having left all the moznet channels

---

We cannot just quit the network if `channels == 0` because otherwise you become impossible to PM. We should have a `!quit` or equivalent though.

**Comment by lukebarnard1** [comment]
Fixed by https://github.com/matrix-org/matrix-appservice-irc/pull/253
