### ISSUE TITLE
we could retry join intents in matrix-appservice-bridge

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-appservice-irc#571]
currently if you use a join intent to ask the bridge to join a matrix room (e.g. an irc bridgebot responding to an invite), it can bail after only 10s if the room requires connecting to a remote HS (see https://github.com/matrix-org/synapse/issues/3013). It might be sensible to retry a few times rather than just give up immediately

**Comment by Half-Shot** [comment]
We now retry join intents in the bridge, via a smart membership queue
