### ISSUE TITLE
Support notifications in Matrix based on your IRC nick

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-appservice-irc#573]
Currently you have to manually set up keywords to alert you to people mentioning your current IRC nick.  It'd be nice if this happened automatically somehow (either with extensible profiles or custom keyword notifs of some kind).

**Comment by hexmode** [comment]
I'm confused about this.  "hexmode[m]" is my current IRC nick (when I'm in matrix) but I also have "hexmode" when I'm not in matrix.  Are you saying that both "hexmode" and "hexmode[m]" should work?   "hexmode[m]" does currently.

**Comment by ara4n** [comment]
yes, both hexmode and hexmode[m] should bing you in Matrix. it works today because hexmode is a subset of hexmode[m]. but if you changed your nick on the irc side it would break.

**Comment by Half-Shot** [comment]
Dumb question, would it not be easier to map nicks to User pills? This is what we do in the Discord bridge and it's generally been successful.

**Comment by Half-Shot** [comment]
Although you will have the silly sod who will set their nick to "a" or "http" and then it breaks.

**Comment by eeeeeta** [comment]
You could get around that issue, though, via a combination of:

- limiting replacement to nicks over x characters
- using a regex to ensure the nick is separated by spaces or punctuation
- only doing replacement if the nick is suffixed by `:` or `,`

**Comment by Half-Shot** [comment]
https://github.com/Half-Shot/matrix-appservice-discord/blob/bc39208d2d8a35c758cb2f849ba 975a671ee1298/src/matrixeventprocessor.ts#L87

**Comment by Half-Shot** [comment]
Reading the question more thoroughly:
> yes, both hexmode and hexmode[m] should bing you in Matrix. it works today because hexmode is a subset of hexmode[m]. but if you changed your nick on the irc side it would break.
- @ara4n 

I am now failing to see why the user cannot update their mentions to contain it, it must be a tiny subset of users who actually bother to change their nicks, and surely in those cases, we could poke them in the same bot conversation to update their mentions manually. This seems like a lot of work for a small subset of users.

If the bot decides on it's own to update the user's nick to something outside of "$NAME[m]" then sure, then it does become something worth automating.

**Comment by afranke** [comment]
> $NAME[m]

FWIW my automatic nick on GIMPNet was `AlexandreFranke[` (I assume they limit the number of characters) so a match on `$NAME[m]` wouldn't have worked for me.

**Comment by Half-Shot** [comment]
This can be closed now that #650 will replace mentions of your connected IRC nick with your userId.
