### ISSUE TITLE
Support old avatars

### ISSUE THREAD

**Issue by SoniEx2** [matrix-org/matrix-appservice-irc#575]
For compatibility, we should support "old" avatars, including (and especially) animated GIFs (as those are often considered a "premium" feature, but we can do it better by making them completely free!)

https://github.com/kvirc/KVIrc/blob/07867e9/src/kvilib/irc/KviIrcUserEntry.cpp#L57

http://www.kvirc.net/doc/doc_ctcp_avatar.html

**Comment by fndax** [comment]
CTCP AVATAR is a kvirc idea that is widely regarded as annoying and not something that people should use. I strongly recommend against Matrix -- or anyone else for that matter -- implementing it.

**Comment by SoniEx2** [comment]
so implement metadata avatar with no visibility controls

**Comment by SoniEx2** [comment]
btw we don't have to request them.

we don't have to show the requests to the matrix user.

we can just display them silently and not annoy anyone.

**Comment by SoniEx2** [comment]
I set an avatar on my client (not kvirc) but don't request ppl's avatars. do you find that annoying?

**Comment by Half-Shot** [comment]
#843 seems to be the sameish thing. Closing this since that is newer.

**Comment by SoniEx2** [comment]
that one doesn't even have KVIrc compatibility. :p
