### ISSUE TITLE
Error while installing IRC Bridge on Ubuntu 16.04, nodejs v8.11.1

### ISSUE THREAD

**Issue by schiessle** [matrix-org/matrix-appservice-irc#577]
I tried to install the IRC appservice on a Ubuntu 16.04 server by following this howto: https://github.com/matrix-org/matrix-appservice-irc/blob/master/HOWTO.md but if I run `npm install` I get this error messages: https://debianforum.de/forum/pastebin/?mode=view&s=40291

````
# npm --version
5.6.0
````

````
# nodejs --version
v8.11.1
````

Any idea what could be the problem here?

**Comment by Half-Shot** [comment]
Had the same issue. Looks like an upstream issue with node-irc

**Comment by Half-Shot** [comment]
I've done some more work and found that a clean clone on ``develop`` install's "fine". As in some of the packages fail to install but the tests do pass.

It also looks like the errors in the test are actually part of the test, so I wouldn't worry.

Is that all right @schiessle ?

**Comment by Half-Shot** [comment]
Closing this as we have builds that are passing on node 6,8 and 10
