### ISSUE TITLE
Bridge crashes under high logging load

### ISSUE THREAD

**Issue by neilisfragile** [matrix-org/matrix-appservice-irc#578]
The bridge uses a logging library called winston
winston.logger.log calls transport.log with a callback
the transport is DailyRotateFile. DailyRotateFile.log is backed by an fs.WriteStream and implements the callback with _stream.once
fs.writestream is backed by an EventListener, which gets expensive when there are lots of listeners
so if we log lots of stuff at once, we end up spending all our time adding and removing callbacks to the log stream, and the problem keeps getting worse

Unclear if this is our fault for doing too much logging, winston's fault for using eventlistener.once, or eventlistener.once's fault for being generally inefficient

**Comment by ara4n** [comment]
this just happened again. i got a cpu profile via `node debug`, which gives a solitary backtrace (https://matrix.org/_matrix/media/v1/download/matrix.org/DJYjszzBFyaWTzacmPGcqwKB) which irritatingly has meaningless linenumbers in it, at least for BridgedClient.js.

```
/home/ircas/freenode/matrix-appservice-irc/lib/irc/BridgedClient.js:105:61
/home/ircas/freenode/matrix-appservice-irc/lib/irc/BridgedClient.js:59:22
/home/ircas/freenode/matrix-appservice-irc/node_modules/winston/lib/winston/common.js:48:29
/home/ircas/freenode/matrix-appservice-irc/node_modules/winston/lib/winston/logger.js:118:32
/home/ircas/freenode/matrix-appservice-irc/node_modules/async/lib/async.js:114:26
```

Presumably this is due to some ES6->ES5 stuff happening somewhere, although unsure where given the project doesn't seem to use Babel.  A quick way to decrypt the linenumbers is probably to breakpoint in `node debug` and then try a good old basic-esque `list`, which i'll quickly try doing and hope it doesn't leave the bridge unstable.

**Comment by ara4n** [comment]
Well, that didn't help:

```
debug> setBreakpoint("BridgedClient.js", 105)
 101 };
 102 
 103 /**
 104  * @return {ConnectionInstance} A new connected connection instance.
 105  */
>106 BridgedClient.prototype.connect = Promise.coroutine(function*() {
 107     var server = this.server;
 108     try {
 109         let nameInfo = yield this._identGenerator.getIrcNames(
 110             this._clientConfig, this.matrixUser
 111         );
```

```
debug> setBreakpoint("BridgedClient.js", 59)
 54     }
 55     this.log = {
 56         debug: function() {
 57             arguments[0] = prefix + arguments[0];
 58             log.debug.apply(log, arguments);
>59         },
 60         info: function() {
 61             arguments[0] = prefix + arguments[0];
 62             log.info.apply(log, arguments);
 63         },
 64         error: function() {
```

just shows the line numbers against the .js as it sits on disk. So perhaps it's an optimisation bug or something which means the wrong line numbers are being reported.

**Comment by ara4n** [comment]
(on the plus side, the bridge seems to have survived being SIGUSR1'd, breakpointed, clear-breakpointed, and then debugger-detached.  It took about 15s for each breakpoint to be set, which is rather disconcerting).

**Comment by ara4n** [comment]
looking a bit harder, it looks like the 59 line number is probably correct - it's literally the debug logger for BridgedClient.  However, the 105 line is probably all wrong due to the `function*()` voodoo syntax which must be confusing everything.

**Comment by Half-Shot** [comment]
It's worth mentioning that Winston 0.9.0 (the one the bridge is using) was released in Feburary 2015, and it's now on version 3.X. It's highly likely that this was either fixed in winston or upstream.

**Comment by ara4n** [comment]
Assuming that it's indeed `BridgedClient.connect()` which is logging too fast, it's worth noting that there are only two debug log lines there:
```
        this.log.debug("connected!");
```
and
```
        this.log.debug("Failed to connect.");
```
As a stopgap we could just comment them out - or just run the whole thing at WARN loglevel or something until this is resolved.

**Comment by Half-Shot** [comment]
I'm going to tag this under matrix.org as I strongly suspect it's the only bridge managing to generate enough traffic to actually cause this failure mode (if I am totally wrong, please shout about it in the thread). 

But generally speaking it sounds like matrix.org cannot cope with having debug logging on and really aught to be running at INFO or WARN level.

**Comment by Half-Shot** [comment]
Did some testing with a test rig that just spams log lines to a file and notes the result: It's very possible to log faster than we can flush and causes the memory to eventually fill up. On that note: I don't see anything in this issue that explains what caused the crash. I'm assuming it would be node screaming in agony as it runs out of memory and in that case, yeah this could be why. I'd also like to know the uptime of the service before it crashes.

**Comment by Half-Shot** [comment]
Keeping this open tentatively while we run the freenode bridge for a bit, but I don't expect it to explode like last time :crossed_fingers:

**Comment by Half-Shot** [comment]
This crashed again recently, but some PRs are in progress to alleviate it.

**Comment by Half-Shot** [comment]
We've not seen this in a long time. Going to close it.
