### ISSUE TITLE
Winston logger is very out of date

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-appservice-irc#579]
Current Winston is pinned at 0.9.0 which was released 3 years ago, and I am reluctant to start snooping into logging issues knowing full well it's likely been improved in a later release. 

Upgrading will require making a few modifications to the logger setup, but the log statements can be left intact. I'd be curious to see if this resolves some of the issues in #578.

**Comment by ara4n** [comment]
I suspect we'll need a test jig that can reproduce the current failure mode first before we can be confident that upgrading has fixed it.

**Comment by Half-Shot** [comment]
Of course. Any work on the bridge to ease performance woes is going to need some way of generating a lot of traffic in a dev environment which is probably going to be the first thing I'll be looking at.

**Comment by Half-Shot** [comment]
@ara4n :

Okay, so the results are in and I can concretely prove that 2.4.2 will run much much faster than 0.9 at high logging levels. I've written a test project that creates a logger instance (which is a C&P of the bridge's logger code to ensure it's close to the real thing).

So if we spam a file with 100000 lines, 0.9.0 will take a second to run the log statement but will sit idle for another 1 minute and 40 seconds clearing up after itself before the process actually terminates. At higher numbers of log lines it just gives up and throws a out of memory exception before it's even finished all the log statements.

2.4.2 however exits cleanly at the same number of log lines, except it takes about 2 seconds before has finished and cleaned up.

Anyway, I think this sufficiently proves the need to upgrade the library.
