### ISSUE TITLE
Handle presence sensibly

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/matrix-appservice-irc#58]
https://matrix.org/jira/browse/BOTS-98
irc bridge AS appears as offline in presence, which is offputting and confusing

No idea what "sensibly" is though, or what it should really be representing.

**Comment by rryan** [comment]
Is someone on the team looking at this or would you be open to contributions here?

**Comment by rryan** [comment]
(Participating on Freenode via Matrix is currently a little embarrassing because I keep talking to people who left hours ago :) )

**Comment by Kegsay** [comment]
That is less to do with the bridge and more to do with Matrix.org's configuration of the Freenode bridge to **not** mirror IRC join/parts to Matrix. The bridge actually supports this, but Synapse struggles to handle that many join/leave events, particularly when netsplits occur.

We can't map this via presence as presence is global, but IRC join/parts are per room, we *have* to leave the room. We can however support a `!whois` command which will fail if the IRC user has left already - see https://github.com/matrix-org/matrix-appservice-irc/issues/50

**Comment by Kegsay** [comment]
It doesn't feel like there is anything actionable here. We have issues for join/part syncing on Freenode and we now have `!whois`, so I'm going to close this issue.
