### ISSUE TITLE
registration config issue

### ISSUE THREAD

**Issue by iclou** [matrix-org/matrix-appservice-irc#581]
I can receive messages from the matrix client riot into my IRC channel.
When sending messages from IRC the bridge gets the following error:

{"errcode":"M_EXCLUSIVE","error":"Invalid user localpart for this application service.
{"errcode":"M_FORBIDDEN","error":"Application service has not registered this user"}

I reviewed all parameters 2 days long... no success.
Any idea?

**Comment by iclou** [comment]
domain: safe-chatter.ch

After running the registration script I have adapted the registration file manually and now the regex looks like this:
regex: '@.*\.\*:safe-chatter\.ch'

With this it works but I am not sure if this is the correct way to do it.
Your feedback is highly appreciated.

**Comment by hpdeifel** [comment]
I get the same error when trying to join some channels (it works for others).

In particular, it does this:

```
INFO:IrcBridge [-] POST https://somewhe.re/_matrix/client/r0/register (AS) Body: "{\"auth\":{},\"username\":\"LOCALPART\"}" 
```

wher LOCALPART is the localpart of my matrix user requesting to join the channel. From my limited knowledge, it seems that the bridge want's to register this username. Why on earth would it try to do this? Surely, setting the regex to `.*` like in the above comment isn't the solution.

**Comment by jgoerzen** [comment]
I found that removing groupId in my config fixes this.

**Comment by jgoerzen** [comment]
Nope, never mind, it was only fixed for some rooms.

**Comment by jgoerzen** [comment]
I was unable to get !join to work, but by setting rooms public, I could at least join using their alias.

**Comment by Half-Shot** [comment]
I don't think there is anything to do here.
