### ISSUE TITLE
Matrix missing messages

### ISSUE THREAD

**Issue by gupta2140** [matrix-org/matrix-appservice-irc#595]
I use Riot client matrix (webapp on mozilla firefox, chrome and app on android) and every night I miss messages from any one user (randomly).
It may sound strange but I receive messages from all others, but miss all the messages from any 1 user (randomly changes every night).

Also it happens everyday only during night and late morning, i.e 10 p.m to 8 a.m (in India, UTC +5.30).
It seemed to be fixed almost a month ago, but again started to happen after some update.

Kindly look into the issue.

**Version information**

- **Platform**: web (in-browser) and android app.

**For the web app:**

- **Browser**: Firefox Quantum(60.0.2)
- **OS**: Ubuntu
- **URL**: / riot.im/app /

**For the android app:**

- **OS**: Android 7.1.2

**Comment by Half-Shot** [comment]
This is probably expected due to the extreme load on matrix.org, but could you tell me which networks you are seeing this on (e.g. Freenode) and if messages are late or missing entirely?

**Comment by gupta2140** [comment]
I experience this on Freenode.

From any one random user, the messages are completely lost and from other users, the messages are late.

**Comment by Half-Shot** [comment]
We don't have the logs to check this anymore. I think we can close this for now.
