### ISSUE TITLE
Identify the host of a bridge somehow.

### ISSUE THREAD

**Issue by Zarthus** [matrix-org/matrix-appservice-irc#599]
There's no way to know who is hosting a bridge on official matrix.org servers, please include this person somewhere, maybe through a CTCP request or in the realname.  (realname would work better as it will be logged consistently, whereas ctcp only would log if you specifically request it, however there's limits on the length of the realname.)

The only current strategy is to kline them all.

Relates to #598

**Comment by jaller94** [comment]
See [MSC2346: Bridge information state event](https://github.com/matrix-org/matrix-spec-proposals/pull/2346)

Implemented in https://github.com/matrix-org/matrix-appservice-irc/pull/941
