### ISSUE TITLE
failed I->M joins are not automatically retried

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-appservice-irc#603]
unless the user in question speaks on the IRC side.

**Comment by ara4n** [comment]
This means the membership list can get out of sync for lurkers if the /join request fails on the Matrix side (e.g. due to being timed out serverside after 90s)

**Comment by richvdh** [comment]
> (e.g. due to being timed out serverside after 90s)

... or due to join requests backing up for 6 hours and synapse being restarted before it has worked through the backlog

**Comment by Half-Shot** [comment]
Fixed by #608
