### ISSUE TITLE
IRC bridge leaks secret channel names

### ISSUE THREAD

**Issue by chauffer** [matrix-org/matrix-appservice-irc#605]
Please let me know if this is not the right place to report this issue.

### Description

Channels which are set as +s are leaked. Tested on the Riot.im Web UI search

### Steps to reproduce

- **User1** joins #foo on freenode, which has the *+s* (secret) channel flag
- **User2** searches and finds #foo on Riot.im Web UI search
### Expected
- **User2** cannot find #foo on the search

**Comment by Half-Shot** [comment]
Just to be clear, anyone can join #foo? They just can't search for it? Seems fairly easy to implement.

**Comment by chauffer** [comment]
@Half-Shot Not sure what you mean, but Matrix should respect the +s flag. https://wiki.swiftirc.net/wiki/Channel_modes#.2Bs

The expected behaviour is indeed that the channel is not listed, or searchable anywhere, but the Matrix user can join it if they know the name.

**Comment by Half-Shot** [comment]
Right, that's exactly what I was asking. Sounds like a good idea to implement this.

**Comment by chauffer** [comment]
@Half-Shot I would consider this as a bug/security related issue, not a feature.

**Comment by Half-Shot** [comment]
Apparently we do implement this, but in this case it hasn't worked :|

**Comment by Half-Shot** [comment]
Channel:
![image](https://user-images.githubusercontent.com/2072976/42505117-b60e9e3a-8435-11e8-9969-56a78649012c.png)
Directory:
![image](https://user-images.githubusercontent.com/2072976/42505141-c72d42fc-8435-11e8-90ff-7690371e2f45.png)

I did also search for the room in the directory and couldn't find it :(.

Could you PM me in private at https://matrix.to/#/@Half-Shot:half-shot.uk and see if I can drill down into your specific case?

**Comment by Half-Shot** [comment]
Following more investigation, it looks like the bridge is working, and I suspect this channel somehow slipped through the net when the mode got set/ channel got joined. In these cases, I suggest toggling the mode of the channel which should set the appropriate visibility.
