### ISSUE TITLE
Releases on NPM are outdated

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-appservice-irc#626]
Last release was 0.8.0 on NPM: https://www.npmjs.com/package/matrix-appservice-irc

**Comment by Half-Shot** [comment]
Better now?

**Comment by turt2live** [comment]
Yup! Thank you :D

**Comment by ajs124** [comment]
NPM is still at 0.13.0. Should I open a new issue or do you want to re-open this one?
