### ISSUE TITLE
Scrollback from remote newly-joined IRC bridge rooms produces blank events

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/matrix-appservice-irc#66]
https://matrix.org/jira/browse/BOTS-148

Blank as in "redacted" events:

``` javascript
{
  "content": {},
  "event_id": "$1451174561228692jZHfy:matrix.org",
  "origin_server_ts": 1451174561380,
  "room_id": "!SSbUDRwkvhDxtoRDXg:matrix.org",
  "type": "m.room.message",
  "user_id": "@freenode_taaem:matrix.org"
}
```

No idea which part of IRC bridge, Synapse, Federation is causing this.

**Comment by Kegsay** [comment]
No one else has reported this, closing this. We can always re-open this if it comes up again.

**Comment by dali99** [comment]
I've now reported this in https://matrix.to/#/!BAXLHOFjvDKUeLafmO:matrix.org/$olV+G5nIQG6NXTKbKDwarzD2BUDAsi6t6CohzGfGAqM?via=matrix.org&via=dodsorf.as&via=tedomum.net

**Comment by Ralith** [comment]
Yeah, this has happened practically every time I join a bridged room historically.
