### ISSUE TITLE
Why is this formatted message sent without formatting to IRC?

### ISSUE THREAD

**Issue by ThiefMaster** [matrix-org/matrix-appservice-irc#662]
```json
  "content": {
    "body": "[test] <moep> created master (1 new commit): https://git.io/DUMMY\ntest/master bb8ac5 Adrian Moennich: Initial commit",
    "msgtype": "m.text",
    "formatted_body": "[<font color=\"fuchsia\">test</font>] <font color=\"lightgrey\">&lt;moep&gt;</font> created <font color=\"orange\">master</font> (<b>1</b> new commit): <font color=\"teal\">https://git.io/DUMMY</font><br><font color=\"fuchsia\">test</font>/<font color=\"orange\">master</font> <font color=\"gray\">bb8ac5</font> <font color=\"lightgrey\">Adrian Moennich</font>: Initial commit",
    "format": "org.matrix.custom.html"
  },
```

It is rendered correctly (ie with the colors) on Riot, but IRC receives the plain `body` instead of the `formatted_body` converted to IRC-style formatting. The channel is not `+c` so it's not the IRC server stripping them. Sending a simple message such as `<font color=red>test</font>` works fine BTW.

**Comment by Half-Shot** [comment]
It doesn't look like you are escaping the <> around moep which it is interpreting as a tag. IRC doesn't use the html component if it detects an invalid tag.

**Comment by ThiefMaster** [comment]
But it is escaped in `formatted_body`! Isn't `body` supposed to be plain text?

**Comment by ThiefMaster** [comment]
I noticed it works fine if I send separate messages instead of the `<br>` separating the lines.

**Comment by Half-Shot** [comment]
So it is :(. My GitHub client unhelpfully rendered them wrong. 

Formatted body looks fine, I wonder why it got rejected...I'll test.

**Comment by ThiefMaster** [comment]
Another one that got rejected:

```json
  "content": {
    "body": "test/master 18ce06 Adrian Moennich: Revert \"Smelly world!\"...",
    "msgtype": "m.text",
    "formatted_body": "<font color=\"lime\">test</font>/<font color=\"orange\">master</font> <font color=\"gray\">18ce06</font> <font color=\"lightgrey\">Adrian Moennich</font>: Revert \"Smelly world!\"...",
    "format": "org.matrix.custom.html"
  },
```

**Comment by Half-Shot** [comment]
https://github.com/matrix-org/matrix-appservice-irc/blob/master/lib/irc/formatting.js#L158 is the list of allowed tags FYI

**Comment by Half-Shot** [comment]
Answer, ``sanitizeHtml`` replaces your double quotes around Smelly world with the html entity.

**Comment by ThiefMaster** [comment]
thanks, also for the quick fix!

**Comment by Half-Shot** [comment]
Merged.

**Comment by ThiefMaster** [comment]
Hey, any idea when this will be put in production for matrix.org?
