### ISSUE TITLE
We should be kicking on "Closing Link: ... (Bad user info)"

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-appservice-irc#671]
https://github.com/freenode/ircd-seven/blob/02023be9f8cdd13937814eb83ed4445b7be5081a/doc/sgml/oper-guide/commands.sgml#L388

**Comment by Mikaela** [comment]
It looks like ircd-seven documentation, here is possibly cleaner highlight:

* https://github.com/freenode/ircd-seven/blob/02023be9f8cdd13937814eb83ed4445b7be5081a/doc/sgml/oper-guide/commands.sgml#L378-#L400

397-398 seems to be the main point.

```
	  The reason is never sent to users. Instead, they will be exited
with <quote>Bad user info</quote>.
```
