### ISSUE TITLE
When user is PL50 at Matrix, but their ghost isn't opped at IRC, voicing the ghost decreases PL to 1

### ISSUE THREAD

**Issue by Mikaela** [matrix-org/matrix-appservice-irc#672]
I noticed power levels going somehow funnily in IRC channel where everyone was automatically voiced after small delay and decided to attempt it in another room.

In #irc:matrix.org Half-Shot was moderator, but his IRC ghost was normal user at IRC. I gave voice to the ghost and matrix-appservice-irc synced it by changing his power level from 50 to 1 until I opped the ghost to restore his PL to 50.

* * * * *

Edit: examples:

![screenshot from 2018-08-31 17-16-14](https://user-images.githubusercontent.com/831184/44917688-c981b300-ad41-11e8-935e-dac8a8c502bf.png)

* IRC op joins and gets PL50 from ChanServ, then autovoice bot hits and the op's ghost gets PL1.

![screenshot from 2018-08-31 17-17-15](https://user-images.githubusercontent.com/831184/44917741-e918db80-ad41-11e8-9c15-8fc86ca6cf88.png)

* What I described earlier.

* * * * *

Edit2: I think the solution involves the bridge ignoring other than the highest mode or power level that the user is currently having. IRCv3 capability [multi-prefix](https://ircv3.net/specs/extensions/multi-prefix-3.1.html) may also be somewhat related allowing the IRC server to tell all modes that the user has set instead of only the highest.

**Comment by Half-Shot** [comment]
#783 should ensure this no longer happens as it checks the PL of the mode being removed against the current PL of the user. If you remove v (PL1) from a user that has PL50, then it will no-op.

**Comment by auscompgeek** [comment]
In my testing just now, this is still an issue.
