### ISSUE TITLE
I->M messages fail consistently after some uptime

### ISSUE THREAD

**Issue by Valodim** [matrix-org/matrix-appservice-irc#687]
After some uptime of the bridge (I don't know exactly, maybe one to three days) it seems to go into a state where [I->M] messages fail consistently, like this:

```
2018-09-12 03:26:56 INFO:req [92kmoegqu5s00] [I->M] onMessage: irc.freenode.net from=redacted (null@irc.freenode.net) to=#channel action={"type":"message","text":"redacted","ts":0}
2018-09-12 03:26:56 INFO:IrcBridge [92kmoegqu5s00] [I->M] FAILED  (2ms)
```

Joins and leaves still work I->M, and all of M->I also still works. But onMessage fails 100% of the time, until I restart the bridge then it works again for a while. There is nothing suspicious in synapse's log around those timestamps, at least not on log level WARN.

This is on 0.11.1, and I haven't had those issues until recently (couple weeks ago). I can't say exactly if this correlates with the 0.11.1 update from 0.11.0, but I'm positive it wasn't an issue at least on 0.9.1 (I think I skipped 0.10.1). Happy to provide more info or logs if that helps.

**Comment by turt2live** [comment]
@Half-Shot This looks like a repeat of the instant-failure thing we saw before. Didn't a patch land for that?

**Comment by Half-Shot** [comment]
Yes, but not a released patch. Valodim is rightly using 0.11.1 which is also unpatched. We should really do a 0.11.2 release.

**Comment by Valodim** [comment]
Yes, please. I'd rather not put an enterprise loop around the bridge :)

**Comment by Valodim** [comment]
...ping?

**Comment by Valodim** [comment]
can confirm this is fixed :)
