### ISSUE TITLE
!nick bug: Handle Bahamut's 435 error code

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/matrix-appservice-irc#69]
There's been reports of `!nick` commands just black holing and not changing nicks. After digging into this, it turns out that Bahamut will send a non-standard `435` response of the form:

`<current_nick> <new_nick> <#channel> :Cannot change nickname while banned on channel`

The bridge should feed this back to the client and cancel the `NICK` listener. This may require the `node-irc` library at https://github.com/matrix-org/node-irc to be updated to recognise this IRC code.

**Comment by sbts** [comment]
In my particular case the message said I was banned in #git 

On investigation that channel requires you to issue an irc command before you can send, (but you can listen)
```
/msg gitinfo .voice
```

I wonder if the error message is not quite correct, perhaps it should say "while not voiced" or "while banned or not voiced"

Opening a 1:1 room with gitinfo and saying
`.voice`
allowed the nick change to complete successfully

**Comment by Kegsay** [comment]
Related: https://github.com/matrix-org/matrix-appservice-irc/issues/45

Once the performance changes have landed, I'll look into doing this.
