### ISSUE TITLE
Notify sender when the recipient in a PM is offline

### ISSUE THREAD

**Issue by z3ntu** [matrix-org/matrix-appservice-irc#692]
Could we at least have some indication that the message wasn't delivered? Currently I mostly connect to a channel via an IRC client to check if a person is online and only then send a message in the PM which is quite annoying.

And @Mikaela wrote at https://github.com/matrix-org/matrix-appservice-irc/issues/348#issuecomment-423552863
> @z3ntu I would recommed you to open a separate issue. I imagine that the Matrix ghosts could at least messagn m.notice nick offline as they do when they are invited to a not-bridged channel.
> 
> Of course it would also be possible for IRC users to /notice matrixuser user offline and other "fun", but that doesn't seem very risky/bad for me.

**Comment by Angedestenebres** [comment]
We got the same report with Channel operators that receive PM and reply without seeing that the user left IRC.

**Comment by Half-Shot** [comment]
Fixed in #978
