### ISSUE TITLE
The bot may violate IRC networks' terms of use

### ISSUE THREAD

**Issue by almereyda** [matrix-org/matrix-appservice-irc#70]
When trying to bridge between `ircs://irc.indymedia.org/#ecobytes` and `#ecobytes:matrix.allmende.io`, it has turned out the appservice is being banned quickly when forking into the virtual Matrix users.

At least the docs should carry a fair warning above the installation instructions, and provide instructions whom to speak with from popular IRC networks.

For Indymedia, it's `#ircd`. If this is a naming pattern that applies to all PoPs, the better.

**Comment by Kegsay** [comment]
> carry a fair warning

Sure, this seems reasonable, though it should be common sense to ask for permission if it isn't your IRC network you're bridging to.

> provide instructions whom to speak with from popular IRC networks.

Not going to happen: maintaining that list would be a giant pain.

**Comment by almereyda** [comment]
I cannot understand how this could be accepted as common sense via impicit premises. There are different usage vectors of IRC, and not all distribute all deeper knowledge about governance and regulations within those to everyone.

And how can common sense be a norm, if it is unexpressed?
Or you are referring to a body of knowledge around creation of IRC bots, which I am not aware of, since I never deployed one before. Last interaction with them were XDCC bots on EFNet in the beginning of this millenium for me.

**Comment by ara4n** [comment]
Agreed that we should have a fair warning and this isn't common sense if you're not in the habit of running IRC bots - sorry that you were bitten by this.
