### ISSUE TITLE
Postfixed usernames leak out in messages

### ISSUE THREAD

**Issue by raboof** [matrix-org/matrix-appservice-irc#704]
When using an IRC bridge, usernames are often postfixed (so they look like `r3boot (IRC)`).

For example using tab-completion, this full name, including postfix, is completed and included in the message. This is also how the messages is passed through the IRC bridge, so any users using IRC directly also see this prefix, which looks very strange.

It would be great if we could somehow scrub that postfix again on the way out to the IRC world.

**Comment by tulir** [comment]
The suffixes have been disabled already, but removing suffixes from old users isn't finished yet.

**Comment by raboof** [comment]
Oh, great, that makes this point moot than - sorry I didn't find that myself.
