### ISSUE TITLE
should we filter the freenode-connect warning?

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-appservice-irc#705]
as it confuses matrix users

**Comment by Mikaela** [comment]
Is it the bridges task to filter what Matrix users need or don't need to see? Will this lead users asking why they cannot private message freenode users? What if freenode starts using it for other important news? Have you consulted @freenode about this? Should InfoServ also be filtered as it's mostly used as another MOTD by many IRC networks that have it?

**Comment by aaronraimist** [comment]
I think the main confusing part is just people don't realize they are joining an IRC room when they join #matrix:matrix.org so they find the IRC PMs confusing. I'm not sure what the best way to solve that is but I don't think the bridge should filter out any messages.

**Comment by aaronraimist** [comment]
I'm beginning to switch my opinion on this. People asking why they got spam called Freenode-connect is an insanely common question.

**Comment by Half-Shot** [comment]
`Welcome to freenode. To protect the network all new connections will be scanned for vulnerabilities. This will not harm your computer, and vulnerable hosts will be notified.` is not something that a Matrix user is going to understand, so I feel like we should just filter these out. That said, I'm going to ensure we only filter out this specific message for the time being.

**Comment by Mikaela** [comment]
I think this issue has resolved itself as freenode has discontinued the use of `freenode-connect` and Libera.Chat hasn't implemented anything similar that I have seen.

**Comment by jaller94** [comment]
Closing in favour of the more general issue: https://github.com/matrix-org/matrix-appservice-irc/issues/888
