### ISSUE TITLE
MatrixBridge bot access and immediatly leave freenode channel when trying integration

### ISSUE THREAD

**Issue by erciccione** [matrix-org/matrix-appservice-irc#710]
When trying to integrate matrix to a freenode channel using riot, the bot just join the channel and leave it right after, without actually sending the request.

@appservice-irc:matrix.org shows up correctly in the matrix room, but it leaves it after few minutes. I guess because of the missing answer from freenode

**Comment by Mikaela** [comment]
Did you allow messages from unidentified users by setting mode -R? I added instructions to the FAQ just now:

> In order to allow messages from unidentified users, run e.g. `!cmd chat.freenode.net MODE YOURNICK -R`, you can get YOURNICK and the server with `!nick`.

* https://github.com/matrix-org/matrix-appservice-irc/wiki/End-user-FAQ#why-i-dont-get-messages-from-unregistered-to-irc-irc-users

See also https://github.com/matrix-org/matrix-appservice-irc/issues/447.

**Comment by erciccione** [comment]
Thanks @Mikaela . Closing this issue
