### ISSUE TITLE
OFTC equivalent for banning unregistered users, except matrix users

### ISSUE THREAD

**Issue by pravi** [matrix-org/matrix-appservice-irc#716]
The FAQ currently has an entry that is specific to freenode irc network. I'd like to get the equivalent command in OFTC.

https://github.com/matrix-org/matrix-appservice-irc/wiki/End-user-FAQ#i-am-a-chanop-and-have-a-spam-problem-how-can-i-fix-it-without-affecting-matrix-users

`!cmd MODE #<channel name> +Me *!*@2001:470:1af1:101::*` also did not work.

**Comment by Mikaela** [comment]
Have you asked OFTC about it? Reading [their channel mode documentation](https://oftc.net/ChannelModes/) I don't think they support this or then I am not seeing something.

**Comment by pravi** [comment]
@Mikaela thanks for the reply. I contacted one staff I know. Hopefully they can clarify.

**Comment by Dhanesh95** [comment]
The FAQ page does not contain the `+Me` mode anymore. It now mentions the `+qe` mode which seems to work with OFTC and Freenode. I also think that this approach is cleaner and non-malicious users will at least be able to join the channel and learn that they will have to register their nick to be able to speak.

**Comment by Mikaela** [comment]
@Half-Shot I think this could be closed or moved to [oftc/oftc-hybrid](https://github.com/oftc/oftc-hybrid/issues).

**Comment by Half-Shot** [comment]
@Mikaela Coolio, I don't really have a good view of this issue so if anyone wants to make an new issue over there, feel free :)
