### ISSUE TITLE
forwarded image will not be shown in IRC

### ISSUE THREAD

**Issue by Flexmaen** [matrix-org/matrix-appservice-irc#720]
I forwarded an image from another Matrix room, in IRC I got _... uploaded an image: image.png (802KB) <_  >
I had to upload the image (via Windows Explorer) then IRC-Users got a link between < >.

**Comment by Half-Shot** [comment]
Was the forwarded image sent from an encrypted chat?

**Comment by Flexmaen** [comment]
No.

**Comment by Half-Shot** [comment]
This got fixed, in the end.
