### ISSUE TITLE
Cannot connect to irc.gitter.im

### ISSUE THREAD

**Issue by benwaffle** [matrix-org/matrix-appservice-irc#729]
I am sending `!join irc.gitter.im #test` to @appservice-irc:matrix.org, but it is not recognizing this command for some reason.

<img width="371" alt="image" src="https://user-images.githubusercontent.com/1713819/53369651-b1b67080-3919-11e9-8309-4fe513be2838.png">

**Comment by t3chguy** [comment]
Because `@appservice-irc:matrix.org` is **JUST** for Freenode.
See https://github.com/matrix-org/matrix-appservice-irc/wiki/Bridged-IRC-networks
