### ISSUE TITLE
Client wont connect to Rizon

### ISSUE THREAD

**Issue by aladar42** [matrix-org/matrix-appservice-irc#731]
Whatever I do, I cant connect to rizon. Opening a dialogue with @rizon-irc:matrix.org only results to every command returning a "You are not connected to the network." message, using !join irc.rizon.net #channel only results to making a new Matrix channel and not bridging it to IRC, and using #_rizon_#channame:matrix.org from Riot does the same. I have tried everything I could, but there is absolutely no response. Whats going on?

**Comment by henrebotha** [comment]
The Rizon bridge has been removed, apparently. [This revision](https://github.com/matrix-org/matrix-appservice-irc/wiki/Bridged-IRC-networks/6a4e4b5ba8daeb42d52b41e725dc0ee228a20e25) of the wiki removes Rizon from the listing.
