### ISSUE TITLE
Changing matrix address

### ISSUE THREAD

**Issue by themousepotato** [matrix-org/matrix-appservice-irc#732]
I want to change my matrix address @test_gm:matrix.org to @navaneeth:matrix.org. Any workaround? I'm using @test_gm:matrix.org as an alias for my freenode account.

**Comment by Mikaela** [comment]
Matrix IDs cannot be changed and I think this is a duplicate of https://github.com/vector-im/riot-web/issues/8927 (and in wrong repository). Other related issues would be https://github.com/matrix-org/synapse/issues/1941 / https://github.com/vector-im/riot-web/issues/787 for actually deleting account.

PS. I am not affiliated with Matrix.org and don't give email/private support, I saw your email before the email notification about this issue.

**Comment by themousepotato** [comment]
@Mikaela Thank you very much for finding time to answer the query. Closing this issue.
