### ISSUE TITLE
Add killswitch to IRC clients

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/matrix-appservice-irc#74]
Currently, if an IRC client is created and told to connect to a network and some channels then it will do just that. It will periodically retry if any failures occur and there is no way to actually stop it from trying.

This sucks for tests because:
 - You get log spam leaking out from other tests (which are still trying to reconnect on a NOP mock)
 - Any fatal errors can result in sporadic, racey test failures - see https://github.com/matrix-org/matrix-appservice-irc/commit/b621a40e31bb975e0121f452d972a7e6986d26a3 for an example of this.

We need some way of communicating to the internal client logic to say "no really, please just stop.". Unfortunately, there is no real error code we can piggyback on for this from the IRC-side, which makes me think this should be an external-to-the-protocol killswitch. This makes me feel a bit sad though since it's additional logic simply for the benefit of testing, but I feel it is necessary for sanity.

**Comment by lukebarnard1** [comment]
Flakiness is now gone: Fixed by #205

**Comment by Mikaela** [comment]
So what is the command to kill the IRC connection?

**Comment by lukebarnard1** [comment]
@Mikaela: that's actually https://github.com/matrix-org/matrix-appservice-irc/pull/253 TL;DR it's `!quit server.name`
