### ISSUE TITLE
No discussions due to wrong permissions

### ISSUE THREAD

**Issue by Delurkdotcom** [matrix-org/matrix-appservice-irc#741]
Hello,

There is an issue with permissions in the #debian-fr channel on freenode. We can't post or read messages from the bridge because you have to rank 1.

Information on #debian-fr:
Founder    : freenode-staff, Yoda-BZH
Registered : Nov 05 10:27:43 2000 (18y 19w 5d ago)
Mode lock  : +nt-rf
URL        : http://www.debian.org/index.fr.html
Flags      : GUARD
The #debian namespace is registered to the debian project
*** End of Info ***

![Channel screen](https://delurk.com/service/images/fichiers/N55EeuYV.png)
![Channel permissions](https://delurk.com/service/images/fichiers/xd09FAYw.png)

**Comment by Half-Shot** [comment]
I've spent some time trying to break this with the new fixes in #785 and have been unable to. I would suggest if you have issues then asking an op to `/mode +m` and `/mode -m` to fix it.

**Comment by colemickens** [comment]
#sr.ht  and #monero seem affected

**Comment by yangm97** [comment]
Duplicate of #553.
