### ISSUE TITLE
URL detection does not detect all URL's

### ISSUE THREAD

**Issue by vranki** [matrix-org/matrix-appservice-irc#742]
Some links pasted by IRC users are not interpreted as links and need to be manually copy-pasted to a broser to open them. That is quite annoying.

Here are 2 examples of links pasted by IRC users, as seen by Matrix client (raw body):
```
https://scontent-arn2-2.xx.fbcdn.net/v/t1.0-9/56894369_10156484881641387_7100980223453167616_n.jpg?_nc_cat=102&amp;_nc_ht=scontent-arn2-2.xx&amp;oh=9ccb15390232a379df203c9ede3fffb4&amp;oe=5D458A3F

<span style='white-space:pre-wrap'><a href="https://www.iltalehti.fi/kotimaa/a/c1c90665-2486-4537-b659-1a5ad58fe549">https://www.iltalehti.fi/kotimaa/a/c1c90665-2486-4537-b659-1a5ad58fe549</a></span>
```

Notice that the first one does not have any HTML tags including <a> to make it a link. Second one has. If I understand correctly, the bridge's URL detection code does not detect these links for some reason.

Some other URLs not detected:

https://www.aamulehti.fi/a/cf208478-5638-416b-823e-3e2cf3762a0c

https://www.tori.fi/pirkanmaa/Ylakaappi__lev_100cm__syv_60cm_ovet_55727586.htm?ca=18&w=111

https://www.youtube.com/watch?reload=9&v=Dr20f19czeE

Tested with IRCnet bridge at twente.

**Comment by vurpo** [comment]
Isn't the linkification part of the Matrix client instead of the bridge? Or at least the client should linkify URLs that are not in a link tag.

**Comment by vranki** [comment]
It seems it is indeed client's task. Closing this as invalid (and moving to libqtmatrixclient)..
