### ISSUE TITLE
`!cmd chat.freenode.net JOIN 0` keeps the Matrix user in all rooms while being invisible from IRC 

### ISSUE THREAD

**Issue by Mikaela** [matrix-org/matrix-appservice-irc#743]
1. join freenode bridged rooms
2. open direct chat with `@appservice-irc:matrix.org`
3. run `!cmd chat.freenode.net JOIN 0`

**Expected result**: I get kicked from all freenode bridged rooms as if I had ran `!quit` (while possibly still keeping my ghost connected for direct chats)

**What happens instead**: I stay in all the rooms and can watch what is being chatted while the IRC users cannot see me. I get the impression that the agreement with freenode requires all Matrix users who can see discussions to be visible on the channel on the freenode side.

When I again say something, I am just JOINed to the channel for messages to get through normally.

**Comment by Mikaela** [comment]
Closely related: https://github.com/matrix-org/matrix-appservice-irc/issues/460 (REMOVE command)

**Comment by ara4n** [comment]
this is an edge case we need to address.

**Comment by danopia** [comment]
Matrix's state machine acts authoritative over the IRC ghosts, and `!cmd` exists outside of the Matrix state machine, so even a simple `PART` will work.

Here's an example where a Matrix user joins an IRC channel through Matrix UI, and then uses `!cmd PART ...`. This setup results in message snooping until the Matrix user speaks again (as described in @Mikaela's original comment). Hopefully the screenshot isn't too cluttered, tried to fit all relevant views into one:

<img width="1440" alt="Screen Shot 2019-04-17 at 11 02 42 AM" src="https://user-images.githubusercontent.com/40628/56310345-8b82a500-6100-11e9-9462-90e788894d9b.png">

The top left window is vanilla IRC, showing the matrix user join and part. A message sent by this vanilla IRC user is wrongly visible in the right window. The bottom left window shows the !cmd that caused the desync.

**Comment by Half-Shot** [comment]
This is fixed by #754, waiting for a deployment.
