### ISSUE TITLE
the correct appservice-irc is not shown when searching user ids

### ISSUE THREAD

**Issue by gitscivola** [matrix-org/matrix-appservice-irc#752]
I was trying to start a chat with appservice-irc:matrix.org to identify to my nick, but when i opened the + on people and typed in "appservice-irc", there was a list of 11 user ids, none of them were the correct one.

![Screen Shot 2019-05-11 at 14 47 08](https://user-images.githubusercontent.com/29957347/57573795-caec9a80-73fb-11e9-8d2d-5b982e991ebc.png)

I understand that I should copy/paste that user-id, but this seems like a bad idea to not have the correct one showing up when someone types in "appservice-irc", because they may not be paying attention and give their nickserv password to a random user id on a federated server.

Is it possible to prioritize/order the list to show users on the same homeserver first rather than a seemingly random list? That way everyone gets the correct one on the top.

**Comment by t3chguy** [comment]
> Is it possible to prioritize/order the list to show users on the same homeserver first rather than a seemingly random list? That way everyone gets the correct one on the top.



That would only fix it for `matrix.org` users though?

**Comment by gitscivola** [comment]
wow, i just realized i conflated two completely different things haha. appservice-irc isn't used for nickserv stuff, i'm not sure why i thought it was. Ignore this :)
