### ISSUE TITLE
espernet not working

### ISSUE THREAD

**Issue by V1TA5** [matrix-org/matrix-appservice-irc#755]
Hi,
im trying to bridge the room #dmp on espernet.
For that i joined #_espernet_#dmp:matrix.org and i can see the users.
None of my messages go trough and theres no bot or virtual user joining the irc channel.
messenging "!help" to @espernet-irc:matrix.org doesnt work but works with @appservice-irc:matrix.org.
I also tried setting up my own bridge and that works (but isnt useable due to the connection limits on irc so i stoped that).

Can it be that the espernet brisge is simply down/not working atm or is it me?

**Comment by V1TA5** [comment]
i was told by the friendly support chanel that its in its aproval phase. an update here would be great when a decission is made.

**Comment by Half-Shot** [comment]
The espernet bridge isn't running yet. There will be an announcement in #irc:matrix.org when it's back up.
