### ISSUE TITLE
!quit does nothing

### ISSUE THREAD

**Issue by abbec** [matrix-org/matrix-appservice-irc#756]
Issuing !quit in a chat with appservice-irc:matrix.org seems to not do anything:

![screenshot](https://user-images.githubusercontent.com/455022/58496885-0963b280-817b-11e9-85ee-28021b3cd3c6.png)

I would expect it to actually log me out.

**Comment by abbec** [comment]
Seems like it was just being suuuper slow

**Comment by abbec** [comment]
It seems like sometimes it does not respond at all to commands

**Comment by abbec** [comment]
Oh, the bot is actually offline

**Comment by turt2live** [comment]
@abbec I suspect it's just slow, as you've discovered. I'd recommend visiting [#irc:matrix.org](https://matrix.to/#/#irc:matrix.org) on Matrix if you have concerns with the bot's ability to function.
