### ISSUE TITLE
Matrix account randomly unregister from Freenode without nosiy warnings

### ISSUE THREAD

**Issue by erciccione** [matrix-org/matrix-appservice-irc#757]
I have a matrix account grouped with a registered freenode account.

After i identify as the Freenode user on Riot, everything is fine for some time, but randomly, the matrix user silently disconnects from Freenode and on reconnection NickServ notify me:

> This nickname is registered. Please choose a different nickname, or identify via /msg NickServ identify <password>.

The problem is that i often don't notice the message from NickServ and this cause the disconnection from my Freenode user and consequently the change of my nickname there. The change is not notified in any way, and i end up posting on Freenode convinced that my nickname is showing (since appear correct on matrix), but it actually shows as `Guest[random_number]` on Freenode.

I used the `!storepass` command in 'appservice-irc:matrix.org', but doesn't seem to solve to work at all. Right now i can only manually fix re-identifying to freenode when i realize the issue is happening.

I couldn't reproduce. The issue appear to happen randomly and in various timeframes (sometimes it disconnects after a month, sometimes twice in a week), doesn't matter if the matrix client is running or not.

**Comment by Mikaela** [comment]
I think `!storepass` / `PASS` could be called as a hack and this issue would be properly resolved by https://github.com/matrix-org/matrix-appservice-irc/issues/747 (which has the added benefit of identifying you in the corner case that the bridge connects to a splitted server without services) and/or https://github.com/matrix-org/matrix-appservice-irc/issues/470 (which needs to be SASL 3.2 and supported by the IRC server to avoid the corner case).

I prefer #747, because it would also allow having a different certificate for the bridge and revoking it in case of server compromise instead of requiring changing passwords everywhere.

**Comment by paul90** [comment]
Certainly seems very random, got kicked from one of a group of freenode channels when I started the Riot desktop client this morning. The other freenode channels seem to be unaffected, updating with the few overnight messages.

Could there be a timing issue?

**Comment by erciccione** [comment]
Just a heads up: this stll "regularly" happens.

**Comment by erciccione** [comment]
The problem is still happening but now got worse. I still get disconnected, but NickServ and @appservice-irc:matrix.org don't even let me know that i got disconnected anymore. My nick silently changes to `Guestxyz` and the only way to find it out if it's somebody from the chat let me know.

Between unreliable servers and a very bad experience with the IRC <-> Matrix relay, it's becoming quite frustrating to keep Matrix/Riot as my main communication medium for the projects i contribute to, especially since most of them are based on IRC. Please fix ASAP.

**Comment by erciccione** [comment]
Still happening. @Half-Shot Is there anything i can do to help investigate this issue?

**Comment by erciccione** [comment]
I was about to close this issue, since everything seemed to be fine for weeks and i thought one of the updates finally solved it, but today happened twice. So, problem still there.

I'm on the last version of riot-web on Debian buster.

**Comment by brendanzab** [comment]
This keeps happening to me. I keep getting "This nickname is registered" every week or so and dropping out of `##dependent`. It's super frustrating! 😞

**Comment by erciccione** [comment]
This still happens multiple times a week. Couldn't be more annoying.

**Comment by erciccione** [comment]
This is still happening.

It's also very hard to identify when the IRC user changes to `GuestXYZ`, because matrix will show pings from other users with my matrix name, not the IRC one.

To clarify:

Let's say my nick is `Erciccione` on matrix. When i get unregistered on IRC (as for this issue) and my nickname on IRC changes to `GuestXYZ`, matrix will highlights when somebody pings `GuestXYZ` on IRC, but willl show it as `ErCiccione` on matrix.

For example, i recently received this message in a matrix room:

`chatguy: Day 3 and ErCiccione is still ErCiccione`

^ this is how the message was displayed to me on Matrix. The problem is that the message of *chatguy* on IRC was

`chatguy: day 3 and ErCiccione is still GuestXYZ`

This led me to not realize that in the meantime my nick on IRC had changed.

**Comment by Cloudwalk9** [comment]
Still happening. Invite-only channels are unusable.

![Screenshot_20210221-095740_Element](https://user-images.githubusercontent.com/3199836/108628914-5bf30100-742b-11eb-8bd9-067d40e1937c.png)

**Comment by erciccione** [comment]
While we approach the 2 years birthday of this issue, the problem is still there and as annoying as ever. Is anyone looking into this? I already offered my help, i'm offering it again.

In the meantime i set up my own version of this bridge and looks like the bridge offered by matrix is having this problem, but i haven't experienced it yet with my own relay. Note that the freenode channels i relayed with my instance are almost empty, so that could be a factor.

**Comment by erciccione** [comment]
I haven't experienced this problem anymore since the switch to Libera. If that's the same for others IMO we can close this issue.

**Comment by Half-Shot** [comment]
Libera uses SASL which in practise seems to have made everyones lives easier. Even if you still get unregistered, the bridge will now warn you.
