### ISSUE TITLE
IRC users with | (pipe) in display name aren't visible at all in Matrix

### ISSUE THREAD

**Issue by Mikaela** [matrix-org/matrix-appservice-irc#767]
I think this is related to the fix of https://github.com/matrix-org/matrix-appservice-irc/issues/744 which isn't referencing that issue.

**Comment by Mikaela** [comment]
2019-06-16T11:20:37+0300 <@Mikaela> Morning, has anyone seen https://github.com/matrix-org/matrix-appservice-irc/issues/767 ? I am wondering if I should be changing my nick, but I think I am already hitting freenode nick registration limit (and unlikely to get REGNOLIMIT) and I have been using the nick Mikaela_Suomalainen|XMPP since Jun 02 16:35:46 2018 +0200 (1y 1w 6d ago) according to PirateIRC's NickServ
2019-06-16T11:21:45+0300 <@Mikaela> I also don't know what are the characters the bridge considers as valid. Elsewhere I just asked if another with ^ is visible and at least (presumably) Riot's search didn't bring anything else up than other people mentioning the name

**Comment by Mikaela** [comment]
Hi, it has almost been two weeks, could anyone at least acknowledge this issue? It's very awkward trying to chat on some channels like your official #matrix-irc with the majority of the room being unable to see me.

Am I missing details? Please tell me, what you need to know.

* Pirate Party Finland is using the PirateIRC network. We in PPFI have some people attempting to use our real names as nicks as we are the largest party outside of the parliament and using real names instead of nicks appears more appropiate. I wondered how should different clients/phones/protocols be denoted and I was suggested to use the | character for it which matrix-appservice-irc or Synapse has broken recently.
* I have registered the nick `Mikaela_Suomalainen|XMPP` on `Jun 02 16:35:46 2018 +0200 (1y 3w 3d ago)`, `Mikaela_Suomalainen|MatrixOrg` on `Jun 02 17:04:03 2018 +0200 (1y 3w 3d ago)`, `MikaelaSuomalainen|Matrix` on `May 29 15:38:48 2019 +0200 (4w 0d 1h ago)` and `Mikaela_Suomalainen|Mx-o` on `Apr 30 15:13:58 2019 +0200 (8w 1d 2h ago)`.
* I cannot provide information how common character `|` is in IRC, but I would say that it's not uncommon and everyone has surely seen at least one user with it. I have also understood that you yourselves were using `|m` instead of `[m]` in the first versions of matrix-appservice-irc, so I think this should be a priority.

There have also been other users asking about this issue on IRC and I again request that you at least acknowledge the existence of this issue. Of course I could workaround this issue by changing my nicknames, but I only have `REGNOLIMIT` on PirateIRC and I don't think freenode would grant it to me for the purpouses of workarounding this. It would also be a lot of work to change all my XMPP bookmarks to reflect the new nick in order to not have Biboumi changing my nick all the time and hitting this issue again. Matrix would be fine with per-room nick, but I haven't heard anything about the return of matrix-bifröst.

**Comment by Mikaela** [comment]
According to Dax from freenode staff, they are seeing ~700 connections with nicks including the character `|` who are currently ignored entirely by Matrix users.

`2019-06-26T18:55:16+0300 <dax> Mikaela: alrighty, nobody objected for half an hour, so... there's about 700 connections on freenode right now with | in their nick`

**Comment by fndax** [comment]
This is fixed on at least freenode, I believe the relevant PR is #768

**Comment by Half-Shot** [comment]
This is fixed on freenode, pending rollout to other bridges.

**Comment by Half-Shot** [comment]
Closing this PR, please use #744 for reporting issues of this type as they seem to all be related.
