### ISSUE TITLE
Remove dead bridges from the "Bridged IRC networks" wiki page

### ISSUE THREAD

**Issue by fndax** [matrix-org/matrix-appservice-irc#771]
https://github.com/matrix-org/matrix-appservice-irc/wiki/Bridged-IRC-networks has multiple bridges on it that aren't up. Rizon is gone; I've been told that the Espernet bridge is at least down (not sure if permanently); there are probably others. I assume it's easy to test this by contacting each of the appservice users in the table and seeing which ones respond.

Opening an issue instead of just doing it because I've brought up the subject multiple times in #irc:matrix.org and asked for opinions on whether removing old bridges is wanted, and got no response.

**Comment by Mikaela** [comment]
@MatrixCoffee I guess you are the person to ask as you have done the latest bigger wiki editing with #563

**Comment by Salusbury** [comment]
Just wondering, but why was Rizon removed?

**Comment by Half-Shot** [comment]
I've removed the known dead ones.

**Comment by bingoxo** [comment]
> Just wondering, but why was Rizon removed?

https://forum.rizon.net/showthread.php?5364-Matrix-IRC-Bridge&p=15222#post15222
