### ISSUE TITLE
Recently active user kicked from IRC reason :  Idle kick: User has been idle for 30 days.

### ISSUE THREAD

**Issue by GuillaumeDIDIER** [matrix-org/matrix-appservice-irc#774]
A user who recently joined a freenode IRC channel (and spoke) got kicked less than 24 hours later, with the above reason, bu the app service. Can someone explain what's going on or point us at the correct place to ask about this issue ?

**Comment by Half-Shot** [comment]
They shouldn't have, it only targets users which are marked as inactive on the matrix.org homeserver. Can you give me the name of the user either here or in a PM (@Half-Shot:half-shot.uk) so I can investigate.

**Comment by mgttlinger** [comment]
Today the appservice kicked a matrix user with above reason. I suppose this is related and should never happen, right?

**Comment by Half-Shot** [comment]
We had a bug this time around which lead to some users erroneously. This has since been rectified. I don't think this issue is actionable and I am going to close it.
