### ISSUE TITLE
After being kicked, rooms silently disappear

### ISSUE THREAD

**Issue by z3ntu** [matrix-org/matrix-appservice-irc#775]
I had the situation recently where apparently the matrix.org bridge restarted and my IRC client claimed the username `z3ntu` (which I've also set for the irc bridge) which then caused the nickserv authentication to fail (`z3ntu1 is not a registered nickname.`), which then in turn kicked me out of some IRC rooms (e.g. `@appservice-irc:matrix.org kicked @z3ntu:matrix.org. Reason: IRC error on ##linux-msm: err_needreggednick`) but the rooms where this happened just silently disappeared out of my room list.

**Comment by z3ntu** [comment]
I've opened https://github.com/vector-im/riot-web/issues/10374 .

Do you know about the second thing I've mentioned, that when your IRC username is different from the freenode account you have, that the bridge tries to authenticate for the current username and not the one it should? At least I can send NickServ directly `identify $username $password` but the `!storepass` command on the bridge just stores the password and no username? Should I open an issue for that?

**Comment by Mikaela** [comment]
`!storepass` only stores the server password, which is generally forwarded to Services which is also the case on freenode where you can `!storepass z3ntu:password` to be identified automatically instead regardless of your nickname.

However the proper solution towards automatic identifying would be #470 (SASL which is the only standardized way for automatic identifying) or in case of OFTC #747 (CertFP which I would actually prefer as it would let me not give my password for Matrix.org and allow me to revoke its access without changing the password).

**Comment by z3ntu** [comment]
Thanks!
After knowing this exists, it's fast to find the freenode docs for it

> you can supply your login details, in the form \<account\>:\<password\>, as a server password and they will be forwarded to NickServ when you finish connecting.

Maybe this can be added to the `!help` text, but I'm closing this issue now.
