### ISSUE TITLE
Error plumbing room: store_room with room_id=!<snip> failed: duplicate key value..

### ISSUE THREAD

**Issue by vranki** [matrix-org/matrix-appservice-irc#787]
I tried to plumb an existing Matrix room to a IRC channel, but the provisioning API endpoint always returned 502 Bad Gateway.

It seems the error in server log is:
```
synapse.storage.room - 245 - ERROR - POST-935224- store_room with room_id=!<snip> failed: duplicate key value violates unique constraint "rooms_pkey"
                                                  DETAIL:  Key (room_id)=(!<snip>) already exists.
```
The guide I was following is at bottom of the page:
https://syscom.utwente.io/info/matrix/irc/ircnet/

I'm pretty sure the json I've sent is correct. Plumbing is difficult (#786) so I could have done something wrong and this is a valid error, but for end user it's impossible to know what's wrong.

**Comment by Half-Shot** [comment]
It's difficult to see what went wrong here from the IRC side without bridge logs. The synapse error doesn't mean much to me, you might want to consult with https://github.com/matrix-org/synapse

**Comment by vranki** [comment]
I've asked the bridge admins to get the logs from this try or try plumbing again and get new results. Hopefully someone posts them here.

**Comment by vranki** [comment]
Closing, reopen if this still happens.
