### ISSUE TITLE
User that is k-lined from freenode stays on the Matrix room to harass Matrix users

### ISSUE THREAD

**Issue by Mikaela** [matrix-org/matrix-appservice-irc#789]
We had a problem on a mainly freenode channel where an abusive user was k-lined (network banned) and was saying "creepy stuff" on Matrix that went completely undetected by IRC ops until a Matrix user with frowning smiley happened to connect to IRC directly and notice this issue and thus told what is the case.

I don't think the bridge should be moving control of the channel from IRC to Matrix or require IRC ops to use Matrix for opping the channel, especially considering how this was in a portal room.

**Comment by Half-Shot** [comment]
#790 should fix this, provided the bridge bot has enough power-levels of course.
