### ISSUE TITLE
Some bridged rooms seem to get corrupted & cause federation issues

### ISSUE THREAD

**Issue by vberger** [matrix-org/matrix-appservice-irc#794]
I'm reporting this because it is the third time it occurs, which is becoming a little too much for a coincidence.

I'm using my own HS (latest synapse from pip), and using the matrix.org provided IRC bridges.

**The symptoms are:**

- A bridged room I am part of suddenly seems to no relay messages to/from IRC any more
- I try to leave/rejoin the room
- I cannot rejoin, Riot tells me "Internal Server Error" or "Could not join room: no known servers"every time I try
- My synapse logs display `IntegrityError` messages about duplicate keys violating unique constraints, for example:

```
psycopg2.IntegrityError: duplicate key value violates unique constraint "current_state_events_room_id_type_state_key_key"
DETAIL:  Key (room_id, type, state_key)=(!BaPNkuWOJBwbKQkpGc:matrix.org, m.room.member, @mozilla_dex:matrix.org) already exists.
```

**So far, it occurred with the following rooms:**

- `#freenode_#wayland:matrix.org`
- `#irc:matrix.org`
- `#mozilla_#rust-fr:matrix.org`

I could "fix" it for `#freenode_#wayland:matrix.org` using the "nuke_room_from_db" script, which is obviously not a good solution. I haven't attempted to fix it for the two other rooms yet. I can run DB queries or do more diagnostic on them if necessary.

I am reporting it here because it only affected IRC-bridged rooms, so I suspect it may be linked to the IRC bridge.

**Personal interpretation:**

(Wild speculation) I seems as if matrix.org HS started to believe I was no longer in the room, while my HS still believed I was in, causing state mismatch that could not be corrected...

**Comment by vberger** [comment]
So, after some more digging it appears that the root of the issue was that my `current_state_events` table  in synapse DB contained duplicate entries for some bridged rooms, which synapse very much did not like...

**Comment by Half-Shot** [comment]
Going to assume this is not related to the bridge and close it.
