### ISSUE TITLE
/Myroomnick seems not effective on irc

### ISSUE THREAD

**Issue by mokas01** [matrix-org/matrix-appservice-irc#800]
The command /myroomnick allows to change the nick in a matrix room. I tried it on a room I am in as a matrix user (through the bridge) and a IRC  user as well. The change in Riot has taken place, but not from the perspective of those connected on IRC.

On matrix I appear as NewNick
On IRC, the same matrix account appear as OldNick[m]

I have't tried to change the Nick globally, but it could be possible that the bridge uses this variable instead of the one set with /myroomnick

Thanks for bridge and your help

**Comment by t3chguy** [comment]
This makes sense given the IRC bridge has one connection to the IRC network per real matrix user, nicks in irc are not per-room and given you only have one connection you can only have one nick

**Comment by t3chguy** [comment]
Allowing this would much quicker exhaust the allocated connection limits (and otherwise resources in general) due to each user being able to consume any number of connections to the irc network

**Comment by mokas01** [comment]
this make sense, thanks for your answer. I guess we can close the issue, then
