### ISSUE TITLE
Unable to receive messages on #freenode_#flatpak:matrix.org

### ISSUE THREAD

**Issue by MateusRodCosta** [matrix-org/matrix-appservice-irc#802]
Hello, some months ago I migrated my Matrix account from `@MateusRodCosta:matrix.org` to `@mateusrodcosta:chat.weho.st` using the Modular.im tool. One of the rooms I am used to talking, and which was included on the migration, is `#freenode_#flatpak:matrix.org` (room id: `!nvrvsodkHJsNtzLpLT:matrix.org`).

However, ever since the migration I am unable to see any messages inside that room that aren't my own messages or my own leave and join events. I have talked to people which confirmed my messages got through to the IRC side but I don't see other people's messages on Matrix side.

This issue seems to not happen with Matrix rooms that are linked to IRC (such as Matrix HQ) and I am not sure if it happens with rooms that are created for IRC channels (such as a `#freenode_*:matrix.org` room) since I don't seem to be in any other of these.
I also rechecked whether it happens on my old matrix.org account and it didn't happen.

One interesting thing that seems to be consistent is that I can look in Firefox's Network tab when running Riot Web and see that whenever there's a request to `https://chat.weho.st/_matrix/client/r0/rooms/!nvrvsodkHJsNtzLpLT%3Amatrix.org/messages?<params>` the result is *always* an error 500 with a response of `{"errcode":"M_UNKNOWN","error":"Internal server error"}`

This issue happens every single time I try to load the Flatpak room on any device. Riot Web shows an eternal loading indicator and Riot Android shows the "Internal Server Error" message.

**Comment by matanster** [comment]
Is there really a way to access the flatpak IRC from matrix?

**Comment by jaller94** [comment]
Sorry that this was not acted upon.
Closing as the Freenode bridge was shut down.
