### ISSUE TITLE
Drop support for statsd

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-appservice-irc#818]
I'm looking through the code and seeing what we can prune from the bridge that is no longer in use. I'm interested to know if anyone is still using the statsd support for metrics in the bridge. Note that this is different to Prometheus metrics, which is more featureful at this point.

**Comment by joepie91** [comment]
If possible, it may be worth it to insert a soft-deprecation message into the statsd metrics, suggesting that people comment here if they still use it? Assuming that that message would show up in their metrics somehow, somewhere.

**Comment by Half-Shot** [comment]
#837 has a message that appears in the logging. We will likely deprecate it after the next release.
