### ISSUE TITLE
Integrate with NickServ

### ISSUE THREAD

**Issue by yuvipanda** [matrix-org/matrix-appservice-irc#82]
Right now identifying yourself to NickServ is a somewhat clumsy and error prone process:
1. You have to figure out how to contact the app-service and use !nick
2. Then you have to wait for NickServ to ping you - this doesn't happen sometimes
3. This then gives you 30s to identify yourself, or you're locked and need to call in release
4. Every time the bridge restarts you gotta do this

This should be automatically handled by the bridge. This implies the bridge will need to store the nickserv password somewhere as well.

**Comment by leonerd** [comment]
FYI, most networks integrate server and NickServ password systems, so it's sufficient simply to provide a server password. Direct interaction with NickServ shouldn't be necessary in most cases.

**Comment by yuvipanda** [comment]
Hmm, does freenode do this? I've so far required to directly interact with
NickServ, but there might be a trick I'm missing.

On Tue, Jun 28, 2016 at 8:53 PM, Paul Evans <notifications@github.com>
wrote:

> FYI, most networks integrate server and NickServ password systems, so it's
> sufficient simply to provide a server password. Direct interaction with
> NickServ shouldn't be necessary in most cases.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/matrix-org/matrix-appservice-irc/issues/82#issuecomment-229146802>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAB23gf-BYWdk80UrGm0vOfUyNjujo9Cks5qQW22gaJpZM4JAXIn>
> .
>



-- 
Yuvi Panda T
http://yuvi.in/blog

**Comment by tgr** [comment]
Privacy-wise, if you are trying to authenticate after you've connected, you have failed already. For Freenode the recommended authentication method is [SASL](https://freenode.net/kb/answer/sasl). 
Server passwords are an inferior but probably more widely supported alternative.

I don't think there is a way around storing your password (or private key if you use one of the challenge-based SASL protocols) on the bridge.

**Comment by Mikaela** [comment]
> Hmm, does freenode do this? 

If you send freenode `PASS nickame:password` (what happens when you use it as server password in your client), it will forward it to services, but what you should use is SASL.

PASS forwarding possibly joins you to channel before identifing and I think it also suffers from not checking that NickServ is NickServ (and not user who got the nick thanks to server isconfiguration (has happened many times especially when new server has came) and in any case what you should use is SASL.

* http://ircv3.net/specs/extensions/sasl-3.1.html
* http://ircv3.net/specs/extensions/sasl-3.2.html
    * This is an optional extension and not so widely supported yet, but it features `SASL REAUTH` which allows identifying with SASL after you are already connected e.g. after netsplit when you were connected to splitted server without services and the split is over and services return.

**Comment by TJuberg** [comment]
SASL is the best option for networks that support it, preferably supporting both PLAIN and ECDSA-NIST256p-CHALLENGE modes. The latter especially if the bridge continues to give problems with SSL connections.

For networks that does not support SASL, falling back to passing the password as server password seems sane, but this should imo. be dependent on SSL being used.

**Comment by Mikaela** [comment]
> SASL is the best option for networks that support it, preferably supporting both PLAIN and ECDSA-NIST256p-CHALLENGE modes.

:+1: for PLAIN, :-1: for ECDSA-NIST256p-CHALLENGE as the author says it's "probably dead" https://github.com/znc/znc/issues/746#issuecomment-119274435 and you would probably end up doing useless work.

**Comment by TJuberg** [comment]
While ECDSA-NIST256p-CHALLENGE has issues, it is what is supported by Freenode for instance.
And I'll prefer questionable algorithms that NSA may or may not have a backdoor into over PLAIN any day.

**Comment by Kegsay** [comment]
We now allow Matrix users to store NickServ passwords via `!storepass passw0rd` - this gets sent to the IRC network as a server password. I can confirm this works fine on Freenode.

**Comment by tgr** [comment]
Where do you issue that command? When I type in the message box like I'd do with special commands on normal IRC clients, it just gets sent to the channel (and `/!storepass` returns an error).

**Comment by Stebalien** [comment]
You have to issue it in the "IRC Bridge Status" room. Unfortunately, once you've closed it, I don't know of a way to get it back...

**Comment by vith** [comment]
Opening a direct chat with @appservice-irc:matrix.org worked for me, assuming you're using that public bridge instance.
