### ISSUE TITLE
#mumble is in a Schrödinger state ("This room has been replaced and is no longer active." loop)

### ISSUE THREAD

**Issue by Mikaela** [matrix-org/matrix-appservice-irc#823]
Via https://github.com/mumble-voip/mumble/issues/3814#issuecomment-535691450:

> Unfortunately our bridged room on Matrix is in a Schrödinger state: it exists and messages from IRC appear, but it is marked as "replaced and no longer active" and messages cannot be sent.
> 
> This happened after I attempted to disable the end-to-end encryption after asking for support in #irc:matrix.org, because messages from Matrix weren't appearing on IRC.
> 
> I contacted support@matrix.org on February 16th and they replied in less than an hour saying that they would look into it. I asked whether there was any progress on the issue on April 1th, June 20th and September 14th. Unfortunately I never received a reply.

CC: @davidebeatrici

**Comment by Half-Shot** [comment]
Yep, the room itself is entirely broken because the `m.room.tombstone` event references itself. I don't quite know how that happened, but I don't really know where the bridge should actually be relaying into.

```
{
  "content": {
    "body": "This room has been replaced",
    "replacement_room": "!NONzDkAXGVzrZQQbEe:matrix.org"
  },
  "event_id": "$155509015596563LCPLB:matrix.org",
  "origin_server_ts": 1555090155632,
  "sender": "@davidebeatrici:matrix.org",
  "state_key": "",
  "type": "m.room.tombstone",
  "unsigned": {
    "replaces_state": "$15501808494591PnYeH:matrix.org",
    "age": 13294881272
  },
  "room_id": "!NONzDkAXGVzrZQQbEe:matrix.org"
}
```

**Comment by Krzmbrzl** [comment]
Does this mean that we should report this issue/bug somewhere else (aka. which is the upstream-repository)?

**Comment by Krzmbrzl** [comment]
Also is there a quick way of fixing this (by e.g. setting that field manually to something more senseful)?

**Comment by Half-Shot** [comment]
The self referential bug should be reported to https://github.com/matrix-org/synapse/issues.

To fix this, you are going to need to create a new room and set it up with the correct aliases, names, topics etc. You can then use the Riot dev tools (go to room settings > Advanced > Devtools > Explore Room State > m.room.tombstone) and replace the content of `"replacement_room": "!NONzDkAXGVzrZQQbEe:matrix.org"` with the ID of your new room.

Ensure the room is joinable. I'll try to hook up the IRC bridge next time we go for a restart :+1:

**Comment by davidebeatrici** [comment]
> Yep, the room itself is entirely broken because the `m.room.tombstone` event references itself. I don't quite know how that happened, but I don't really know where the bridge should actually be relaying into.

My fault. After I created a replacement room, the IRC bridge was still connected to the old one.
I set `m.room.tombstone`'s value to the old room's ID, thinking that it would override/remove the event.

> To fix this, you are going to need to create a new room and set it up with the correct aliases, names, topics etc. You can then use the Riot dev tools (go to room settings > Advanced > Devtools > Explore Room State > m.room.tombstone) and replace the content of `"replacement_room": "!NONzDkAXGVzrZQQbEe:matrix.org"` with the ID of your new room.
>
> Ensure the room is joinable. I'll try to hook up the IRC bridge next time we go for a restart +1

It seems that the room upgrade issue is not present anymore: as soon as I changed `replacement_room`'s value to `!jRKczymKjXhzAFRhke:matrix.org` (the new room's ID), the bridge switched room.

Messages sent from Matrix appear on IRC and messages sent from IRC appear on Matrix.

Thank you very much for your help!

**Comment by Mikaela** [comment]
I guess I can close this then :)
