### ISSUE TITLE
Persist the channel keys in +k rooms

### ISSUE THREAD

**Issue by evoL** [matrix-org/matrix-appservice-irc#835]
I'm a member of a room that has +k set. Unfortunately, every time I lose connection to IRC (which can happen even several times per week), I get kicked out of the room, because the bridge doesn't persist the key that I've entered when joining. It's a pretty annoying experience.

**Comment by Mikaela** [comment]
Duplicate of https://github.com/matrix-org/matrix-appservice-irc/issues/213.

**Comment by evoL** [comment]
Thanks, Mikaela. Closing this in favor of #213.
