### ISSUE TITLE
ECONNRESET can make the bridge panic

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/matrix-appservice-irc#84]
Freenode bridge restarted with:
```
2016-07-02 08:27:21 ERROR:main FATAL EXCEPTION
2016-07-02 08:27:21 ERROR:main Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at TCP.onread (net.js:544:26)
2016-07-02 08:27:21 ERROR:main Terminating (exitcode=1)
```

Possibly the least helpful stack trace ever...

**Comment by Kegsay** [comment]
Related: https://github.com/matrix-org/matrix-appservice-irc/issues/37

**Comment by Kegsay** [comment]
Related stack traces:
```
2015-12-15 07:50:39 ERROR:main Error: socket hang up
    at createHangUpError (http.js:1472:15)
    at Socket.socketOnEnd [as onend] (http.js:1568:23)
    at Socket.g (events.js:180:16)
    at Socket.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

```
2015-12-13 06:46:32 ERROR:main FATAL EXCEPTION
2015-12-13 06:46:32 ERROR:main Error: read ECONNRESET
    at errnoException (net.js:901:11)
    at TCP.onread (net.js:556:19)
2015-12-13 06:46:32 ERROR:main Terminating (exitcode=1)
```

**Comment by Kegsay** [comment]
So it looks like the error is made here https://github.com/nodejs/node/blob/6b0352d79a67e4b7036177442156400f26253eef/lib/net.js#L544 and pushed onto the next tick here https://github.com/nodejs/node/blob/6b0352d79a67e4b7036177442156400f26253eef/lib/net.js#L444 which then emits an `error` event here https://github.com/nodejs/node/blob/6b0352d79a67e4b7036177442156400f26253eef/lib/net.js#L1256 which has nothing listening on it so it bubbles up as an uncaught exception, terminating the process.

`self` in this case is a `Socket`. So somewhere... *somewhere*... there is a Socket without an error listener. Yay.

**Comment by Kegsay** [comment]
So Matrix-side there are no long-lived connections (webhooks from the server) and there was no message being passed through at the time according to the logs. Based on that, I'm guessing it's the IRC connections?

**Comment by Kegsay** [comment]
It looks like the IRC connections are fine given https://github.com/matrix-org/node-irc/blob/master/lib/irc.js#L806

I've double-checked the logs for outbound Matrix requests, but there were no outstanding requests at the time of the crash (every request ID accounted for and no `DELAYED` or `DEAD` requests).

This would leave the Express app which is listening for HS requests. It looks like express itself is fine (no need to add `error` listeners), based on testing with `tcpkill` and:

```
curl -XPUT --limit-rate 1100 --upload-file debug.log "http://localhost:8888/transactions/2?access_token=...
```

I'm really at a loss here...

**Comment by Kegsay** [comment]
`tcpkill`ing IRC clients works as expected:
```
2016-07-04 14:43:45 ERROR:client-connection Server: localhost (boot) Network Error: {
  "code": "ECONNRESET",
  "errno": "ECONNRESET",
  "syscall": "read"
}
```

So where the hell is the unhandled error coming from?!

**Comment by Kegsay** [comment]
Found one in the ident service: if you get `ECONNRESET` there then it hard fails with the stack trace we expect. However, this cannot be the root cause here because we'd see a bunch of ident logging before it dies and we don't see that :sob:  It's not statsd since that's all UDP and the error / stack trace is clear it is TCP.

**Comment by Kegsay** [comment]
The ident service **is the root cause** :smiley: - I tried to pair up `CONNECT` and `CLOSE` ident requests and sure enough, there is exactly 1 more `CONNECT` than `CLOSE`, meaning that there was an ident TCP connection which was left open. This means that **there would be no ident logging around the fatal stack trace**. This would eventually timeout with `ECONNRESET` resulting in the panic! Specifically, the hanging ident connection occurred at 08:26:50, and 30s later it died.

**Comment by pranatha** [comment]
Hey there, how did you fix this issue at the end? 
i come with the same error.
