### ISSUE TITLE
reapUsers endpoint reaps more than it should

### ISSUE THREAD

**Issue by silkeh** [matrix-org/matrix-appservice-irc#841]
The `reapUsers` debug endpoint introduced in #772 seems to catch more users than it should.

We're using the endpoint in a weekly cron, with a `since` of 60 days (`60*24`). However, recent disconnects included users that were active more recently than that. For example a user that was actively chatting on September 23rd, and one that joined a channel on September 11th.

**Comment by Half-Shot** [comment]
I've not noticed this. Occasionally someone has complained, only to find that they hadn't actually spoken in >N days. If you've got some logs to prove otherwise, then I think we can keep this bug open. For now though, I've not been able find any evidence to say this is broken.
