### ISSUE TITLE
TLS Error on launch

### ISSUE THREAD

**Issue by j4m3s-s** [matrix-org/matrix-appservice-irc#859]
I encountered this error while trying to setup a bridge between irc and matrix (synapse) I just set up.

I'm using version (commit) e8b84e5b7e5f0c8d8375c46f4102cd3489e3c8c3

You'll find the config and error in the attached files.
[log.txt](https://github.com/matrix-org/matrix-appservice-irc/files/3800870/log.txt)
[config.txt](https://github.com/matrix-org/matrix-appservice-irc/files/3800874/config.txt)

**Comment by Half-Shot** [comment]
Fixed in https://github.com/matrix-org/matrix-appservice-irc/releases/tag/0.13.1
