### ISSUE TITLE
Can't !join rooms

### ISSUE THREAD

**Issue by jcgruenhage** [matrix-org/matrix-appservice-irc#903]
When sending `!join #channel` to @appservice-irc:matrix.org, I don't get a reply, and I don't get an invite either.

**Comment by Fuseteam** [comment]
I noticed i chanserv send me me a welcome message for joining ##c but i still didn't get an invite
it does seem to create a matrix room if the irc room doesn't already exist

**Comment by Half-Shot** [comment]
(This was fixed in #970)
