### ISSUE TITLE
Documentation on disconnecting idle users

### ISSUE THREAD

**Issue by Mikaela** [matrix-org/matrix-appservice-irc#906]
We have today again had I-line for a third party Matrix bridge broken by having 500 connections to PirateIRC. I have been asking the host, diasp.in, to disconnect idle users for months and they are telling that they are waiting for @Half-Shot for documentation on how to do that and @Half-Shot has said that it should be documented on September 14th (to clarify he has said that it should be documented, not given ETA).

> Generally speaking we just collect all the active users on the bridge using /joined_members on each room the bridge is in, and then check the last_seen time on the IP addresses logged by synapse. We run the /kill debugapi command against those used.
> \*users 

* https://matrix.to/#/!wkueYcSiKNkSSRLMXJ:diasp.in/$62XDU1Ej8PCXPNfmBv9ZFgXPRq5wZldPeN2GovJPBUg?via=diasp.in&via=privacytools.io&via=matrix.org

In July 10th even before that

>> https://github.com/matrix-org/matrix-appservice-irc/issues/388#issuecomment-509832528 - it's merged, will you look at it next weekend or are you waiting for it to get to a stable release?

> * Half-Shot needs to document it on the wi,i
> *wiki, even

* https://matrix.to/#/!wkueYcSiKNkSSRLMXJ:diasp.in/$VvD4sp4ipBuTtXfCZB5vivg58lcY_jaEm_yNmaEjsug?via=diasp.in&via=privacytools.io&via=matrix.org

**Comment by Half-Shot** [comment]
This has now been completed. https://github.com/matrix-org/matrix-appservice-irc/wiki/Debug-API
