### ISSUE TITLE
Catch-22 when seeking support

### ISSUE THREAD

**Issue by AndrewKvalheim** [matrix-org/matrix-appservice-irc#908]
When I attempt to join the [room for support](https://github.com/matrix-org/matrix-appservice-irc/wiki/Bridged-IRC-networks) for the freenode bridge I am immediately kicked:

> **You were kicked from IRC Matrix Bridges by @appservice-irc:matrix.org**
>
> Reason: IRC connection failure.

IRC connection issues are the reason I'm trying to join the room in the first place.

**Comment by Half-Shot** [comment]
Yes, for precisely the same reasons as #906. For the future, we are aware of this error and are continuing to try to find a path forward.
