### ISSUE TITLE
Messages with `m.in_reply_to` are not propagating to IRC

### ISSUE THREAD

**Issue by zouppen** [matrix-org/matrix-appservice-irc#915]
Stumbled upon this bug while investigating why Telegram-to-Telegram replies (generated by mautrix-telegram appservice) are not propagated to IRC ([see bug report](https://github.com/tulir/mautrix-telegram/issues/400)).

To reproduce, send the following minimal message from Matrix:

```
{
    "body": "testing",
    "msgtype": "m.text",
    "m.relates_to": {
	"event_id": "$15760700702709kXicd:hacklab.fi",
	"rel_type": "m.reference",
	"m.in_reply_to": {
            "event_id": "$15760700702709kXicd:hacklab.fi"
	}
    }
}
```

And then remove `m.in_reply_to` object and resend the message. The message is then propagating to IRC.

**Comment by Half-Shot** [comment]
>Clients that do support rich replies MUST provide the fallback format on replies, and MUST strip the fallback before rendering the reply. Rich replies MUST have a `format` of `org.matrix.custom.html` and therefore a `formatted_body` alongside the `body` and appropriate `msgtype`.

From https://matrix.org/docs/spec/client_server/r0.6.0#fallbacks-and-event-representation

The example you have given there is not a reply event according to the spec, and therefore the IRC bridge is not going to bridge it.
