### ISSUE TITLE
users are unable to join matrix channels when IRC connection is not working

### ISSUE THREAD

**Issue by lub** [matrix-org/matrix-appservice-irc#934]
Hi,

it seems you are unable to join e.g. Matrix HQ when the bridge is unable to join the IRC counter part. They get kicked because of "IRC connection failure."

Examples:
![image](https://user-images.githubusercontent.com/1029578/71364889-bd0c1400-259d-11ea-8bfa-5147452f49ed.png)

https://matrix.to/#/!OGEhHVWSdvArJzumhm:matrix.org/$6SHcrPBEhELIYtwJR7kfOMfneqjo3sTlVwctIridgws?via=matrix.org&via=t2bot.io&via=privacytools.io

![image](https://user-images.githubusercontent.com/1029578/71364912-cd23f380-259d-11ea-88eb-0cfa264678aa.png)

https://matrix.to/#/!BAXLHOFjvDKUeLafmO:matrix.org/$YBK/3Hd3nHHcJFX63cd0b1oJO2JM7O6rAaYYLQqMx88?via=matrix.org&via=privacytools.io&via=chat.weho.st

It's kind of a bad first impression, if people can't join some of the largest matrix rooms, because a centralized component isn't working correctly.

**Comment by Half-Shot** [comment]
Yep, this sucks but is working as intended. For reasons, we can't let users join freenode bridged rooms if they cannot get a IRC connection because of the potential to leak history to Matrix users without them being visible to IRC users.

FWIW, we've fixed the bridge so that #matrix and #matrix-dev are exempt from this rule and users will not be kicked from those channels.

**Comment by Mikaela** [comment]
> FWIW, we've fixed the bridge so that #matrix and #matrix-dev are exempt from this rule and users will not be kicked from those channels.

How about #matrix-irc where people are bound to ask about that? Do you have a formal protocol for exempting from the rule?

**Comment by lub** [comment]
I was afraid it was because of the freenode policy :/
But great to hear, that you have exemptions for some rooms now :)

Thank you for the update

**Comment by Half-Shot** [comment]
> > FWIW, we've fixed the bridge so that #matrix and #matrix-dev are exempt from this rule and users will not be kicked from those channels.
> 
> How about #matrix-irc where people are bound to ask about that? Do you have a formal protocol for exempting from the rule?

No, we just ask FN and then enact it if they OK it.

**Comment by Mikaela** [comment]
So the defacto-protocol is contacting freenode support and if they OK, you will change config?
