### ISSUE TITLE
Users who QUIT can end up stuck with a client that will never connect

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-appservice-irc#939]
The symptoms are that sending messages/joining rooms will not bridge across, and from the logs the requests seem to take forever to send and get dropped.

The problem is that these users have a defined `BridgedClient` instance, but the instance is not considered "dead" (at least, `isDead` reports `false`). However, the `ConnectionInstance` within is definitely `null`. The problem here is that messages/requests will queue up waiting for the thing to connect, which won't happen.

**Comment by Fuseteam** [comment]
Can #903 be related to this?

**Comment by Half-Shot** [comment]
No, I believe that was a parsing bug.

**Comment by Half-Shot** [comment]
Fixed in #1024
