### ISSUE TITLE
Formatted messages not being passed through to IRC

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/matrix-appservice-irc#94]
Specifically:
```
'<i>(edited)</i> ... another <font color="red">one</font> here => ... another <font color="green">message</font> here'
```

Because `sanitizeHtml` outputs:

```
'<i>(edited)</i> ... another <font color="red">one</font> here =&gt; ... another <font color="green">message</font> here'
```

which is not an exact match (note the `&gt;`). We should lax our check to allow escaped tags like this.

**Comment by Kegsay** [comment]
It's worth noting that this HTML is technically invalid because of the > (which should've been escaped).

**Comment by Kegsay** [comment]
Hmm, I'm not sure how much I fancy trying to handle mangled HTML - it's non-trivial using the parser I'm using. Plus, if we get it wrong, it'll be a mess of formatting on the IRC side. Punting this for now until we actually have a problem with this, and then maybe we can revisit it.

**Comment by leonerd** [comment]
I wouldn't worry about it for now; https://github.com/matrix-org/matrix-appservice-gitter/commit/c778b5ab9272ecab4c8fe9c1cce32e5e83f0a5d2 makes it a non-issue
