### ISSUE TITLE
Not connected to OFTC anymore

### ISSUE THREAD

**Issue by kroeckx** [matrix-org/matrix-appservice-irc#946]
NickServ on OFTC was complaining I was using a registered nick. I did in the past set my password. To try and fix it, I did a !storepass, and since #864 it then reconnects you. But I ended up with the wrong nick now, so I did !nick and !storepass again in the hope it was now fixed. But then it tried reconnected, and hasn't connected to IRC since. I've been disconnected since the the 28th of December 2019. If I try to do something like !whois, I get "unsafeClient not ready yet". I can still see the messages other people send to the channel, but I can't send a message back or do any private message.

**Comment by Half-Shot** [comment]
I believe this was because we were not reconnecting users to channels which was fixed in #979
