### ISSUE TITLE
Allow binding only to localhost instead of to 0.0.0.0

### ISSUE THREAD

**Issue by dakrone** [matrix-org/matrix-appservice-irc#95]
Currently when running the bridge, it listens on port 9999 on all interfaces.

It would be great if the bridge could listen only on 127.0.0.1:9999 when the matrix service is also running locally, so that the port isn't opened to the world.

**Comment by Kegsay** [comment]
This will need a new config option in the YAML, and then hooking it correctly into the AS lib.

**Comment by dakrone** [comment]
@Kegsay I started on this, but it will have to go through the matrix-appservice-node, and then matrix-appservice-bridge projects first in order to thread the required parameter through. Opened the first PR (linked) against matrix-appservice-node.

**Comment by Kegsay** [comment]
@dakrone Merged and released on NPM as 0.3.2

**Comment by ArchangeGabriel** [comment]
What the status here? I don’t really like to have port opened uselessly on my server…

**Comment by ArchangeGabriel** [comment]
I was surprised when I realized it has almost been a year since I pinged here. Anything new? :(

**Comment by ara4n** [comment]
yup, this just hasn't got to the top of the todo list yet. sorry :(

**Comment by Half-Shot** [comment]
@dakrone You'll be happy to know that a *mere* 1236 days days later, we have fixed this in #857
