### ISSUE TITLE
Bridge 0.14.0 doesn't start on Debian testing (NodeJS v10.18.1) - "Failed to run bridge"

### ISSUE THREAD

**Issue by alturiak** [matrix-org/matrix-appservice-irc#954]
After updating my bridge from 0.13.1 to 0.14.0 via git, it does not start anymore. None of the logfiles are written to.

Console output looks like this:
```
matrix-irc@matrix:~/matrix-appservice-irc$ node app.js -c config.yaml -f appservice-registration-irc.yaml -p 9999
(node:2719485) [DEP0091] DeprecationWarning: crypto.DEFAULT_ENCODING is deprecated.
(node:2719485) [DEP0010] DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node:2719485) [DEP0011] DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead.
(node:2719485) DeprecationWarning: prom-client - Passing a non-object to metrics constructor is deprecated
matrix-irc@matrix:~/matrix-appservice-irc$
```

Enabling console debug output adds `2020-01-20 20:58:26 ERROR:CLI Failed to run bridge.` to above messages.

I'm running the bridge on debian testing with kernel 5.3.0-3-amd64. NodeJS is on version v10.18.1 and I'm using NeDB. I have not tested it using postgres.

So far, I tried:
- running node app.js with -v
- creating a new configuration file
- running the bridge with empty "data"-directory
- setting up a new linux user to run the bridge from and installing by git clone, npm install, npm test (no obvious errors here)

without any changes to the outcome mentioned above.

**Comment by cremesk** [comment]
I have also the problem.

debian 10.2
npm 6.13.4
nodejs v10.18.1

**Comment by Half-Shot** [comment]
@alturiak Sorry to hear this, if you stick a console.log(err) on line https://github.com/matrix-org/matrix-appservice-irc/blob/0.14.0/app.js#L54, does it tell you what the error was?

**Comment by alturiak** [comment]
Wow, that was quick. I can confirm that 0.14.1 fixed the issue for me.
Thanks a lot! Greatly appreciated.
