### ISSUE TITLE
`User has been idle for 30+ days.`, no! that's not true!

### ISSUE THREAD

**Issue by pedro-nonfree** [matrix-org/matrix-appservice-irc#960]
> Seen by maskeduser at 2020-1-28 20:41

> 2020-1-30 12:30 @appservice-irc:matrix.org kicked maskeduser. **Reason**: User has been idle for 30+ days.

he has been kicked for being idle in less than 2 days, the **Reason** is incorrect.

And I hate when this happens. Early optimization is evil. The room has 37 members (but I remember we had a peak of 80), is this inefficient from the IRC side? for the IRC bridge? really? I thought it was for *larger rooms*

**Comment by Half-Shot** [comment]
I'm not sure what you mean by efficiency? This is so we can keep under out maximum limit of users imposed by the IRC network. If the user wasn't idle, could you give me the mxid of the user and I can investigate what happened.

**Comment by Half-Shot** [comment]
I've done some investigation. The user who was kicked had not interacted with the bridge since `12/12/2019 @ 11:49pm` and so was kicked entirely fairly.

**Comment by pedro-nonfree** [comment]
I put this discussion in `#irc:matrix.org` and I copy here two interesting replies from the room:

>  idle means not sending an irc message if I understand correctly. Reading does not count. It's a freenode thing

> Yes, sadly. Apparently Freenode doesn't like the idea of maintaining large amounts of idle irc connections, I can imagine it's quite the extra load. Then again, it's not too hard to send one message a month, or reconnect once a month.

@Half-Shot Can we **redefine** what is idle? This way, lurkers cannot *participate* in its way. What about saying that idle means that this person does not read any message in that particular room for 30 days (and we can know from matrix side because of read receipts).

**Comment by Half-Shot** [comment]
>What about saying that idle means that this person is not reading any message of the bridged channel from the matrix side since 30 days (and we can know from matrix side because of read receipts).

We can't rely on read receipts, not least because bridges do not support them yet. For now I am comfortable with excluding users who aren't talking/joining/leaving/PMing in any bridged channels for 30 days, and asking them to reconnect. It's a tough rule but it's the only way to ensure that new users who are trying to use the bridge aren't excluded because we have run out of connections. 

It's possible that I may raise the limit past 30 days, if we find that 30 days is reaping too many users.

**Comment by pedro-nonfree** [comment]
For the particular channel that made me fill this issue, I deactivated the IRC bridge there. The situation is: 60 people (well, now 39) on the matrix side vs 2 occasional IRC users. So I was gently open to IRC community. And now, as I see it happening, I will be closing them. I am not convinced by the reason to be kicked right now. Specially, for the people without the information in this ticket. I suggest to point to a link explaining why this is needed (Freenode forces us to do it) and what measure is implemented (excluding users who aren't talking/joining/leaving/PMing in any bridged channels for 30 days). Because it is impossible to explain in ~30 characters.

To consider lurkers I don't see any better way than processing the read receipts, hope one day it is implemented.

Maybe if I run my own irc bridge this is not going to happen. Because the target people and connections is low, right?
