### ISSUE TITLE
Bot not relay written messages to irc but from irc to matrix

### ISSUE THREAD

**Issue by djdomi** [matrix-org/matrix-appservice-irc#963]
Hi,

I am a new user and cant understand whats wrong.

I also tested already on 2 different networks and the bot can read the messages out of my channels and forward them to the matrix.

but in case if I write in the matrix it will not be replied to IRC without any error.

Does anyone have ideas?

**Comment by Half-Shot** [comment]
Which channels, and what is your mxid?

**Comment by djdomi** [comment]
what is a mxid?

I created a channel on my home server and connected to chat.godsandidols.com but even if I used Quakenet it was not working

**Comment by Half-Shot** [comment]
Ah, this isn't something I can help you with and you will need to speak to the administrator(s) of chat.godsandidols.com. This support channel is for admins of other IRC bridges and users of matrix.org hosted bridges.

**Comment by djdomi** [comment]
nope, as this is a public realted question i please you to tell me whats the difference between it would by placed on your server or on a other one, i mean it would be a benefit for all

**Comment by djdomi** [comment]
as written above, it doesn't matter chat.godsandidols.com was an example. Even if I use #quakenet or my IRC server, doesn't care, so why you unwilling to support your software, if you put it in public?!

**Comment by Half-Shot** [comment]
As I mentioned: 

>This support channel is for admins of other IRC bridges and users of matrix.org hosted bridges.

I can't help users using other bridges because I do not have access to log files, and you do not have the ability to give me them. I'm totally willing to support software if I have the means to do so :). If you are running your own instance of `matrix-appservice-irc`, you can open a bug report with logs.

**Comment by djdomi** [comment]
i ran my own bridge on my own server and i use just an public irc server. i provides them tomorrow
