### ISSUE TITLE
Bridge not transporting from Matrix to IRC

### ISSUE THREAD

**Issue by djdomi** [matrix-org/matrix-appservice-irc#966]
Dear All

First, I'm running my own server which runs a matrix instance and telegram and also this IRC Bridge.
The Server itself works fine and also the Telegram bridge, but the problem is the IRC-Bridge.

If I type on a (random, here in example chat.godsandidols.com) IRC-Server a text, it works in the direction to the matrix. but not Vise versa.
I attached the Error, Debug, and Config-Files.

- [config_upload.yaml.txt](https://github.com/matrix-org/matrix-appservice-irc/files/4152098/config_upload.yaml.txt)
- [debug.log](https://github.com/matrix-org/matrix-appservice-irc/files/4152067/debug.log)
- [errors.log](https://github.com/matrix-org/matrix-appservice-irc/files/4152069/errors.log)

I am open for any suggestions to fix this

**Comment by Half-Shot** [comment]
Looks like you aren't getting any `/transactions` from your homeserver. Is your homeserver trying to send to the bridge and cannot reach it? Check your synapse logs.

**Comment by djdomi** [comment]
> Looks like you aren't getting any `/transactions` from your homeserver. Is your homeserver trying to send to the bridge and cannot reach it? Check your synapse logs.

[homeserver.log.gz](https://github.com/matrix-org/matrix-appservice-irc/files/4154425/homeserver.log.gz)

ive put in here the log for you @Half-Shot

**Comment by djdomi** [comment]
update: it seems i forgot to update the config, but still no writing to irc i continue tomorrow to upload a new logfile

**Comment by djdomi** [comment]
Update:

i had now some spare time, i closed every programm, and started it again now the bridge works
