### ISSUE TITLE
Implement the !kick command

### ISSUE THREAD

**Issue by dakrone** [matrix-org/matrix-appservice-irc#98]
It would be great if the `!kick` command were implemented, currently in order to kick someone, I have to:

- disconnect the bridge (because ops are linked to my nick)
- reconnect to IRC with an IRC client
- kick/ban the user from the room
- disconnect on the IRC client
- restart the bridge and have it reconnect to the room

**Comment by Kegsay** [comment]
We support kicks natively now (so just kick them on Matrix/IRC)
