### ISSUE TITLE
Problems with changing nick

### ISSUE THREAD

**Issue by Exalm** [matrix-org/matrix-appservice-irc#980]
![Screenshot from 2020-02-14 16-23-26](https://user-images.githubusercontent.com/1510457/74526956-7511c980-4f1c-11ea-8666-50c6c427db82.png)

This happens on gimpnet. Unfortunately I don't have more info.

**Comment by Half-Shot** [comment]
The bug is that if you specify `exalm` then it appends a number? This is probably because an `exalm` exists on the network already and it's trying to avoid the name clash. We should probably add a check to ensure that you aren't about to clash with someone's nick, though.

**Comment by Exalm** [comment]
Well, yes, but even other than that look how it selected the nick:

`exalm` - > `exalm1` - ok, fair enough.

Next time. `exalm2`. Fair enough.

`exalm3. Ditto and I changed it to that explicitly.

`exal4` - what? Where's the letter m?

`exalm[m]` - ok.

`exal6` - What? No `m` again and where did 5 go?

**Comment by Half-Shot** [comment]
Strange, I can't find any logging for this. Was this just now?

**Comment by Exalm** [comment]
No, 5 days ago. It was on matrix.org HS though.

**Comment by Half-Shot** [comment]
I believe this has been fixed in #1018, as I believe this bug was caused due to a nick conflict.
