### ISSUE TITLE
Homeserver URL seems overloaded

### ISSUE THREAD

**Issue by warthog9** [matrix-org/matrix-appservice-irc#983]
The config.yaml homeserver: url seems a bit overloaded since it's used both to define where to connect to, and where to point URLs that may need to be displayed.  Since it's possible these may need to be different (to force internal routing for bridge to homeserver connections, and obviously something different for external links) I'd propose breaking this up in the following way:

url - continues to define where the homeserver is
external_url - if this is set is used in url's stead for links given out.  If empty, it defaults to what's in url.

This is mostly a bug looking at feedback since I just tripped over a similar problem to what's described above and, while working around it with /etc/hosts files works - seems less optimal and far more fragile / incorrect.  (happy to do up the patch to make this work, just wanted to get some feedback before doing it)

**Comment by Half-Shot** [comment]
We already have [`media_url`](https://github.com/matrix-org/matrix-appservice-irc/blob/master/config.sample.yaml#L12) in the config already, which is used for links (media urls). I don't think we need to change anything here?

**Comment by Half-Shot** [comment]
Closing as I think this is invalid.
