### ISSUE TITLE
NPM releases several versions out of date

### ISSUE THREAD

**Issue by ajs124** [matrix-org/matrix-appservice-irc#987]
The latest version published to [npm](https://www.npmjs.com/package/matrix-appservice-irc?activeTab=versions) is 0.13.0 from 5 months ago. Is there any reason for this? What is your release process and (why) does it not include publishing to npm?

**Comment by Half-Shot** [comment]
No reason, it just got lost for a while while we were figuring out a docker process too. I've published 0.15.2 to NPM.
